'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),{spawnSync}=require('node:child_process');
const{lodDerivativeSpecs}=require('../server/lodDerivativePolicy');
test('native tiles are audited at their storage root and regenerate only from OBJ',()=>{assert.deepEqual(lodDerivativeSpecs([{kind:'tiles',rootKey:'datasets',relativePath:'import/3d_tiles/model/tileset.json'},{kind:'glb',rootKey:'datasets',relativePath:'import/model.glb'},{kind:'obj',rootKey:'datasets',relativePath:'import/model.obj'}],{meshDerivativesEnabled:true}),[{type:'lod_audit',request:{tilesRootKey:'datasets',tilesRelativePath:'import/3d_tiles/model',generateFromObjOnFailure:true,optional:true}}]);});
test('native tile audits remain active while automatic generation is disabled',()=>{assert.deepEqual(lodDerivativeSpecs([{kind:'tiles',rootKey:'datasets',relativePath:'import/3d_tiles/model/tileset.json'},{kind:'glb',rootKey:'datasets',relativePath:'import/model.glb'},{kind:'obj',rootKey:'datasets',relativePath:'import/model.obj'}],{meshDerivativesEnabled:false}),[{type:'lod_audit',request:{tilesRootKey:'datasets',tilesRelativePath:'import/3d_tiles/model',generateFromObjOnFailure:false,optional:true}}]);});
test('missing tiles queue Obj2Tiles only with OBJ plus an auditable GLB fallback',()=>{assert.deepEqual(lodDerivativeSpecs([{kind:'obj',relativePath:'model.obj'},{kind:'glb',relativePath:'model.glb'}],{meshDerivativesEnabled:true}),[{type:'mesh_tiles',request:{optional:true}}]);assert.deepEqual(lodDerivativeSpecs([{kind:'obj',relativePath:'model.obj'}],{meshDerivativesEnabled:true}),[]);assert.deepEqual(lodDerivativeSpecs([{kind:'glb',relativePath:'model.glb'}],{meshDerivativesEnabled:true}),[]);assert.deepEqual(lodDerivativeSpecs([{kind:'obj',relativePath:'model.obj'},{kind:'glb',relativePath:'model.glb'}],{meshDerivativesEnabled:false}),[]);});
test('native tiles without a GLB audit source do not queue work and remain in private storage only',()=>{assert.deepEqual(lodDerivativeSpecs([{kind:'tiles',rootKey:'datasets',relativePath:'import/3d_tiles/model/tileset.json'},{kind:'obj',rootKey:'datasets',relativePath:'import/model.obj'}],{meshDerivativesEnabled:true}),[]);});
test('runtime pins Obj2Tiles, enables audited production generation independently, and invokes its bounded texture-atlas contract',()=>{const root=path.resolve(__dirname,'..'),docker=fs.readFileSync(path.join(root,'Dockerfile'),'utf8'),worker=fs.readFileSync(path.join(root,'server','derivativeWorker.js'),'utf8'),compose=fs.readFileSync(path.join(root,'docker-compose.yml'),'utf8'),config=fs.readFileSync(path.join(root,'server','config.js'),'utf8');assert.match(docker,/OBJ2TILES_VERSION=1\.6\.2/);assert.match(docker,/34a576e0b8ebbd73da5e2271d238724a9b39be3ee1edc167214b5b28bed2baa0/);assert.match(docker,/b5252158f81a3d5659a978d1468f7c8915f3794e11359dfeb351e5eeaac48ed5/);assert.match(docker,/40adc90db9f019d1d976badc1733a5acc69d43cd1db34bf0ebc823f554188274/);assert.match(docker,/c54dbcbe953640f2aa0e7c2568709108a97063dac492781c9560a5042e46d9b1/);assert.match(docker,/executable_digest\s+\/opt\/obj2tiles\/Obj2Tiles/);assert.match(docker,/ENV OBJ2TILES_BIN=\/opt\/obj2tiles\/Obj2Tiles/);assert.match(compose,/MESH_DERIVATIVES_ENABLED:\s*\$\{MESH_DERIVATIVES_ENABLED:-true\}/);assert.match(config,/meshDerivativesEnabled:\s*bool\(process\.env\.MESH_DERIVATIVES_ENABLED, true\)/);assert.doesNotMatch(config,/meshDerivativesEnabled:[^\n]*LOCAL_DERIVATIVES_ENABLED/);assert.match(worker,/\['--octree', '--lods', '3', '--divisions', '2', '--lod-texture-scale', '0\.5', '--local', source, incomplete\]/);assert.doesNotMatch(worker,/--keeptextures/);assert.match(worker,/auditSource,[\s\S]*'--controlled-obj2tiles',[\s\S]*source,[\s\S]*config\.obj2TilesBin/);assert.equal((worker.match(/'--controlled-obj2tiles'/g)||[]).length,1);assert.match(worker,/run\(process\.execPath, \[audit, tiles, source, '--external-source'\]/);assert.doesNotMatch(worker,/config\.obj2TilesBin,\s*\['-i'/);});
test('server fallback enables mesh derivatives while explicit false remains authoritative',()=>{const root=path.resolve(__dirname,'..'),probe=(value)=>{const env={...process.env};if(value===undefined)delete env.MESH_DERIVATIVES_ENABLED;else env.MESH_DERIVATIVES_ENABLED=value;const result=spawnSync(process.execPath,['-e',"process.stdout.write(String(require('./server/config').config.meshDerivativesEnabled))"],{cwd:root,env,encoding:'utf8'});assert.equal(result.status,0,result.stderr);return result.stdout;};assert.equal(probe(undefined),'true');assert.equal(probe('false'),'false');});
