import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {preflightPointSurface} from '../server/measurementPointSurface.mjs';
import {createMeasurementSurfaceClient} from '../measurement-surface-client.mjs';
import {retainedDisplayBoundary} from '../measurement-display-elevations.mjs';
const require=createRequire(import.meta.url),express=require('express');
const {DatabaseSync}=require('node:sqlite');
const {applyMigrations}=require('../server/database');
const {ViewerRepository}=require('../server/repository');
const {ProcessingRepository}=require('../server/processingRepository');
const {MeasurementRepository}=require('../server/measurementRepository');
const {MeasurementCalculationRepository}=require('../server/measurementCalculationRepository');
const {createMeasurementApi}=require('../server/measurementApi');
const {processOneMeasurementCalculation}=require('../server/measurementCalculationWorker');
const auth=require('../server/auth');

test('signed-in client point volume and attached section execute the shipped child against verified source nodes',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'viewer-point-http-'));
  t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  fs.mkdirSync(path.join(root,'ept-data'));fs.mkdirSync(path.join(root,'ept-hierarchy'));
  const files=[],write=(relative,value)=>{const bytes=Buffer.isBuffer(value)?value:Buffer.from(JSON.stringify(value));fs.writeFileSync(path.join(root,relative),bytes);const f={relativePath:relative,byteSize:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};files.push(f);return f;};
  const horizontal='PROJCS["WGS84 UTM16N",GEOGCS["WGS84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-87],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1],AXIS["Easting",EAST],AXIS["Northing",NORTH]]';
  const header=write('ept.json',{bounds:[0,0,0,2,2,4],dataType:'binary',srs:{wkt:`COMPD_CS["Survey",${horizontal},VERT_CS["Height",VERT_DATUM["Survey datum",2005],UNIT["metre",1],AXIS["Height",UP]]]`},schema:['X','Y','Z'].map(name=>({name,type:'floating',size:8}))});
  write('ept-hierarchy/0-0-0-0.json',{'0-0-0-0':4});
  const bytes=Buffer.alloc(96);[[.5,.5,1],[1.5,.5,2],[.5,1.5,3],[1.5,1.5,4]].forEach((p,i)=>p.forEach((v,j)=>bytes.writeDoubleLE(v,i*24+j*8)));write('ept-data/0-0-0-0.bin',bytes);
  const database=new DatabaseSync(':memory:');database.exec('PRAGMA foreign_keys=ON');applyMigrations(database);t.after(()=>database.close());
  const repository=new ViewerRepository(database),processing=new ProcessingRepository(database),measurements=new MeasurementRepository(database),jobs=new MeasurementCalculationRepository(database);
  const model=repository.upsertModelVersion({provider:'webodm',providerModelId:'point',providerVersionId:'v1',displayName:'Point fixture',status:'ready',assets:[{kind:'ept',format:'ept',rootKey:'models',relativePath:'ept.json',byteSize:header.byteSize,sha256:header.sha256,manifestSha256:crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex'),manifestFiles:files}]});
  const principal={modelId:model.id,modelVersionId:model.activeVersion.id,subject:'client-one',audience:'client'},token=crypto.randomBytes(32).toString('base64url');
  repository.createViewerSession({...principal,tokenHash:auth.hashToken(token),permissions:{view:true,measure:true,personalMeasurements:true},expiresAt:new Date(Date.now()+3600000).toISOString()});
  const document={id:crypto.randomUUID(),name:'Pile',kind:'polygon',collection:'spatial3d',vertices:[[0,0,0],[2,0,0],[2,2,0],[0,2,0]],coordinateReference:{crs:'EPSG:32616',verticalUnit:'m'}};
  let measurement=measurements.create(principal,document).measurement;
  const app=express();app.use(express.json());app.use('/measurements',createMeasurementApi(repository,{preflightPoint:request=>preflightPointSurface(path.join(root,'ept.json'),request,{requireEncodedVerticalUnits:true})}));
  const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});t.after(()=>new Promise(resolve=>server.close(resolve)));
  const client=createMeasurementSurfaceClient({token:()=>token,context:()=>principal,fetcher:(url,options)=>fetch(`http://127.0.0.1:${server.address().port}${url.replace('/api/v1/measurements','/measurements')}`,options)});
  const post=body=>client('create',{measurementId:measurement.id,request:body},measurement);
  const deps={repository,processing,storage:{resolve:()=>path.join(root,'ept.json')},config:{measurementTimeoutMs:10000}};
  const response=await post({revision:1,method:'point-surface-cut-fill',sourceAssetId:model.activeVersion.assets[0].id,cellSizeM:1,reference:{type:'custom',elevationM:0}});
  const queued=response.calculation;assert.equal(queued.status,'queued');
  await processOneMeasurementCalculation(deps,'point-volume');
  const parent=jobs.get(measurement.id,queued.id);assert.equal(parent.status,'complete',parent.errorCode);assert.equal(parent.result.cutM3,10);
  assert.equal(parent.result.source.verticalUnitBasis,'ept-vertical-crs');
  measurement=measurements.update(principal,measurement.id,{...document,revision:1,results:{...parent.result,calculationJobId:parent.id}});
  assert.equal(jobs.get(measurement.id,parent.id).attachmentRevision,measurement.revision);
  const profileResponse=await post({revision:measurement.revision,method:'surface-transect',parentCalculationId:parent.id,line:{start:[0,.5],end:[2,.5]}});
  const profileJob=profileResponse.calculation;assert.equal(profileJob.status,'queued');
  await processOneMeasurementCalculation(deps,'point-profile');
  const profile=jobs.get(measurement.id,profileJob.id);assert.equal(profile.status,'complete',profile.errorCode);
  assert.equal(profile.result.sampling,'point-grid-step');
  assert.equal(profile.result.segments.reduce((sum,s)=>sum+(s.endM-s.startM)*s.surfaceM,0),3);
  assert.equal(measurements.get(principal,measurement.id).revision,2);
  assert.equal(jobs.get(measurement.id,parent.id).result.cutM3,10);
  await t.test('map triangulated volume retains display boundary after HTTP save and reload',async()=>{
    const mapDocument={...document,id:crypto.randomUUID(),name:'Map boundary',collection:'map'};
    const http=async(method,suffix,body)=>{
      const response=await fetch(`http://127.0.0.1:${server.address().port}/measurements${suffix}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
      const data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data;
    };
    measurement=(await http('POST','',mapDocument)).measurement;
    const accepted=await post({revision:measurement.revision,method:'point-surface-cut-fill',sourceAssetId:model.activeVersion.assets[0].id,cellSizeM:1,reference:{type:'boundary-triangulated'}});
    await processOneMeasurementCalculation(deps,'map-point-volume');
    const completed=(await client('status',{measurementId:measurement.id,jobId:accepted.calculation.id},measurement)).calculation;
    assert.equal(completed.status,'complete',completed.errorCode);
    assert.equal(completed.result.calculationOrigin,'server-original-point-surface');
    assert.deepEqual(completed.result.boundaryVertices,[[0,0,1],[2,0,2],[2,2,4],[0,2,3]]);
    const {preview,...results}=completed.result;
    const saved=(await http('PUT',`/${measurement.id}`,{...mapDocument,revision:measurement.revision,results:{...results,calculationJobId:completed.id}})).measurement;
    const reloaded=(await http('GET',`/${measurement.id}`)).measurement;
    assert.equal(jobs.get(measurement.id,completed.id).attachmentRevision,reloaded.revision);
    assert.deepEqual(reloaded.results.boundaryVertices,completed.result.boundaryVertices);
    assert.deepEqual(reloaded.results.source,completed.result.source);
    assert.equal(reloaded.results.netM3,completed.result.netM3);
    assert.equal(reloaded.revision,saved.revision);
    assert.equal(reloaded.results.calculationOrigin,'browser','saved payloads never attest their own server provenance');
    const authorized=(await client('status',{measurementId:reloaded.id,jobId:reloaded.results.calculationJobId},reloaded)).calculation;
    assert.equal(authorized.attachmentRevision,reloaded.revision);
    assert.equal(authorized.id,reloaded.results.calculationJobId);assert.equal(authorized.measurementId,reloaded.id);
    const before=JSON.stringify(reloaded),retained=retainedDisplayBoundary({...reloaded,results:authorized.result},model.activeVersion.id);
    assert.ok(retained,'trusted saved point-grid boundary is eligible in the 3D viewer');
    assert.deepEqual(retained.vertices,completed.result.boundaryVertices);
    assert.equal(JSON.stringify(reloaded),before,'display eligibility never mutates saved values');
  });
});
