'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const express=require('express');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const auth=require('../server/auth');
const {config}=require('../server/config');
const {openDatabase}=require('../server/database');
const {createProcessingApi}=require('../server/processingApi');
const {ProcessingRepository}=require('../server/processingRepository');
const {ViewerRepository}=require('../server/repository');
const {StorageManager}=require('../server/storageManager');

test('processing readiness fails closed when API and worker mesh generation settings differ',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-readiness-'));
  for(const name of['datasets','models','cache','trash','imports'])fs.mkdirSync(path.join(root,name));
  const db=openDatabase(path.join(root,'viewer.sqlite')),processing=new ProcessingRepository(db),repository=new ViewerRepository(db),storage=new StorageManager({datasetsMount:path.join(root,'datasets'),modelsMount:path.join(root,'models'),cacheMount:path.join(root,'cache'),trashMount:path.join(root,'trash'),datasetImportMount:path.join(root,'imports'),storageReserveBytes:0,storageReservePercent:0});
  storage.initialize();
  const token='readiness-token-0000000000000000000000';
  processing.createAdminSession({tokenHash:auth.hashToken(token),subject:'ops:readiness',permissions:['viewer.processing.read'],displayUnits:'imperial',expiresAt:new Date(Date.now()+60000).toISOString()});
  processing.recordWorkerHeartbeat('worker-old',{meshDerivatives:!config.meshDerivativesEnabled});
  const app=express();app.use(express.json());app.use(createProcessingApi({repository,processing,storage}));
  const server=await new Promise(resolve=>{const value=app.listen(0,'127.0.0.1',()=>resolve(value));});
  t.after(()=>new Promise(resolve=>server.close(()=>{db.close();fs.rmSync(root,{recursive:true,force:true});resolve();})));
  const url=`http://127.0.0.1:${server.address().port}/api/v1/processing/ready`,headers={authorization:`Bearer ${token}`};
  const mismatched=await fetch(url,{headers});
  assert.equal(mismatched.status,503);
  assert.deepEqual((await mismatched.json()).configuration,{meshDerivativesEnabled:config.meshDerivativesEnabled,workerMeshDerivativesEnabled:!config.meshDerivativesEnabled,mismatch:true});
  processing.recordWorkerHeartbeat('worker-legacy',{});
  const undeclared=await fetch(url,{headers});
  assert.equal(undeclared.status,503);
  assert.deepEqual((await undeclared.json()).configuration,{meshDerivativesEnabled:config.meshDerivativesEnabled,workerMeshDerivativesEnabled:null,mismatch:true});
  processing.recordWorkerHeartbeat('worker-new',{meshDerivatives:config.meshDerivativesEnabled});
  const matched=await fetch(url,{headers});
  assert.equal(matched.status,200);
  assert.equal((await matched.json()).configuration.mismatch,false);
});
