'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const {sha256Hex,signature}=require('../server/serviceAuth');const {signViewerEvent}=require('../server/viewerEvents');const {optionArray}=require('../server/nodeOdmProvider');
const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures','viewer-processing-contract-v1.json'),'utf8'));
const routeFixtureBytes=fs.readFileSync(path.join(__dirname,'fixtures','viewer-processing-route-responses-v1.json'));
test('admin grant golden HMAC contract matches Ops bytes',()=>{const f=fixture.adminGrant;assert.equal(sha256Hex(Buffer.from(f.body)),f.contentSha256);assert.equal(signature(f.secret,{method:f.method,path:f.path,timestamp:f.timestamp,nonce:f.nonce,bodySha256:f.contentSha256}),f.signature);});
test('processing callback golden HMAC contract matches Ops bytes',()=>{const f=fixture.processingEvent;const headers=signViewerEvent({secret:f.secret,keyId:f.keyId,method:f.method,path:f.path,body:f.body,timestamp:f.timestamp,nonce:f.nonce});assert.equal(headers['X-LTDS-Viewer-Content-SHA256'],f.contentSha256);assert.equal(headers['X-LTDS-Viewer-Signature'],f.signature);});
test('ODM option serialization preserves explicit false',()=>assert.deepEqual(optionArray({'dsm':false,'fast-orthophoto':true}),[{name:'dsm',value:false},{name:'fast-orthophoto',value:true}]));
test('Viewer and Ops pin the exact route-response byte corpus',()=>{assert.equal(sha256Hex(routeFixtureBytes),'2e71ab8ca396aadbbba254ba528dcf4ea27e1d55376d079f2e514da1d8e7eeaa');const routes=JSON.parse(routeFixtureBytes);assert.equal(routes.operations.uploadFinalizeAccepted.status,202);assert.equal(routes.operations.uploadFinalizeAccepted.headers.Location,'/api/v1/operations/11111111-1111-4111-8111-111111111111');assert.equal(routes.tasks.tasks[0].latestAttempt.capabilityFingerprint,null);assert.equal(routes.providers.providers[0].activeAttempts,1);assert.equal(routes.presets.presets[0].providerType,null);});
