'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const {openDatabase}=require('../server/database');
const {ProcessingRepository}=require('../server/processingRepository');
const {ViewerRepository}=require('../server/repository');
const {StorageManager}=require('../server/storageManager');
const {applyStorageMutation,reconcileStorageMutations,purgeExpiredTrash}=require('../server/storageLifecycle');
const {processSubmit}=require('../server/processingWorker');
const {shareUnlockRateKey}=require('../server/shareApi');

function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-v10-'));for(const name of['datasets','models','cache','trash','imports'])fs.mkdirSync(path.join(root,name));const db=openDatabase(path.join(root,'viewer.sqlite')),processing=new ProcessingRepository(db),repository=new ViewerRepository(db),storage=new StorageManager({datasetsMount:path.join(root,'datasets'),modelsMount:path.join(root,'models'),cacheMount:path.join(root,'cache'),trashMount:path.join(root,'trash'),datasetImportMount:path.join(root,'imports'),storageReserveBytes:0,storageReservePercent:0});storage.initialize();t.after(()=>{db.close();fs.rmSync(root,{recursive:true,force:true});});return{root,db,processing,repository,storage};}
function finalizedDataset(context,project,count=1,label='Dataset'){const relativePath=crypto.randomUUID(),dataset=context.processing.createDataset({projectId:project.id,displayName:label,storageMode:'managed',rootKey:'datasets',relativePath}),directory=path.join(context.root,'datasets',relativePath),files=[];fs.mkdirSync(directory,{recursive:true});for(let i=0;i<count;i++){const body=Buffer.from(`image-${i}`),relative=`photo-${String(i).padStart(3,'0')}.jpg`,sha256=crypto.createHash('sha256').update(body).digest('hex');fs.writeFileSync(path.join(directory,relative),body);files.push({relativePath:relative,byteSize:body.length,sha256});}context.processing.finalizeDataset(dataset.id,files,crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex'));return context.processing.getDataset(dataset.id,true);}

test('project and dataset tags are normalized and reassociation preserves immutable storage',(t)=>{const c=fixture(t),first=c.processing.createProject({displayName:'First',tags:[' Survey ','survey','2026']}),second=c.processing.createProject({displayName:'Second'}),dataset=finalizedDataset(c,first,1,'Flight');assert.deepEqual(first.tags,['Survey','2026']);const moved=c.processing.updateDatasetMetadata(dataset.id,{projectId:second.id,tags:['North',' north '],description:'Catalog-only edit'});assert.equal(moved.projectId,second.id);assert.deepEqual(moved.tags,['North']);assert.equal(moved.rootKey,dataset.rootKey);assert.equal(moved.relativePath,dataset.relativePath);assert.equal(moved.manifestSha256,dataset.manifestSha256);const occupied=finalizedDataset(c,first,1,'Occupied'),task=c.processing.createTask({projectId:first.id,datasetId:occupied.id,displayName:'Existing task'});assert.ok(task);assert.throws(()=>c.processing.updateDatasetMetadata(occupied.id,{projectId:second.id}),{code:'dataset_reassociation_blocked'});finalizedDataset(c,second,1,'Collision');assert.throws(()=>c.processing.updateDatasetMetadata(dataset.id,{displayName:'Collision'}),{code:'dataset_name_conflict'});assert.throws(()=>c.processing.updateProject(second.id,{displayName:'First'}),{code:'project_name_conflict'});});

test('submit resumes after init, upload-batch and commit ambiguity without duplicating files',async(t)=>{const c=fixture(t),project=c.processing.createProject({displayName:'Resume'}),dataset=finalizedDataset(c,project,25),task=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Resume task'}),provider=c.processing.upsertProvider({type:'nodeodm',displayName:'ODM',endpoint:'http://127.0.0.1:3000',enabled:true}),attempt=c.processing.createAttempt({taskId:task.id,providerId:provider.id,options:{'pc-ept':true}}),job=c.processing.claimJob('worker-a'),remote={exists:false,imagesCount:0,status:'queued_upstream',initCalls:0,uploadCalls:0,commitCalls:0,removeCalls:0};c.storage.requireProcessingHeadroom=()=>({});const adapter={async status(){if(!remote.exists)throw Object.assign(new Error('missing'),{code:'provider_task_not_found'});return{status:remote.status,progress:0,imagesCount:remote.imagesCount};},async initialize(){remote.exists=true;remote.initCalls++;if(remote.initCalls===1)throw new Error('crash after init');},async upload(_uuid,files){remote.imagesCount+=files.length;remote.uploadCalls++;if(remote.uploadCalls===1)throw new Error('crash after first upload batch');},async commit(){remote.commitCalls++;remote.status='running';if(remote.commitCalls===1)throw new Error('crash after commit');},async remove(){remote.removeCalls++;remote.exists=false;remote.imagesCount=0;}};const deps={processing:c.processing,storage:c.storage,config:{},signal:new AbortController().signal,adapterFactory:()=>adapter};await assert.rejects(processSubmit(job,deps),/after init/);assert.equal(c.processing.getAttemptSubmission(attempt.id).submissionPhase,'initializing');await assert.rejects(processSubmit(job,deps),/upload batch/);assert.equal(c.processing.getAttemptSubmission(attempt.id).uploadedFileCount,0);await assert.rejects(processSubmit(job,deps),/after commit/);assert.equal(c.processing.getAttemptSubmission(attempt.id).submissionPhase,'committing');await processSubmit(job,deps);const resumed=c.processing.getAttemptSubmission(attempt.id);assert.equal(resumed.submissionPhase,'committed');assert.equal(resumed.uploadedFileCount,25);assert.equal(remote.initCalls,1);assert.equal(remote.uploadCalls,2);assert.equal(remote.commitCalls,1);assert.equal(remote.removeCalls,0);assert.equal(c.db.prepare("SELECT COUNT(*) AS n FROM processing_jobs WHERE attempt_id=? AND job_type='reconcile' AND status='pending'").get(attempt.id).n,1);});

test('ambiguous GCP auxiliary upload removes and safely restarts the provider task',async(t)=>{const c=fixture(t),project=c.processing.createProject({displayName:'GCP resume'}),relativePath=crypto.randomUUID(),draft=c.processing.createDataset({projectId:project.id,displayName:'GCP data',storageMode:'managed',rootKey:'datasets',relativePath}),directory=path.join(c.root,'datasets',relativePath),specs=[['photo.jpg','image'],['gcp_list.txt','EPSG:4326\n1 2 3 4 5 photo.jpg']];fs.mkdirSync(directory,{recursive:true});const files=specs.map(([name,body])=>{fs.writeFileSync(path.join(directory,name),body);return{relativePath:name,byteSize:Buffer.byteLength(body),sha256:crypto.createHash('sha256').update(body).digest('hex')};});c.processing.finalizeDataset(draft.id,files,crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex'));const task=c.processing.createTask({projectId:project.id,datasetId:draft.id,displayName:'GCP task'}),provider=c.processing.upsertProvider({type:'nodeodm',displayName:'ODM',endpoint:'http://127.0.0.1:3000',enabled:true}),attempt=c.processing.createAttempt({taskId:task.id,providerId:provider.id,options:{}}),job=c.processing.claimJob('worker-gcp'),remote={exists:false,imagesCount:0,init:0,photo:0,aux:0,remove:0,commit:0};c.storage.requireProcessingHeadroom=()=>({});const adapter={async status(){if(!remote.exists)throw Object.assign(new Error('missing'),{code:'provider_task_not_found'});return{status:'queued_upstream',progress:0,imagesCount:remote.imagesCount};},async initialize(){remote.exists=true;remote.init++;},async upload(_uuid,batch){if(batch.some((file)=>file.relativePath.endsWith('.txt'))){remote.aux++;if(remote.aux===1)throw new Error('auxiliary upload response lost');}else{remote.photo++;remote.imagesCount+=batch.length;}},async remove(){remote.remove++;remote.exists=false;remote.imagesCount=0;},async commit(){remote.commit++;}};const deps={processing:c.processing,storage:c.storage,config:{},signal:new AbortController().signal,adapterFactory:()=>adapter};await assert.rejects(processSubmit(job,deps),/response lost/);assert.equal(c.processing.getAttemptSubmission(attempt.id).submissionPhase,'uploading_auxiliary');await processSubmit(job,deps);assert.equal(remote.remove,1);assert.equal(remote.init,2);assert.equal(remote.photo,2);assert.equal(remote.aux,2);assert.equal(remote.commit,1);});

test('model output accounting and journaled archive trash restore retention purge remain consistent',(t)=>{const c=fixture(t),project=c.processing.createProject({displayName:'Outputs'}),dataset=finalizedDataset(c,project),task=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Output task'}),provider=c.processing.upsertProvider({type:'nodeodm',displayName:'ODM',endpoint:'http://127.0.0.1:3000',enabled:true}),attempt=c.processing.createAttempt({taskId:task.id,providerId:provider.id,options:{}}),directory=path.join(c.root,'models',task.id,attempt.id),file=path.join(directory,'model.glb');fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(file,'model-output');const sha256=crypto.createHash('sha256').update('model-output').digest('hex'),model=c.repository.upsertModelVersion({provider:'ltds-processing',providerModelId:task.id,providerVersionId:attempt.id,displayName:task.displayName,sourceLocator:{taskId:task.id,attemptId:attempt.id},status:'ready',assets:[{kind:'glb',rootKey:'models',relativePath:`${task.id}/${attempt.id}/model.glb`,byteSize:12,sha256,published:false}],makeActive:false}),version=c.db.prepare('SELECT id FROM model_versions WHERE model_id=?').get(model.id);c.processing.setAttemptResult(attempt.id,model.id,version.id);c.processing.transitionAttempt(attempt.id,'ready_for_review',{progress:1});c.processing.registerModelOutput({versionId:version.id,modelId:model.id,taskId:task.id,attemptId:attempt.id,projectId:project.id,relativePath:`${task.id}/${attempt.id}`,byteSize:12,assetCount:1});const projectStorage=c.processing.projectStorage(project.id);assert.equal(projectStorage.project.datasetBytes,dataset.byteSize);assert.equal(projectStorage.project.outputBytes,12);assert.equal(c.processing.taskStorage(task.id).outputs.length,1);assert.equal(c.processing.archiveModelOutput(version.id).status,'archived');const trashMutation=c.processing.beginOutputTrashMutation(version.id,'ops:1');assert.throws(()=>applyStorageMutation(c.processing,c.storage,trashMutation,{faultAt:'after_filesystem'}),{code:'fault_injected'});reconcileStorageMutations(c.processing,c.storage);assert.equal(c.processing.getModelOutput(version.id).status,'trashed');const restore=c.processing.beginRestoreMutation(trashMutation.trashId,'ops:1');applyStorageMutation(c.processing,c.storage,restore);assert.equal(c.processing.getModelOutput(version.id).status,'archived');const retrash=c.processing.beginOutputTrashMutation(version.id,'ops:1');applyStorageMutation(c.processing,c.storage,retrash);c.db.prepare("UPDATE storage_trash SET purge_after='2000-01-01T00:00:00.000Z' WHERE id=?").run(retrash.trashId);assert.equal(purgeExpiredTrash(c.processing,c.storage).find((row)=>row.trashId===retrash.trashId).status,'complete');assert.equal(c.processing.getModelOutput(version.id).byteSize,0);assert.equal(fs.existsSync(directory),false);assert.ok(c.processing.getTrash(retrash.trashId).permanentlyDeletedAt);});

test('public share unlock limiter keys contain only normalized token hashes',()=>{const raw='sensitive-token-value',key=shareUnlockRateKey(raw,'203.0.113.4');assert.doesNotMatch(key,/sensitive-token-value/);assert.match(key,/^share-unlock:[a-f0-9]{64}:203\.0\.113\.4$/);assert.equal(key,shareUnlockRateKey(raw.normalize('NFKC'),'203.0.113.4'));});

test('processing disk admission combines peak requirements that share a filesystem',(t)=>{const c=fixture(t),calls=[];c.storage.requireSpace=(rootKey,required)=>{calls.push({rootKey,required});return{available:required+1,total:required+1,reserve:0,required,ok:true};};const result=c.storage.requireProcessingHeadroom(1024);assert.equal(calls.length,1);assert.equal(calls[0].required,1280*1024*1024);assert.deepEqual(new Set(result.models.sharedWith),new Set(['datasets','cache','models']));assert.equal(result.datasets.required,0);assert.equal(result.cache.required,256*1024*1024);assert.equal(result.models.required,1024*1024*1024);});

test('processing admission reserves logical output headroom for already-active attempts',(t)=>{const c=fixture(t),project=c.processing.createProject({displayName:'Reservation'}),dataset=finalizedDataset(c,project),provider=c.processing.upsertProvider({type:'clusterodm',displayName:'Cluster',endpoint:'http://127.0.0.1:3000',enabled:true,admissionLimit:4}),firstTask=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'First'}),secondTask=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Second'}),first=c.processing.createAttempt({taskId:firstTask.id,providerId:provider.id,options:{}}),second=c.processing.createAttempt({taskId:secondTask.id,providerId:provider.id,options:{}});c.processing.transitionAttempt(first.id,'running',{progress:0.25});assert.deepEqual(c.processing.activeProcessingReservationBytes(second.id),[dataset.byteSize]);const available=1536*1024*1024;c.storage.requireSpace=(rootKey,required)=>{if(required>available)throw Object.assign(new Error('insufficient storage headroom'),{code:'insufficient_storage'});return{available,total:available,reserve:0,required,ok:true};};assert.doesNotThrow(()=>c.storage.requireProcessingHeadroom(dataset.byteSize,[]));assert.throws(()=>c.storage.requireProcessingHeadroom(dataset.byteSize,c.processing.activeProcessingReservationBytes(second.id)),{code:'insufficient_storage'});});

test('storage backpressure defers admission without consuming retry budget and recovers later',(t)=>{const c=fixture(t),project=c.processing.createProject({displayName:'Backpressure'}),dataset=finalizedDataset(c,project),provider=c.processing.upsertProvider({type:'clusterodm',displayName:'Cluster',endpoint:'http://127.0.0.1:3000',enabled:true,admissionLimit:4}),firstTask=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'First'}),secondTask=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Second'}),first=c.processing.createAttempt({taskId:firstTask.id,providerId:provider.id,options:{}}),second=c.processing.createAttempt({taskId:secondTask.id,providerId:provider.id,options:{}});c.db.prepare("UPDATE processing_jobs SET status='complete' WHERE attempt_id=?").run(first.id);c.processing.transitionAttempt(first.id,'running',{progress:0.25});const leased=c.processing.claimJob('worker-two');assert.equal(leased.attempt_id,second.id);assert.equal(c.processing.getAttempt(second.id).status,'admitted');assert.equal(c.processing.deferSubmitAdmission(leased.id,'worker-two',5000),true);let job=c.db.prepare('SELECT * FROM processing_jobs WHERE id=?').get(leased.id);assert.equal(job.status,'pending');assert.equal(job.attempt_count,0);assert.equal(c.processing.getAttempt(second.id).status,'pending');c.processing.transitionAttempt(first.id,'ready_for_review',{progress:1});c.db.prepare("UPDATE processing_jobs SET available_at='2000-01-01T00:00:00.000Z' WHERE id=?").run(leased.id);job=c.processing.claimJob('worker-after-space');assert.equal(job.id,leased.id);assert.equal(c.processing.getAttempt(second.id).status,'admitted');});
