'use strict';
const assert=require('node:assert/strict');const crypto=require('node:crypto');const express=require('express');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const test=require('node:test');const auth=require('../server/auth');const {openDatabase}=require('../server/database');const {ViewerRepository}=require('../server/repository');const {ProcessingRepository}=require('../server/processingRepository');const {StorageManager}=require('../server/storageManager');const {createProcessingApi}=require('../server/processingApi');const {processSubmit}=require('../server/processingWorker');

function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-max-images-')),config={datasetsMount:path.join(root,'datasets'),modelsMount:path.join(root,'models'),cacheMount:path.join(root,'cache'),trashMount:path.join(root,'trash'),storageReserveBytes:0,storageReservePercent:0};for(const location of Object.values(config).filter((value)=>typeof value==='string'&&value.startsWith(root)))fs.mkdirSync(location,{recursive:true});const database=openDatabase(path.join(root,'viewer.sqlite')),processing=new ProcessingRepository(database),repository=new ViewerRepository(database),storage=new StorageManager(config);storage.initialize();t.after(()=>{database.close();fs.rmSync(root,{recursive:true,force:true});});return{root,config,database,processing,repository,storage};}
function datasetWithTwoPhotos(c,project){const id=crypto.randomUUID(),dataset=c.processing.createDataset({id,projectId:project.id,displayName:'Two photos',storageMode:'managed',rootKey:'datasets',relativePath:id}),directory=path.join(c.config.datasetsMount,id),empty=crypto.createHash('sha256').digest('hex');fs.mkdirSync(directory,{recursive:true});for(const name of['one.jpg','two.jpg'])fs.writeFileSync(path.join(directory,name),'');c.processing.finalizeDataset(dataset.id,[{relativePath:'one.jpg',byteSize:0,sha256:empty},{relativePath:'two.jpg',byteSize:0,sha256:empty}],empty);return c.processing.getDataset(dataset.id,true);}

test('provider maxImages rejects oversized datasets at submission and before upstream initialization',async(t)=>{const c=fixture(t),project=c.processing.createProject({displayName:'Project'}),dataset=datasetWithTwoPhotos(c,project),provider=c.processing.upsertProvider({type:'nodeodm',displayName:'Small ODM',endpoint:'http://127.0.0.1:3000',enabled:true}),options=[{name:'pc-ept',type:'bool'},{name:'gltf',type:'bool'},{name:'3d-tiles',type:'bool'}];c.processing.updateProviderCapabilities(provider.id,{capabilities:{maxImages:1,options},fingerprint:'d'.repeat(64),health:'healthy'});const token='provider-image-limit-token-000000000000';c.processing.createAdminSession({tokenHash:auth.hashToken(token),subject:'ops:max-images',permissions:['viewer.processing.write'],displayUnits:'imperial',expiresAt:new Date(Date.now()+60000).toISOString()});const app=express();app.use(express.json({verify:(req,_res,buffer)=>{req.rawBody=Buffer.from(buffer);}}));app.use(createProcessingApi(c));const server=await new Promise((resolve)=>{const value=app.listen(0,'127.0.0.1',()=>resolve(value));});t.after(()=>new Promise((resolve)=>server.close(resolve)));const response=await fetch(`http://127.0.0.1:${server.address().port}/api/v1/task-submissions`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':'provider-max-images-api'},body:JSON.stringify({submissionId:crypto.randomUUID(),projectId:project.id,datasetId:dataset.id,taskDisplayName:'Too large',providerId:provider.id,options:{}})});assert.equal(response.status,409);assert.equal((await response.json()).code,'provider_image_limit_exceeded');
  const task=c.processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Direct task'}),attempt=c.processing.createAttempt({taskId:task.id,providerId:provider.id,options:{'pc-ept':true,gltf:true,'3d-tiles':true}}),job=c.processing.claimJob('max-image-worker');c.storage.requireProcessingHeadroom=()=>({});let initialized=false;await assert.rejects(processSubmit(job,{processing:c.processing,storage:c.storage,config:c.config,signal:new AbortController().signal,adapterFactory:()=>({initialize:async()=>{initialized=true;}})}),(error)=>error.code==='provider_image_limit_exceeded');assert.equal(initialized,false);assert.equal(c.processing.getAttempt(attempt.id).datasetId,dataset.id);
});
