'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const {buildRetainedManifest}=require('../server/retainedManifest');
const VALID_EPT=JSON.stringify({version:'1.1.0',bounds:[0,0,0,1,1,1],boundsConforming:[0,0,0,1,1,1],dataType:'laszip',hierarchyType:'json',points:1,span:128,schema:[{name:'X',type:'signed',size:4},{name:'Y',type:'signed',size:4},{name:'Z',type:'signed',size:4}]});

function put(root,relative,body='fixture'){const target=path.join(root,...relative.split('/'));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,body);return target;}
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-retained-manifest-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function completeTree(t){const root=fixture(t);put(root,'DJI_001.JPG','photo-one');put(root,'images/DJI 002.jpg','photo-two');put(root,'thumbnails/DJI_001.JPG','thumb');put(root,'assets/odm_report/shots.geojson',JSON.stringify({type:'FeatureCollection',features:[{type:'Feature',properties:{filename:'DJI_001.JPG'},geometry:{type:'Point',coordinates:[-90,44,200]}}]}));put(root,'assets/cameras.json','{}');put(root,'assets/odm_texturing/odm_textured_model_geo.glb','glb');put(root,'assets/odm_texturing/odm_textured_model_geo.obj','mtllib materials/main material.mtl\nv 0 0 0\n');put(root,'assets/odm_texturing/materials/main material.mtl','newmtl wall\nmap_Kd -s 1 1 1 ../textures/wall diffuse.jpg\nmap_Bump -bm 0.5 ../textures/wall normal.png\n');put(root,'assets/odm_texturing/textures/wall diffuse.jpg','diffuse');put(root,'assets/odm_texturing/textures/wall normal.png','normal');put(root,'assets/odm_georeferencing/proj.txt','+proj=utm +zone=16 +datum=WGS84 +units=m');put(root,'assets/odm_georeferencing/odm_georeferencing_model_geo.txt','WGS84 UTM 16N\n435932 4897211');put(root,'assets/odm_georeferencing/odm_georeferenced_model.summary.json','{"summary":{"bounds":{"minx":1,"miny":2,"minz":3,"maxx":4,"maxy":5,"maxz":6}}}');put(root,'assets/odm_report/stats.json','{}');put(root,'assets/entwine_pointcloud/ept.json',VALID_EPT);put(root,'assets/entwine_pointcloud/ept-data/0.bin','points');put(root,'assets/entwine_pointcloud/ept-hierarchy/0-0-0-0.json','{}');put(root,'assets/odm_georeferencing/odm_georeferenced_model.laz','source-cloud');put(root,'assets/odm_orthophoto/odm_orthophoto.tif','ortho');put(root,'assets/odm_dem/dsm.tif','dsm');put(root,'assets/odm_dem/dtm.tif','dtm');put(root,'assets/odm_report/report.pdf','report');put(root,'assets/3d_tiles/model/tileset.json','legacy');put(root,'assets/3d_tiles/model/root.b3dm','legacy-tile');put(root,'data/console_output.txt','log');put(root,'data/backup.json','control');put(root,'cache/preview.png','cache');return root;}

test('canonical retained manifest contains the full dependency closure and excludes disposable products',async(t)=>{const root=completeTree(t),first=await buildRetainedManifest(root),second=await buildRetainedManifest(root);assert.equal(first.manifestSha256,second.manifestSha256);assert.deepEqual(first.files,second.files);assert.match(first.manifestSha256,/^[a-f0-9]{64}$/);const byPath=new Map(first.files.map(file=>[file.sourceRelativePath,file]));for(const [relative,role] of[['DJI_001.JPG','source_photo'],['images/DJI 002.jpg','source_photo'],['assets/odm_report/shots.geojson','camera_positions'],['assets/cameras.json','camera_positions'],['assets/odm_texturing/odm_textured_model_geo.glb','mesh_glb'],['assets/odm_texturing/odm_textured_model_geo.obj','mesh_obj'],['assets/odm_texturing/materials/main material.mtl','mesh_mtl'],['assets/odm_texturing/textures/wall diffuse.jpg','mesh_texture'],['assets/odm_texturing/textures/wall normal.png','mesh_texture'],['assets/odm_georeferencing/proj.txt','georeference'],['assets/odm_report/stats.json','processing_metadata'],['assets/entwine_pointcloud/ept.json','ept'],['assets/entwine_pointcloud/ept-data/0.bin','ept'],['assets/odm_orthophoto/odm_orthophoto.tif','orthophoto'],['assets/odm_dem/dsm.tif','dsm'],['assets/odm_dem/dtm.tif','dtm'],['assets/odm_report/report.pdf','report']])assert.equal(byPath.get(relative)?.role,role,relative);for(const excluded of['thumbnails/DJI_001.JPG','assets/odm_georeferencing/odm_georeferenced_model.laz','assets/3d_tiles/model/tileset.json','assets/3d_tiles/model/root.b3dm','data/console_output.txt','data/backup.json','cache/preview.png'])assert.equal(byPath.has(excluded),false,excluded);assert.deepEqual(first.files.map(file=>file.relativePath),[...first.files.map(file=>file.relativePath)].sort());for(const file of first.files){assert.equal(file.relativePath,file.sourceRelativePath);assert.ok(Number.isSafeInteger(file.byteSize)&&file.byteSize>=0);assert.match(file.sha256,/^[a-f0-9]{64}$/);}});

test('retained manifest fails closed on a missing OBJ or MTL dependency',async(t)=>{const root=fixture(t);put(root,'odm_textured_model_geo.obj','mtllib model.mtl\n');put(root,'odm_textured_model_geo.glb','glb');put(root,'model.mtl','map_Kd missing texture.jpg\n');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='retained_dependency_missing');});

test('retained manifest rejects dependency case mismatch instead of guessing',async(t)=>{const root=fixture(t);put(root,'odm_textured_model_geo.obj','mtllib model.mtl\n');put(root,'odm_textured_model_geo.glb','glb');put(root,'model.mtl','map_Kd Texture.JPG\n');put(root,'texture.jpg','texture');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='retained_dependency_case_mismatch');});

test('retained manifest rejects dependencies outside the extracted root',async(t)=>{const root=fixture(t);put(root,'nested/odm_textured_model_geo.obj','mtllib ../../../outside.mtl\n');put(root,'nested/odm_textured_model_geo.glb','glb');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='retained_dependency_unsafe');});

test('retained manifest rejects ambiguous duplicate primary products',async(t)=>{const root=fixture(t);put(root,'one/odm_textured_model_geo.glb','one');put(root,'two/odm_textured_model_geo.glb','two');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='retained_product_ambiguous');});

test('retained manifest keeps LAS or LAZ only when no EPT closure exists',async(t)=>{const root=fixture(t);put(root,'odm_georeferenced_model.laz','cloud');const manifest=await buildRetainedManifest(root);assert.equal(manifest.files.length,1);assert.equal(manifest.files[0].role,'point_cloud_source');});

test('retained manifest rejects PLY as the only point-cloud source',async(t)=>{const root=fixture(t);put(root,'odm_georeferenced_model.ply','ply');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='unsupported_pointcloud_source');});

test('retained manifest rejects a file changed between inventory and hashing',async(t)=>{const root=fixture(t),target=put(root,'model.glb','old'),lstat=fs.lstatSync;let calls=0;fs.lstatSync=(candidate,...rest)=>{if(path.resolve(String(candidate))===path.resolve(target)&&++calls===1)fs.writeFileSync(target,'new-longer');return lstat(candidate,...rest);};try{await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='source_changed');}finally{fs.lstatSync=lstat;}assert.ok(calls>=1);});

test('retained manifest rejects dependency files changed after parsing',async(t)=>{const root=fixture(t),obj=put(root,'model.obj','mtllib one.mtl\n');put(root,'one.mtl','newmtl one\n');put(root,'two.mtl','newmtl two\n');const read=fs.readSync;let changed=false;fs.readSync=(fd,...rest)=>{const result=read(fd,...rest);let opened='';try{opened=fs.readlinkSync(`/proc/self/fd/${fd}`);}catch{}if(!changed&&path.resolve(opened)===path.resolve(obj)){changed=true;fs.writeFileSync(obj,'mtllib two.mtl\n');}return result;};try{await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='source_changed');}finally{fs.readSync=read;}assert.equal(changed,true);});

test('EPT closure retains only the EPT namespace when ept.json is near unrelated assets',async(t)=>{const root=fixture(t);put(root,'assets/ept.json',VALID_EPT);put(root,'assets/ept-data/0.bin','points');put(root,'assets/ept-hierarchy/0.json','{}');put(root,'assets/cache/preview.tmp','preview');put(root,'assets/data/backup.json','control');put(root,'assets/odm_georeferenced_model.laz','cloud');const manifest=await buildRetainedManifest(root),paths=manifest.files.map(file=>file.relativePath);assert.deepEqual(paths,['assets/ept-data/0.bin','assets/ept-hierarchy/0.json','assets/ept.json']);});

test('schema-incomplete EPT does not shadow a usable LAS or LAZ source',async(t)=>{const root=fixture(t);put(root,'ept.json','{"version":"1.1.0"}');put(root,'ept-data/0.bin','points');put(root,'ept-hierarchy/0.json','{}');put(root,'odm_georeferenced_model.laz','cloud');const manifest=await buildRetainedManifest(root);assert.deepEqual(manifest.files.map(file=>[file.relativePath,file.role]),[['odm_georeferenced_model.laz','point_cloud_source']]);});

test('a valid zero-point EPT does not require data or hierarchy payloads',async t=>{const root=fixture(t),empty=JSON.stringify({...JSON.parse(VALID_EPT),points:0});put(root,'entwine/ept.json',empty);const manifest=await buildRetainedManifest(root);assert.deepEqual(manifest.files.map(file=>[file.relativePath,file.role]),[['entwine/ept.json','ept']]);});
test('MTL option parsing cannot substitute a suffix-shaped decoy texture',async(t)=>{const root=fixture(t);put(root,'model.obj','mtllib model.mtl\n');put(root,'model.mtl','map_Bump -bm 0.5 missing texture.jpg\n');put(root,'0.5 missing texture.jpg','decoy');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='retained_dependency_missing');});

test('disposable product lookalikes are not retained as primary or metadata products',async(t)=>{const root=fixture(t);put(root,'cache/dsm-preview.tif','preview');put(root,'previews/odm_orthophoto_preview.tif','preview');put(root,'temporary/dtm_temp.tif','temporary');put(root,'cache/shots.geojson','{}');put(root,'data/images.json','{}');put(root,'temporary/odm_georeferencing/proj.txt','+proj=utm');put(root,'previews/odm_report/stats.json','{}');const manifest=await buildRetainedManifest(root);assert.deepEqual(manifest.files,[]);});

test('legacy streaming-tree mesh lookalikes are excluded from primary products',async t=>{const root=fixture(t);put(root,'assets/odm_texturing/odm_textured_model_geo.glb','authoritative');put(root,'assets/3d_tiles/model/model.glb','legacy');const manifest=await buildRetainedManifest(root);assert.deepEqual(manifest.files.map(file=>file.relativePath),['assets/odm_texturing/odm_textured_model_geo.glb']);});
test('retained manifest bounds georeference and processing metadata',async t=>{const root=fixture(t);put(root,'odm_georeferencing/proj.txt',Buffer.alloc(8*1024*1024+1));await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='invalid_retained_source');});
test('retained manifest rejects ambiguous camera-position sources',async t=>{const root=fixture(t);put(root,'DJI_001.JPG','photo');put(root,'shots.geojson','{"type":"FeatureCollection","features":[]}');put(root,'assets/odm_report/shots.geojson','{"type":"FeatureCollection","features":[]}');await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='retained_product_ambiguous');});
test('retained manifest rejects a nested directory replaced after lstat',async t=>{const root=fixture(t),nested=path.join(root,'a','b'),escaped=path.join(root,'a','escaped'),outside=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-retained-outside-')),lstat=fs.lstatSync;fs.mkdirSync(nested,{recursive:true});fs.writeFileSync(path.join(nested,'model.glb'),'inside');fs.writeFileSync(path.join(outside,'model.glb'),'outside');t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));let swapped=false;fs.lstatSync=(candidate,...args)=>{const result=lstat(candidate,...args);if(!swapped&&String(candidate).replaceAll('\\','/').endsWith('/b')){fs.renameSync(nested,escaped);fs.symlinkSync(outside,nested,'dir');swapped=true;}return result;};try{await assert.rejects(()=>buildRetainedManifest(root),(error)=>['source_changed','invalid_retained_source'].includes(error.code));}finally{fs.lstatSync=lstat;}assert.equal(swapped,true);});
test('retained manifest rejects symlinks and special source entries',async(t)=>{const root=fixture(t),outside=put(root,'outside.jpg','photo');fs.symlinkSync(outside,path.join(root,'linked.jpg'));await assert.rejects(()=>buildRetainedManifest(root),(error)=>error.code==='invalid_retained_source');});
