'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const {descriptorSource,extractZipDescriptor}=require('../server/safeZip');
const {makeZip,makeZip64Descriptor}=require('./helpers/zipFixture');

async function runExtraction(t,archiveBytes,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-')),archive=path.join(root,'source.zip'),destination=path.join(root,'expanded'),workId=options.workId||'test';fs.writeFileSync(archive,archiveBytes);const fd=fs.openSync(archive,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);t.after(()=>{try{fs.closeSync(fd);}catch{}fs.rmSync(root,{recursive:true,force:true});});const result=await extractZipDescriptor(fd,archiveBytes.length,destination,{maxEntries:100,maxBytes:1024*1024,workId,...options});fs.fstatSync(fd);return{root,archive,destination,fd,result,incomplete:`${destination}.${workId}.incomplete`};}

test('descriptor ZIP extraction validates CRC and keeps the caller descriptor open',async(t)=>{const zip=makeZip([{path:'nested/model.glb',data:'mesh'},{path:'nested/info.json',data:'{}',method:8,descriptor:true}]),done=await runExtraction(t,zip);assert.deepEqual(done.result,{entries:2,bytes:6});assert.equal(fs.readFileSync(path.join(done.destination,'nested','model.glb'),'utf8'),'mesh');});

test('descriptor ZIP extraction accepts small ZIP64 entries with 64-bit data descriptors',async(t)=>{const done=await runExtraction(t,makeZip64Descriptor('small.bin','a'),{workId:'zip64-small'});assert.equal(fs.readFileSync(path.join(done.destination,'small.bin'),'utf8'),'a');});

test('descriptor ZIP extraction rejects conflicting ZIP64 local sizes',async(t)=>{const bytes=makeZip64Descriptor('small.bin','a',{localSize:2}),root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-zip64-conflict-')),archive=path.join(root,'source.zip');fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,path.join(root,'out'),{workId:'zip64-conflict'}),/local and central headers disagree/);});

test('descriptor ZIP extraction rejects conflicting non-ZIP64 local descriptor fields',async(t)=>{const bytes=makeZip([{path:'small.bin',data:'a',descriptor:true,localCrc:1,localCompressedSize:2,localUncompressedSize:2}]),root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-descriptor-conflict-')),archive=path.join(root,'source.zip');fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,path.join(root,'out'),{workId:'descriptor-conflict'}),/local and central headers disagree/);});

test('descriptor range validation rejects unsafe offsets without leaking duplicate FDs',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-fd-')),file=path.join(root,'source.zip');fs.writeFileSync(file,'bytes');const fd=fs.openSync(file,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});const count=()=>fs.readdirSync('/proc/self/fd').length,before=count();assert.throws(()=>descriptorSource(fd,5).stream(Number.MAX_SAFE_INTEGER+1,1),(error)=>error.code==='invalid_archive');assert.equal(count(),before);});

test('descriptor ZIP extraction accepts a bounded central-directory comment',async(t)=>{const zip=makeZip([{path:'model.glb',data:'mesh'}],{comment:'c'.repeat(512)}),done=await runExtraction(t,zip,{workId:'comment'});assert.equal(fs.readFileSync(path.join(done.destination,'model.glb'),'utf8'),'mesh');});

for(const [name,entries] of[
  ['parent traversal',[{path:'../escape.txt',data:'x'}]],
  ['absolute path',[{path:'/escape.txt',data:'x'}]],
  ['backslash path',[{path:'dir\\escape.txt',data:'x'}]],
  ['case-colliding duplicate',[{path:'Photo.JPG',data:'a'},{path:'photo.jpg',data:'b'}]],
  ['symbolic link entry',[{path:'link',data:'target',mode:0o120777}]],
  ['special entry',[{path:'device',data:'x',mode:0o020666}]],
])test(`descriptor ZIP extraction rejects ${name}`,async(t)=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-reject-')),archive=path.join(root,'source.zip'),destination=path.join(root,'expanded'),bytes=makeZip(entries),fd=(fs.writeFileSync(archive,bytes),fs.openSync(archive,'r'));t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,destination,{workId:'reject'}),/archive/);assert.equal(fs.existsSync(destination),false);});

test('descriptor ZIP extraction rejects encrypted and unsupported methods',async(t)=>{for(const bytes of[makeZip([{path:'secret.txt',data:'x',flags:1}]),makeZip([{path:'odd.txt',data:'x',method:99}])]){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-method-')),archive=path.join(root,'source.zip'),destination=path.join(root,'expanded');fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,destination,{workId:'method'}),/archive/);fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});}});

test('descriptor ZIP extraction rejects local and central header disagreement',async(t)=>{const bytes=makeZip([{path:'central.txt',localPath:'local.txt',data:'x'}]),root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-header-')),archive=path.join(root,'source.zip'),destination=path.join(root,'expanded');fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,destination,{workId:'header'}),/header/);});

test('descriptor ZIP extraction rejects corrupt CRC and preserves incomplete staging',async(t)=>{const bytes=makeZip([{path:'corrupt.bin',data:'changed!',crcData:'expected'}]),root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-crc-')),archive=path.join(root,'source.zip'),destination=path.join(root,'expanded'),workId='crc';fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,destination,{workId}),/CRC/);assert.equal(fs.existsSync(`${destination}.${workId}.incomplete`),true);assert.equal(fs.existsSync(destination),false);});

test('descriptor ZIP extraction preflights the declared entry count before central allocation',async(t)=>{const bytes=Buffer.from(makeZip([{path:'one',data:'x'}])),eocd=bytes.length-22;bytes.writeUInt16LE(65535,eocd+8);bytes.writeUInt16LE(65535,eocd+10);const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-preflight-')),archive=path.join(root,'source.zip');fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,path.join(root,'out'),{workId:'preflight',maxEntries:100}),/entry limit/);});

test('descriptor ZIP extraction enforces entry and streamed expansion limits',async(t)=>{const bytes=makeZip([{path:'one',data:'12'},{path:'two',data:'34'}]),root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-limits-')),archive=path.join(root,'source.zip');fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');t.after(()=>{fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});});await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,path.join(root,'entries'),{workId:'entries',maxEntries:1,maxBytes:100}),/entry limit/);await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,path.join(root,'bytes'),{workId:'bytes',maxEntries:10,maxBytes:3}),/expansion limit/);});

test('descriptor ZIP extraction rejects cancellation, destination collision, truncation, and size mismatch',async(t)=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-safe-zip-final-')),destination=path.join(root,'expanded');fs.mkdirSync(destination);const valid=makeZip([{path:'one',data:'x'}]),mismatch=makeZip([{path:'one',data:'x',uncompressedSize:2}]);for(const [name,bytes,options,target] of[['cancelled',valid,{signal:AbortSignal.abort()},path.join(root,'cancelled')],['collision',valid,{},destination],['truncated',valid.subarray(0,valid.length-5),{},path.join(root,'truncated')],['mismatch',mismatch,{},path.join(root,'mismatch')]]){const archive=path.join(root,`${name}.zip`);fs.writeFileSync(archive,bytes);const fd=fs.openSync(archive,'r');await assert.rejects(()=>extractZipDescriptor(fd,bytes.length,target,{workId:name,...options}));fs.closeSync(fd);}fs.rmSync(root,{recursive:true,force:true});});
