'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),express=require('express');
const {openDatabase}=require('../server/database'),{ViewerRepository}=require('../server/repository'),auth=require('../server/auth'),shareApi=require('../server/shareApi'),assets=require('../server/assets');
const {resolveEphemeralAccess,localAccess}=require('../server/ephemeralMeasurementAccess');
test('share changes enforce password, views, cameras, downloads and queued calculation access across old signed credentials',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'share-policy-')),db=openDatabase(path.join(root,'viewer.sqlite')),repository=new ViewerRepository(db),body=Buffer.from('fixture bytes');
 const entries=[['glb','model.glb'],['ortho','ortho.tif'],['dsm','dsm.tif'],['shots','shots.geojson'],['report','report.pdf'],['allAssets','all.zip']];
 for(const [,file] of entries)fs.writeFileSync(path.join(root,file),body);
 const model=repository.upsertModelVersion({provider:'webodm',providerModelId:'fixture',providerVersionId:'v1',displayName:'Policy fixture',status:'ready',sourceLocator:{legacyAssetRoots:{webodm:root}},assets:entries.map(([kind,file])=>({kind,rootKey:'webodm',relativePath:file,byteSize:body.length,sha256:auth.hashToken(body),format:kind==='report'?'pdf':path.extname(file).slice(1),contentType:kind==='report'?'application/pdf':null,published:true}))});
 const raw=auth.newShareToken();let share=repository.createPublicShare({modelId:model.id,publicIdHash:raw.tokenHash,permissions:{view:true,measure:true,cameras:true,download:true}});
 share=repository.updatePublicShare(share.id,{allowedViews:['model','ortho','dsm']});
 const validator={allows:async()=>true};shareApi.setRepository(repository);shareApi.setSourceAuthorizationValidator(validator);assets.setRepository(repository);assets.setSourceAuthorizationValidator(validator);
 const app=express();app.use(express.json());app.use((req,_res,next)=>{req.cookies=Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(part=>part.trim().split('=')));next();});app.use(shareApi);app.use(assets);
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});const base=`http://127.0.0.1:${server.address().port}`;
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(root,{recursive:true,force:true});});
 const first=await fetch(`${base}/api/share/${raw.token}`);assert.equal(first.status,200);const cookie=first.headers.get('set-cookie').split(';')[0],config=await first.json();
 assert.equal((await fetch(base+config.assets.glb)).status,200);
 const capability=decodeURIComponent(config.assets.glb.split('/')[2]),access=await resolveEphemeralAccess(capability,repository,{validator});assert.ok(localAccess(access.authority,repository));
 let response=await fetch(`${base}/session-products/${capability}/${model.id}`),products=(await response.json()).products;
 assert.ok(products.find(item=>item.kind==='report'),'processing report remains explicitly downloadable');assert.equal(products.some(item=>item.kind==='allAssets'),false,'aggregate archives cannot bypass selected views');
 const orthoProduct=products.find(item=>item.kind==='ortho');const ticket=await(await fetch(base+orthoProduct.grantUrl,{method:'POST'})).json();assert.equal((await fetch(base+ticket.url)).status,200);
 share=repository.updatePublicShare(share.id,{passwordHash:await auth.hashPassword('new password'),permissions:{view:true,measure:true,cameras:false,download:true},allowedViews:['model'],invalidateAuthorization:true});
 assert.equal((await fetch(`${base}/api/share/${raw.token}`,{headers:{cookie}})).status,401,'old cookie cannot unlock newly protected link');
 assert.equal((await fetch(base+config.assets.glb)).status,403,'old asset tokens are invalidated');assert.equal((await fetch(base+ticket.url)).status,403,'existing download tickets are invalidated');
 assert.equal(localAccess(access.authority,repository),null,'queued work loses old authorization');await assert.rejects(resolveEphemeralAccess(capability,repository,{validator}));
 const unlocked=await fetch(`${base}/api/share/${raw.token}/unlock`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:'new password'})});assert.equal(unlocked.status,200);const fresh=await unlocked.json(),freshCookie=unlocked.headers.get('set-cookie').split(';')[0];
 assert.equal(fresh.assets.ortho,null);assert.equal(fresh.assets.dsm,null);assert.equal(fresh.assets.shots,null);assert.equal((await fetch(base+fresh.assets.glb)).status,200);
 const newCapability=decodeURIComponent(fresh.assets.glb.split('/')[2]);const forbidden=`/session-assets/${newCapability}/${model.id}/webodm/ortho.tif`;
 assert.equal((await fetch(base+forbidden)).status,403,'manually reconstructed hidden asset URL fails');
 assert.equal((await fetch(`${base}/assets/${model.id}/webodm/ortho.tif`,{headers:{cookie:freshCookie}})).status,403,'cookie asset route enforces the same view selection');
 assert.equal((await fetch(`${base}/session-products/${newCapability}/${model.id}/ortho/download-grants`,{method:'POST'})).status,403);
 assert.equal((await fetch(`${base}/session-products/${newCapability}/${model.id}/allAssets/download-grants`,{method:'POST'})).status,403);
 share=repository.updatePublicShare(share.id,{passwordHash:null,invalidateAuthorization:true});assert.equal((await fetch(`${base}/api/share/${raw.token}`)).status,200,'password removal transparently permits new public bootstrap');
 repository.updatePublicShare(share.id,{expiresAt:new Date(Date.now()-1).toISOString(),invalidateAuthorization:true});assert.equal((await fetch(`${base}/api/share/${raw.token}`)).status,410);
});
