'use strict';
const assert=require('node:assert/strict');const crypto=require('node:crypto');const express=require('express');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const test=require('node:test');const auth=require('../server/auth');const {openDatabase}=require('../server/database');const {ViewerRepository}=require('../server/repository');const shareApi=require('../server/shareApi');const assets=require('../server/assets');const {SourceAuthorizationValidator}=require('../server/sourceAuthorization');
const SECRET='source-authorization-test-secret-000000000000000';
function clientShare(overrides={}){return{id:'share-one',modelId:'model-one',shareClass:'client',sourceAuthorization:{type:'client_grant',id:'authorization-one',version:2,subject:'client-subject',expiresAt:null},...overrides};}
function reply(share,active=true,overrides={}){return new Response(JSON.stringify({active,authorizationId:share.sourceAuthorization.id,authorizationVersion:share.sourceAuthorization.version,subject:share.sourceAuthorization.subject,modelId:share.modelId,expiresAt:share.sourceAuthorization.expiresAt,...overrides}),{status:200,headers:{'content-type':'application/json','cache-control':'no-store'}});}

test('source authorization coalesces asset fanout, bounds leases and fails closed without affecting staff shares',async()=>{const share=clientShare(),staff={...share,shareClass:'staff',sourceAuthorization:null},calls=[];let active=true,failed=false;const validator=new SourceAuthorizationValidator({enabled:true,baseUrl:'https://incoming.ledgetopdroneservices.com',keyId:'viewer-v1',secret:SECRET,fetchImpl:async(url,init)=>{calls.push({url:String(url),init});if(failed)throw new Error('automation unavailable');await new Promise((resolve)=>setTimeout(resolve,5));return reply(share,active);}});assert.equal(await validator.allows(staff),true);assert.equal(calls.length,0,'staff shares bypass automation and remain outage independent');const burst=await Promise.all(Array.from({length:250},()=>validator.allows(share,1000)));assert.equal(burst.every(Boolean),true);assert.equal(calls.length,1,'nested/range fanout is promise-coalesced');assert.equal(calls[0].init.redirect,'error');assert.equal(await validator.allows(share,5999),true);assert.equal(calls.length,1);active=false;assert.equal(await validator.allows(share,6001),false,'revocation is observed after the five-second positive lease');assert.equal(calls.length,2);assert.equal(await validator.allows(share,6999),false);assert.equal(calls.length,2,'negative decisions are cached for no more than one second');failed=true;assert.equal(await validator.allows(share,7002),false);assert.equal(calls.length,3);const restarted=new SourceAuthorizationValidator({enabled:true,baseUrl:'https://incoming.ledgetopdroneservices.com',keyId:'viewer-v1',secret:SECRET,fetchImpl:async()=>{throw new Error('still down');}});assert.equal(await restarted.allows(share),false,'restart has no stale positive cache');const disabled=new SourceAuthorizationValidator({enabled:false,baseUrl:'https://incoming.ledgetopdroneservices.com',keyId:'viewer-v1',secret:SECRET,fetchImpl:async()=>reply(share)});assert.equal(await disabled.allows(share),false);assert.equal(await disabled.allows(staff),true);
});

test('source authorization rejects response mismatches, expiry and oversized cache growth',async()=>{const share=clientShare(),validator=new SourceAuthorizationValidator({enabled:true,baseUrl:'https://incoming.ledgetopdroneservices.com',keyId:'viewer-v1',secret:SECRET,fetchImpl:async()=>reply(share,true,{modelId:'different-model'})});assert.equal(await validator.allows(share),false);const expired=clientShare({id:'expired-share',sourceAuthorization:{...share.sourceAuthorization,expiresAt:'2020-01-01T00:00:00.000Z'}});assert.equal(await validator.allows(expired),false);for(let index=0;index<10000;index+=1)validator.cache.set(String(index),{allowed:false,until:Date.now()+10000});const freshShare=clientShare({id:'fresh-share'}),valid=new SourceAuthorizationValidator({enabled:true,baseUrl:'https://incoming.ledgetopdroneservices.com',keyId:'viewer-v1',secret:SECRET,fetchImpl:async()=>reply(freshShare)});valid.cache=validator.cache;assert.equal(await valid.allows(freshShare),true);assert.ok(valid.cache.size<=10000);
});

test('client authorization is enforced at share bootstrap, password unlock and every asset capability request',async(t)=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-source-route-')),database=openDatabase(path.join(root,'viewer.sqlite')),repository=new ViewerRepository(database),assetRoot=path.join(root,'assets');fs.mkdirSync(assetRoot,{recursive:true});fs.writeFileSync(path.join(assetRoot,'model.glb'),'mesh');const digest=crypto.createHash('sha256').update('mesh').digest('hex'),model=repository.upsertModelVersion({modelId:'model-one',versionId:'version-one',provider:'webodm',providerModelId:'provider-one',providerVersionId:'version-one',displayName:'Model',sourceLocator:{legacyAssetRoots:{webodm:assetRoot}},status:'ready',assets:[{kind:'glb',rootKey:'webodm',relativePath:'model.glb',byteSize:4,sha256:digest,published:true}]});const {token,tokenHash}=auth.newShareToken(),share=repository.createPublicShare({modelId:model.id,publicIdHash:tokenHash,passwordHash:await auth.hashPassword('correct horse'),permissions:{view:true},shareClass:'client',sourceAuthorization:{type:'client_grant',id:'auth-one',version:1,subject:'subject-one',expiresAt:null}});let allowed=false,calls=0,validator={allows:async(value)=>{calls+=1;assert.equal(value.id,share.id);return allowed;}};shareApi.setRepository(repository);shareApi.setSourceAuthorizationValidator(validator);assets.setRepository(repository);assets.setSourceAuthorizationValidator(validator);const app=express();app.use(express.json());app.use((req,_res,next)=>{req.cookies=Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map((part)=>part.trim().split('=')));next();});app.use(shareApi);app.use(assets);const server=await new Promise((resolve)=>{const value=app.listen(0,'127.0.0.1',()=>resolve(value));});t.after(async()=>{await new Promise((resolve)=>server.close(resolve));database.close();fs.rmSync(root,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`;assert.equal((await fetch(`${base}/api/share/${token}`)).status,410);allowed=true;assert.equal((await fetch(`${base}/api/share/${token}`)).status,401);allowed=false;assert.equal((await fetch(`${base}/api/share/${token}/unlock`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:'correct horse'})})).status,410);allowed=true;const unlock=await fetch(`${base}/api/share/${token}/unlock`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:'correct horse'})});assert.equal(unlock.status,200);const config=await unlock.json(),cookie=auth.sign({shareId:share.id,modelId:model.id},60000);allowed=false;assert.equal((await fetch(`${base}${config.assets.glb}`,{headers:{cookie:`ltds_share=${cookie}`}})).status,403);assert.ok(calls>=4);
});
