'use strict';
const assert=require('node:assert/strict');const crypto=require('node:crypto');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawn}=require('node:child_process');const {openDatabase}=require('../server/database');const {ProcessingRepository}=require('../server/processingRepository');const {ViewerRepository}=require('../server/repository');const test=require('node:test');
const root=path.resolve(__dirname,'..');
test('live WebODM API synchronization is absent while file migration and legacy delivery remain',()=>{const config=fs.readFileSync(path.join(root,'server','config.js'),'utf8'),index=fs.readFileSync(path.join(root,'server','index.js'),'utf8'),api=fs.readFileSync(path.join(root,'server','apiV1.js'),'utf8'),assets=fs.readFileSync(path.join(root,'server','assets.js'),'utf8');for(const source of[config,index,api])assert.doesNotMatch(source,/WEBODM_API_URL|WEBODM_USERNAME|WEBODM_PASSWORD|require\('\.\/sync'\)|api\/v1\/imports/);assert.equal(fs.existsSync(path.join(root,'server','sync.js')),false);assert.equal(fs.existsSync(path.join(root,'server','webodmClient.js')),false);assert.match(api,/toViewerConfig/);assert.match(assets,/legacyAssetRoots|catalogImport/);});

test('user-facing copy directs empty catalogs to file import instead of promising live sync',()=>{const main=fs.readFileSync(path.join(root,'main.js'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8');assert.match(main,/Import or manage a model from the secure Viewer workspace/);assert.doesNotMatch(main,/Waiting for the next WebODM sync|auto-sync/);assert.doesNotMatch(readme,/exact synced task|At sync time/);});

test('Compose always declares the worker and defaults this installation processing-on without changing viewer.env',()=>{const compose=fs.readFileSync(path.join(root,'docker-compose.yml'),'utf8');assert.match(compose,/PROCESSING_PLATFORM_ENABLED:\s*\$\{PROCESSING_PLATFORM_ENABLED:-true\}/);assert.match(compose,/viewer-worker:/);assert.doesNotMatch(compose,/profiles:\s*\[processing\]/);assert.match(compose,/source:\s*\/mnt\/Plugins\/App_Data\/Model-Viewer\/Storage[\s\S]*target:\s*\/app\/storage/);assert.doesNotMatch(compose,/viewer_storage|legacy-derivatives|DERIVATIVES_MOUNT/);});

test('the always-started worker remains healthy and idle when processing is explicitly disabled',async(t)=>{const data=fs.mkdtempSync(path.join(os.tmpdir(),'viewer-idle-worker-')),databasePath=path.join(data,'viewer.sqlite'),child=spawn(process.execPath,['server/worker.js'],{cwd:root,env:{...process.env,NODE_NO_WARNINGS:'1',NODE_ENV:'development',DATA_DIR:data,DATABASE_PATH:databasePath,PROCESSING_PLATFORM_ENABLED:'false',EMERGENCY_ADMIN_ENABLED:'false',SERVICE_AUTH_KEYS_JSON:'',SERVICE_AUTH_SECRET:'service-auth-secret-at-least-thirty-two-characters'},stdio:'ignore'});t.after(()=>{if(child.exitCode===null)child.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});});const deadline=Date.now()+5000;let heartbeat=null;while(Date.now()<deadline){if(child.exitCode!==null)assert.fail(`idle worker exited with ${child.exitCode}`);if(fs.existsSync(databasePath)){const db=openDatabase(databasePath);const row=db.prepare("SELECT value FROM app_state WHERE key='processing_worker_heartbeat'").get();db.close();if(row){heartbeat=JSON.parse(row.value);break;}}await new Promise((resolve)=>setTimeout(resolve,50));}assert.equal(heartbeat?.idle,true);assert.equal(heartbeat?.enabled,false);child.kill('SIGTERM');await new Promise((resolve)=>child.once('exit',resolve));});

test('the enabled worker logs bounded startup and heartbeat state',async(t)=>{const data=fs.mkdtempSync(path.join(os.tmpdir(),'viewer-worker-log-')),databasePath=path.join(data,'viewer.sqlite'),child=spawn(process.execPath,['server/worker.js'],{cwd:root,env:{...process.env,NODE_NO_WARNINGS:'1',NODE_ENV:'development',DATA_DIR:data,DATABASE_PATH:databasePath,PROCESSING_PLATFORM_ENABLED:'true',LOCAL_DERIVATIVES_ENABLED:'false',MESH_DERIVATIVES_ENABLED:'false',SESSION_SECRET:'session-secret-at-least-thirty-two-characters',EMERGENCY_ADMIN_ENABLED:'false',SERVICE_AUTH_KEYS_JSON:'',SERVICE_AUTH_SECRET:'service-auth-secret-at-least-thirty-two-characters',PROVIDER_CREDENTIALS_KEY:'0000000000000000000000000000000000000000000000000000000000000000'},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',(chunk)=>{stdout+=chunk;});child.stderr.on('data',(chunk)=>{stderr+=chunk;});t.after(()=>{if(child.exitCode===null)child.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});});const deadline=Date.now()+5000;while(Date.now()<deadline&&!stdout.includes('Processing worker started:')){if(child.exitCode!==null)assert.fail(`worker exited with ${child.exitCode}: ${stderr}`);await new Promise((resolve)=>setTimeout(resolve,50));}assert.match(stdout,/Processing worker started: heartbeat=recorded local-derivatives=disabled mesh-derivatives=disabled lanes=dataset-operation,processing,provider-health,derivative,event/);assert.doesNotMatch(stdout,new RegExp(data.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.equal(stderr,'');child.kill('SIGTERM');await new Promise((resolve)=>child.once('exit',resolve));});

test('the real worker leaves completed legacy LOD audits immutable',async(t)=>{
  const data=fs.mkdtempSync(path.join(os.tmpdir(),'viewer-lod-recovery-worker-')),databasePath=path.join(data,'viewer.sqlite'),db=openDatabase(databasePath),processing=new ProcessingRepository(db),repository=new ViewerRepository(db);
  const project=processing.createProject({displayName:'Recovery project'}),dataset=processing.createDataset({projectId:project.id,displayName:'Recovery source',storageMode:'managed',rootKey:'datasets',relativePath:crypto.randomUUID()});
  processing.finalizeDataset(dataset.id,[],'a'.repeat(64));
  const task=processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Recovery task'}),attempt=processing.createImportedAttempt({id:crypto.randomUUID(),taskId:task.id,datasetId:dataset.id,providerTaskId:'legacy',createdBy:'ops:test'}),model=repository.upsertModelVersion({provider:'ltds-processing',providerModelId:task.id,providerVersionId:attempt.id,displayName:task.displayName,status:'ready',assets:[{kind:'glb',rootKey:'datasets',relativePath:'legacy/model.glb',sha256:'b'.repeat(64),published:false}],makeActive:false}),versionId=db.prepare('SELECT id FROM model_versions WHERE model_id=?').get(model.id).id;
  processing.setAttemptResult(attempt.id,model.id,versionId);
  processing.registerModelOutput({versionId,modelId:model.id,taskId:task.id,attemptId:attempt.id,projectId:project.id,relativePath:`${task.id}/${attempt.id}`,status:'ready',byteSize:1,assetCount:1});
  processing.enqueueOptionalDerivatives(attempt.id,[{type:'lod_audit',request:{optional:true,tilesRootKey:'models',tilesRelativePath:'legacy/tiles'}}]);
  db.prepare("UPDATE derivative_jobs SET status='complete',result_json=?,completed_at=?,recovery_revision=0 WHERE attempt_id=?").run(JSON.stringify({verified:false,fallback:'glb'}),new Date().toISOString(),attempt.id);
  db.close();

  const child=spawn(process.execPath,['server/worker.js'],{cwd:root,env:{...process.env,NODE_NO_WARNINGS:'1',NODE_ENV:'development',DATA_DIR:data,DATABASE_PATH:databasePath,PROCESSING_PLATFORM_ENABLED:'true',LOCAL_DERIVATIVES_ENABLED:'false',MESH_DERIVATIVES_ENABLED:'false',SESSION_SECRET:'session-secret-at-least-thirty-two-characters',EMERGENCY_ADMIN_ENABLED:'false',SERVICE_AUTH_KEYS_JSON:'',SERVICE_AUTH_SECRET:'service-auth-secret-at-least-thirty-two-characters',PROVIDER_CREDENTIALS_KEY:'0000000000000000000000000000000000000000000000000000000000000000'},stdio:['ignore','pipe','pipe']});
  let stdout='',stderr='';child.stdout.on('data',(chunk)=>{stdout+=chunk;});child.stderr.on('data',(chunk)=>{stderr+=chunk;});
  t.after(()=>{if(child.exitCode===null)child.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});});
  const deadline=Date.now()+5000;
  while(Date.now()<deadline&&!stdout.includes('Processing worker started:')){if(child.exitCode!==null)assert.fail(`worker exited with ${child.exitCode}: ${stderr}`);await new Promise((resolve)=>setTimeout(resolve,50));}
  await new Promise((resolve)=>setTimeout(resolve,250));
  assert.doesNotMatch(stdout,/LOD reconciliation:/);
  assert.doesNotMatch(stdout,new RegExp(data.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  child.kill('SIGTERM');await new Promise((resolve)=>child.once('exit',resolve));
  const verified=openDatabase(databasePath),row=verified.prepare('SELECT status,recovery_revision FROM derivative_jobs WHERE attempt_id=?').get(attempt.id);
  assert.equal(row.status,'complete');
  assert.equal(row.recovery_revision,0);
  assert.equal(verified.prepare("SELECT COUNT(*) n FROM audit_events WHERE action='derivative.recovery_requeued'").get().n,0);
  verified.close();
});
