'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const {openDatabase}=require('../server/database');
const {ProcessingRepository}=require('../server/processingRepository');
const {StorageManager}=require('../server/storageManager');
const {openImportZipSource}=require('../server/importSourceSnapshot');
const {stageSource}=require('../server/webodmTaskImport');
const {processOneDatasetOperation}=require('../server/datasetOperationWorker');
const {ViewerRepository}=require('../server/repository');
const {makeZip}=require('./helpers/zipFixture');

const VALID_ZIP=Buffer.from('UEsDBBQAAAAAAG5SEV1oIC3YAwAAAAMAAAAoAAAAb2RtX3RleHR1cmluZy9vZG1fdGV4dHVyZWRfbW9kZWxfZ2VvLmdsYmdsYlBLAwQUAAAAAABuUhFdQ7+mowIAAAACAAAAGwAAAGVudHdpbmVfcG9pbnRjbG91ZC9lcHQuanNvbnt9UEsDBBQAAAAAAG5SEV1Dv6ajAgAAAAIAAAAbAAAAM2RfdGlsZXMvbW9kZWwvdGlsZXNldC5qc29ue31QSwECFAAUAAAAAABuUhFdaCAt2AMAAAADAAAAKAAAAAAAAAAAAAAAAAAAAAAAb2RtX3RleHR1cmluZy9vZG1fdGV4dHVyZWRfbW9kZWxfZ2VvLmdsYlBLAQIUABQAAAAAAG5SEV1Dv6ajAgAAAAIAAAAbAAAAAAAAAAAAAAAAAEkAAABlbnR3aW5lX3BvaW50Y2xvdWQvZXB0Lmpzb25QSwECFAAUAAAAAABuUhFdQ7+mowIAAAACAAAAGwAAAAAAAAAAAAAAAACEAAAAM2RfdGlsZXMvbW9kZWwvdGlsZXNldC5qc29uUEsFBgAAAAADAAMA6AAAAL8AAAAAAA==','base64');

function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-source-snapshot-')),config={datasetsMount:path.join(root,'datasets'),modelsMount:path.join(root,'models'),cacheMount:path.join(root,'cache'),trashMount:path.join(root,'trash'),datasetImportMount:path.join(root,'imports'),storageReserveBytes:0,storageReservePercent:0,uploadMaxFiles:1000};for(const location of Object.values(config).filter((value)=>typeof value==='string'&&value.startsWith(root)))fs.mkdirSync(location,{recursive:true});const db=openDatabase(path.join(root,'viewer.sqlite')),processing=new ProcessingRepository(db),repository=new ViewerRepository(db),storage=new StorageManager(config);storage.initialize();t.after(()=>{db.close();fs.rmSync(root,{recursive:true,force:true});});return{root,config,db,processing,repository,storage};}

test('an opened ZIP snapshot stays bound to its inode after same-path replacement',async(t)=>{const c=fixture(t),archive=path.join(c.config.datasetImportMount,'nested.zip');fs.writeFileSync(archive,VALID_ZIP);const opened=openImportZipSource(c.storage,'nested.zip');t.after(()=>opened.close());const snapshot=await opened.snapshot();assert.equal(snapshot.relativePath,'nested.zip');assert.equal(snapshot.byteSize,VALID_ZIP.length);assert.match(snapshot.sha256,/^[a-f0-9]{64}$/);for(const key of['device','inode','ctimeNs','mtimeNs'])assert.match(snapshot[key],/^\d+$/);fs.renameSync(archive,`${archive}.original`);fs.writeFileSync(archive,Buffer.alloc(VALID_ZIP.length,0x61));const descriptorBytes=Buffer.alloc(VALID_ZIP.length);fs.readSync(opened.fd,descriptorBytes,0,descriptorBytes.length,0);assert.equal(descriptorBytes.equals(VALID_ZIP),true,'opened descriptor remains bound to the original inode');await assert.rejects(()=>opened.hash(),(error)=>error.code==='source_changed');assert.notEqual(String(fs.statSync(archive,{bigint:true}).ino),snapshot.inode);});

test('ZIP snapshot rejects directories and symlinks before hashing',t=>{const c=fixture(t),directory=path.join(c.config.datasetImportMount,'folder.zip'),target=path.join(c.config.datasetImportMount,'target.zip'),link=path.join(c.config.datasetImportMount,'link.zip');fs.mkdirSync(directory);fs.writeFileSync(target,VALID_ZIP);fs.symlinkSync(target,link);assert.throws(()=>openImportZipSource(c.storage,'folder.zip'),(error)=>error.code==='invalid_import_source');assert.throws(()=>openImportZipSource(c.storage,'link.zip'),(error)=>error.code==='invalid_import_source');});

test('ZIP snapshot rejects a parent-directory symlink swap after path resolution',t=>{const c=fixture(t),parent=path.join(c.config.datasetImportMount,'parent'),outside=path.join(c.root,'outside');fs.mkdirSync(parent);fs.mkdirSync(outside);fs.writeFileSync(path.join(parent,'source.zip'),Buffer.from('inside'));fs.writeFileSync(path.join(outside,'source.zip'),Buffer.from('outside'));const resolve=c.storage.resolve.bind(c.storage);let swapped=false;c.storage.resolve=(...args)=>{const resolved=resolve(...args);if(!swapped&&args[0]==='dataset_import'){fs.renameSync(parent,`${parent}.original`);fs.symlinkSync(outside,parent);swapped=true;}return resolved;};assert.throws(()=>openImportZipSource(c.storage,'parent/source.zip'),(error)=>['invalid_import_source','source_changed'].includes(error.code));assert.equal(swapped,true);});

test('server-folder staging rejects a parent-directory symlink swap',async(t)=>{const c=fixture(t),parent=path.join(c.config.datasetImportMount,'parent'),inside=path.join(parent,'task'),outsideParent=path.join(c.root,'outside-parent'),outside=path.join(outsideParent,'task');fs.mkdirSync(inside,{recursive:true});fs.mkdirSync(outside,{recursive:true});fs.writeFileSync(path.join(inside,'odm_orthophoto.tif'),'inside');fs.writeFileSync(path.join(outside,'odm_orthophoto.tif'),'outside');const project=c.processing.createProject({displayName:'Folder race'});c.processing.createWebodmTaskImportOperation({request:{sourceRelativePath:'parent/task',projectId:project.id,taskDisplayName:'Folder race'},subject:'ops:one',sessionId:'session'});const operation=c.processing.claimDatasetOperation('folder-race-worker'),resolve=c.storage.resolve.bind(c.storage);let swapped=false;c.storage.resolve=(...args)=>{const result=resolve(...args);if(!swapped&&args[0]==='dataset_import'){fs.renameSync(parent,`${parent}.original`);fs.symlinkSync(outsideParent,parent);swapped=true;}return result;};await assert.rejects(()=>stageSource(operation,{processing:c.processing,storage:c.storage,config:c.config},new AbortController().signal,async()=>{}),(error)=>['invalid_import_source','source_changed'].includes(error.code));assert.equal(fs.readFileSync(path.join(outside,'odm_orthophoto.tif'),'utf8'),'outside');});

test('server-folder staging rejects a nested-directory symlink swap during traversal',async(t)=>{const c=fixture(t),source=path.join(c.config.datasetImportMount,'task'),nested=path.join(source,'nested'),outside=path.join(c.root,'outside-nested');fs.mkdirSync(nested,{recursive:true});fs.mkdirSync(outside);fs.writeFileSync(path.join(nested,'odm_orthophoto.tif'),'inside');fs.writeFileSync(path.join(outside,'odm_orthophoto.tif'),'outside');const project=c.processing.createProject({displayName:'Nested race'});c.processing.createWebodmTaskImportOperation({request:{sourceRelativePath:'task',projectId:project.id,taskDisplayName:'Nested race'},subject:'ops:one',sessionId:'session'});const operation=c.processing.claimDatasetOperation('nested-race-worker'),lstat=fs.lstatSync;let swapped=false;fs.lstatSync=(target,...args)=>{const stat=lstat(target,...args);if(!swapped&&String(target).endsWith('/nested')){fs.renameSync(nested,`${nested}.original`);fs.symlinkSync(outside,nested);swapped=true;}return stat;};try{await assert.rejects(()=>stageSource(operation,{processing:c.processing,storage:c.storage,config:c.config},new AbortController().signal,async()=>{}),(error)=>['invalid_asset_tree','source_changed','invalid_import_source'].includes(error.code));}finally{fs.lstatSync=lstat;}assert.equal(swapped,true);assert.equal(fs.readFileSync(path.join(outside,'odm_orthophoto.tif'),'utf8'),'outside');});

test('ZIP snapshot hashing yields to cancellation without closing the descriptor',async(t)=>{const c=fixture(t),archive=path.join(c.config.datasetImportMount,'large.zip');fs.writeFileSync(archive,Buffer.alloc(32*1024*1024,0x5a));const opened=openImportZipSource(c.storage,'large.zip'),controller=new AbortController();t.after(()=>opened.close());const hashing=opened.snapshot({signal:controller.signal});setImmediate(()=>controller.abort());await assert.rejects(hashing,(error)=>error.code==='lease_lost');fs.fstatSync(opened.fd);});

test('queued ZIP operations reject a directory replacement with the same name',async(t)=>{const c=fixture(t),source=path.join(c.config.datasetImportMount,'backup.zip');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'model.glb'),'mesh');const project=c.processing.createProject({displayName:'Type binding'});c.processing.createWebodmTaskImportOperation({request:{sourceRelativePath:'backup.zip',projectId:project.id,taskDisplayName:'Type binding'},subject:'ops:one',sessionId:'session'});const operation=c.processing.claimDatasetOperation('type-worker');await assert.rejects(()=>stageSource(operation,{processing:c.processing,storage:c.storage,config:c.config},null,async()=>{}),(error)=>error.code==='invalid_import_source');assert.equal(fs.readFileSync(path.join(source,'model.glb'),'utf8'),'mesh');});

test('operation source kind uses the validated endpoint kind rather than a filename suffix',t=>{const c=fixture(t),project=c.processing.createProject({displayName:'Kind'}),operation=c.processing.createWebodmTaskImportOperation({request:{sourceRelativePath:'backup.zip',sourceKind:'folder',projectId:project.id,taskDisplayName:'Kind'},subject:'ops:one',sessionId:'session'}),payload=JSON.parse(c.db.prepare('SELECT payload_json FROM dataset_operations WHERE id=?').get(operation.id).payload_json);assert.equal(payload.importSource.kind,'server_folder');});

test('API accepts only ZIPs on the backup endpoint and folders on the compatibility endpoint',()=>{const source=fs.readFileSync(path.join(__dirname,'..','server','processingApi.js'),'utf8'),start=source.indexOf('router.use(serverTaskImportPaths,(req,res,next)=>');assert.ok(start>0);const guard=source.slice(start,source.indexOf('router.post(serverTaskImportPaths',start));assert.match(guard,/req\.baseUrl\.endsWith\('\/webodm-task-imports'\)\?'zip':'folder'/);assert.match(guard,/validateImportSelection\(storage,.*\{expectedKind\}/);assert.match(guard,/req\.importSourceKind=expectedKind/);assert.match(source,/sourceKind:req\.importSourceKind/);const workspace=fs.readFileSync(path.join(__dirname,'..','workspace-projects.js'),'utf8');assert.match(workspace,/selection\.dataset\.sourceKind=button\.dataset\.selectKind/);assert.match(workspace,/form\.elements\.sourceRelativePath\.dataset\.sourceKind==='zip'.*webodm-task-imports.*server-task-imports/);});

test('unsupported ZIP contents fail without deleting the source or completed extraction staging',async(t)=>{const c=fixture(t),archive=path.join(c.config.datasetImportMount,'unsupported.zip'),bytes=makeZip([{path:'report.txt',data:'not viewable'}]);fs.writeFileSync(archive,bytes);const project=c.processing.createProject({displayName:'Unsupported'}),operation=c.processing.createWebodmTaskImportOperation({request:{sourceRelativePath:'unsupported.zip',projectId:project.id,taskDisplayName:'Unsupported'},subject:'ops:one',sessionId:'session'});await processOneDatasetOperation(c,'unsupported-worker');const failed=c.processing.getDatasetOperation(operation.id,'ops:one'),staging=path.join(c.config.cacheMount,'webodm-task-imports',operation.id,'extracted');assert.equal(failed.status,'failed');assert.equal(fs.readFileSync(archive).equals(bytes),true);assert.equal(fs.readFileSync(path.join(staging,'report.txt'),'utf8'),'not viewable');});

test('worker persists the ZIP snapshot before extraction and never reopens a replacement path',async(t)=>{const c=fixture(t),archive=path.join(c.config.datasetImportMount,'task.zip');fs.writeFileSync(archive,VALID_ZIP);const project=c.processing.createProject({displayName:'Snapshot'}),queued=c.processing.createWebodmTaskImportOperation({request:{sourceRelativePath:'task.zip',sourceKind:'zip',projectId:project.id,taskDisplayName:'Snapshot'},subject:'ops:one',sessionId:'session'}),operation=c.processing.claimDatasetOperation('snapshot-worker'),staging=path.join(c.config.cacheMount,'webodm-task-imports',queued.id,'extracted'),originalSet=c.processing.setWebodmImportSourceSnapshot?.bind(c.processing);let replaced=false;c.processing.setWebodmImportSourceSnapshot=(...args)=>{const stored=originalSet(...args);fs.renameSync(archive,`${archive}.original`);fs.writeFileSync(archive,Buffer.alloc(VALID_ZIP.length,0x62));replaced=true;return stored;};await assert.rejects(()=>stageSource(operation,{processing:c.processing,storage:c.storage,config:c.config},null,async()=>{}),(error)=>error.code==='source_changed');assert.equal(replaced,true);assert.equal(fs.readFileSync(path.join(staging,'odm_texturing','odm_textured_model_geo.glb'),'utf8'),'glb');const payload=JSON.parse(c.db.prepare('SELECT payload_json FROM dataset_operations WHERE id=?').get(queued.id).payload_json);assert.equal(payload.sourceSnapshot.relativePath,'task.zip');assert.equal(payload.sourceSnapshot.byteSize,VALID_ZIP.length);assert.match(payload.sourceSnapshot.sha256,/^[a-f0-9]{64}$/);c.processing.setWebodmImportSourceSnapshot=originalSet;await assert.rejects(()=>stageSource(operation,{processing:c.processing,storage:c.storage,config:c.config},null,async()=>{}),(error)=>error.code==='source_changed');assert.equal(fs.readFileSync(path.join(staging,'odm_texturing','odm_textured_model_geo.glb'),'utf8'),'glb','verified extraction staging survives source replacement');});
