'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawn}=require('node:child_process');const {openDatabase}=require('../server/database');const test=require('node:test');
const root=path.resolve(__dirname,'..');
test('live WebODM API synchronization is absent while file migration and legacy delivery remain',()=>{const config=fs.readFileSync(path.join(root,'server','config.js'),'utf8'),index=fs.readFileSync(path.join(root,'server','index.js'),'utf8'),api=fs.readFileSync(path.join(root,'server','apiV1.js'),'utf8'),assets=fs.readFileSync(path.join(root,'server','assets.js'),'utf8');for(const source of[config,index,api])assert.doesNotMatch(source,/WEBODM_API_URL|WEBODM_USERNAME|WEBODM_PASSWORD|require\('\.\/sync'\)|api\/v1\/imports/);assert.equal(fs.existsSync(path.join(root,'server','sync.js')),false);assert.equal(fs.existsSync(path.join(root,'server','webodmClient.js')),false);assert.match(api,/toViewerConfig/);assert.match(assets,/legacyAssetRoots|catalogImport/);});

test('user-facing copy directs empty catalogs to file import instead of promising live sync',()=>{const main=fs.readFileSync(path.join(root,'main.js'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8');assert.match(main,/Import or manage a model from the secure Viewer workspace/);assert.doesNotMatch(main,/Waiting for the next WebODM sync|auto-sync/);assert.doesNotMatch(readme,/exact synced task|At sync time/);});

test('Compose always declares the worker and defaults this installation processing-on without changing viewer.env',()=>{const compose=fs.readFileSync(path.join(root,'docker-compose.yml'),'utf8');assert.match(compose,/PROCESSING_PLATFORM_ENABLED:\s*\$\{PROCESSING_PLATFORM_ENABLED:-true\}/);assert.match(compose,/viewer-worker:/);assert.doesNotMatch(compose,/profiles:\s*\[processing\]/);assert.match(compose,/viewer_storage:\/app\/storage/);});

test('the always-started worker remains healthy and idle when processing is explicitly disabled',async(t)=>{const data=fs.mkdtempSync(path.join(os.tmpdir(),'viewer-idle-worker-')),databasePath=path.join(data,'viewer.sqlite'),child=spawn(process.execPath,['server/worker.js'],{cwd:root,env:{...process.env,NODE_ENV:'development',DATA_DIR:data,DATABASE_PATH:databasePath,PROCESSING_PLATFORM_ENABLED:'false',EMERGENCY_ADMIN_ENABLED:'false',SERVICE_AUTH_KEYS_JSON:'',SERVICE_AUTH_SECRET:'service-auth-secret-at-least-thirty-two-characters'},stdio:'ignore'});t.after(()=>{if(child.exitCode===null)child.kill('SIGTERM');fs.rmSync(data,{recursive:true,force:true});});const deadline=Date.now()+5000;let heartbeat=null;while(Date.now()<deadline){if(child.exitCode!==null)assert.fail(`idle worker exited with ${child.exitCode}`);if(fs.existsSync(databasePath)){const db=openDatabase(databasePath);const row=db.prepare("SELECT value FROM app_state WHERE key='processing_worker_heartbeat'").get();db.close();if(row){heartbeat=JSON.parse(row.value);break;}}await new Promise((resolve)=>setTimeout(resolve,50));}assert.equal(heartbeat?.idle,true);assert.equal(heartbeat?.enabled,false);child.kill('SIGTERM');await new Promise((resolve)=>child.once('exit',resolve));});
