'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const express=require('express');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const auth=require('../server/auth');
const {openDatabase}=require('../server/database');
const {ViewerRepository}=require('../server/repository');
const {ProcessingRepository}=require('../server/processingRepository');
const {createProcessingApi}=require('../server/processingApi');

test('admin bearer can create list and revoke a one-time staff link for a published output',async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ltds-workspace-share-')),db=openDatabase(path.join(root,'viewer.sqlite')),repository=new ViewerRepository(db),processing=new ProcessingRepository(db),token='workspace-share-token-000000000000000';
  const project=processing.createProject({displayName:'Share'}),dataset=processing.createDataset({projectId:project.id,displayName:'Dataset',storageMode:'managed',rootKey:'datasets',relativePath:crypto.randomUUID()});db.prepare("UPDATE datasets SET status='finalized',manifest_sha256=?,finalized_at=? WHERE id=?").run('a'.repeat(64),new Date().toISOString(),dataset.id);
  const task=processing.createTask({projectId:project.id,datasetId:dataset.id,displayName:'Published'}),provider=processing.upsertProvider({type:'nodeodm',displayName:'Node',endpoint:'http://127.0.0.1:3000',enabled:true}),attempt=processing.createAttempt({taskId:task.id,providerId:provider.id,options:{}}),model=repository.upsertModelVersion({provider:'test',providerModelId:task.id,providerVersionId:attempt.id,displayName:'Published',status:'ready',assets:[{kind:'glb',rootKey:'models',relativePath:'model.glb',sha256:'b'.repeat(64),published:true}]}),version=db.prepare('SELECT id FROM model_versions WHERE model_id=?').get(model.id).id;
  processing.registerModelOutput({versionId:version,modelId:model.id,taskId:task.id,attemptId:attempt.id,projectId:project.id,relativePath:'output',byteSize:1,assetCount:1});db.prepare("UPDATE model_outputs SET status='published' WHERE id=?").run(version);
  processing.createAdminSession({tokenHash:auth.hashToken(token),subject:'ops:share',permissions:['viewer.processing.publish','viewer.shares.read','viewer.shares.create','viewer.shares.revoke'],displayUnits:'imperial',expiresAt:new Date(Date.now()+60000).toISOString()});
  const app=express();app.use(express.json({verify:(req,_res,buffer)=>{req.rawBody=Buffer.from(buffer)}}));app.use(createProcessingApi({repository,processing,storage:{}}));const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s))});t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(root,{recursive:true,force:true})});
  const base=`http://127.0.0.1:${server.address().port}`,headers={authorization:`Bearer ${token}`,'content-type':'application/json'},body=JSON.stringify({label:'Review link',password:'password123',permissions:{view:true,measure:true,cameras:false,download:false}});db.exec("CREATE TRIGGER reject_workspace_share_audit BEFORE INSERT ON audit_events WHEN NEW.action='share.created' BEGIN SELECT RAISE(ABORT,'injected share audit failure'); END");let response=await fetch(`${base}/api/v1/processing/outputs/${version}/shares`,{method:'POST',headers:{...headers,'idempotency-key':'workspace-share-audit-failure'},body});assert.equal(response.status,500);assert.equal(db.prepare('SELECT COUNT(*) n FROM public_shares').get().n,0);db.exec('DROP TRIGGER reject_workspace_share_audit');const clientToken=auth.newShareToken();const clientShare=repository.createPublicShare({modelId:model.id,publicIdHash:clientToken.tokenHash,permissions:{view:true},shareClass:'client',sourceAuthorization:{type:'client_grant',id:'client-auth',version:1,subject:'client:one',expiresAt:null}});response=await fetch(`${base}/api/v1/processing/outputs/${version}/shares`,{method:'POST',headers:{...headers,'idempotency-key':'workspace-share-create'},body});assert.equal(response.status,201);const created=await response.json();assert.match(created.viewUrl,/\/view\/[A-Za-z0-9_-]+$/);assert.equal(created.share.hasPassword,true);response=await fetch(`${base}/api/v1/processing/outputs/${version}/shares`,{headers});assert.equal(response.status,200);const listed=(await response.json()).shares;assert.equal(listed.length,1);assert.equal(listed[0].id,created.share.id);response=await fetch(`${base}/api/v1/processing/shares/${clientShare.id}`,{method:'DELETE',headers:{...headers,'idempotency-key':'workspace-client-share-revoke'},body:'{}'});assert.equal(response.status,404);assert.equal(repository.getPublicShare(clientShare.id).revokedAt,null);response=await fetch(`${base}/api/v1/processing/shares/${created.share.id}`,{method:'DELETE',headers:{...headers,'idempotency-key':'workspace-share-revoke'},body:'{}'});assert.equal(response.status,200);assert.ok((await response.json()).share.revokedAt);
});
