import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {existsSync,mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {acquireBrowserHarnessLock} from './browser-lock.mjs';
import {createServer as createViteServer} from 'vite';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),delay=ms=>new Promise(r=>setTimeout(r,ms));
class Cdp {
  constructor(socket){this.socket=socket;this.id=0;this.pending=new Map();this.errors=[];socket.addEventListener('message',event=>{const value=JSON.parse(event.data),p=this.pending.get(value.id);if(value.method==='Runtime.exceptionThrown')this.errors.push(value.params.exceptionDetails);if(p){this.pending.delete(value.id);clearTimeout(p.timer);value.error?p.reject(new Error(value.error.message)):p.resolve(value.result);}});}
  static async connect(url){const socket=new WebSocket(url);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});return new Cdp(socket);}
  command(method,params={}){const id=++this.id;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`CDP timeout ${method}`)),12000);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}));});}
  async eval(expression){const r=await this.command('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;}
  close(){this.socket.close();for(const p of this.pending.values())clearTimeout(p.timer);}
}
async function until(fn){const end=Date.now()+10000;while(Date.now()<end){if(await fn())return;await delay(30);}throw new Error('Fixture timeout');}
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/workspace.css"><link rel="stylesheet" href="/workspace-management.css"><dialog class="workspace-modal" open><header class="modal-heading"><h2>New task</h2></header><div id="host"></div></dialog><script type="module">
import {mountNewTask} from '/workspace-new-task.mjs';
const calls=[];let mode='pc',datasetStatus='draft',submitCount=0,complete=null,handle,releaseRead;
function jpeg(){const data=new Uint8Array(174),v=new DataView(data.buffer),base=12;data.set([255,216,255,225,0,168,69,120,105,102,0,0]);data.set([73,73],base);const u16=(o,n)=>v.setUint16(base+o,n,true),u32=(o,n)=>v.setUint32(base+o,n,true);u16(2,42);u32(4,8);u16(8,1);u16(10,0x8825);u16(12,4);u32(14,1);u32(18,26);u16(26,6);[[1,2,2,'N'],[2,5,3,104],[3,2,2,'W'],[4,5,3,128],[16,2,2,'T'],[17,5,1,152]].forEach(([tag,type,count,value],i)=>{const at=28+i*12;u16(at,tag);u16(at+2,type);u32(at+4,count);if(type===2)data[base+at+8]=value.charCodeAt(0);else u32(at+8,value);});[45,30,0,90,15,0,123].forEach((value,i)=>{u32(104+i*8,value);u32(108+i*8,1);});data.set([255,217],172);return data;}
const provider={id:'node',displayName:'Test node',type:'nodeodm',enabled:true,capabilityFingerprint:'fp',lastHealth:'healthy',lastHealthAt:new Date().toISOString(),capabilities:{options:['pc-ept','gltf','3d-tiles'].map(name=>({name}))}};
const api=async(url,opts={})=>{if(opts.signal?.aborted)throw new DOMException('Cancelled','AbortError');calls.push({url,body:opts.body,headers:opts.headers});
 if(url.startsWith('/api/v1/processing/providers'))return{providers:[provider]};
 if(url.startsWith('/api/v1/dataset-imports/browse'))return{path:'raw',parentPath:'',entries:[{name:'flight',relativePath:'raw/flight',kind:'folder'}],nextOffset:null};
 if(url==='/api/v1/dataset-imports/photo-preview')return{points:[{latitude:45.5,longitude:-90.25,name:'Server photo'}],missingGpsCount:0,unscannedCount:0};
 if(url==='/api/v1/dataset-imports/copy'){datasetStatus='finalizing';return{dataset:{id:'dataset'},operation:{id:'copy',status:'queued'}};}
 if(url==='/api/v1/datasets')return{dataset:{id:'dataset'}};
 if(url.endsWith('/uploads'))return{uploadToken:'scoped',upload:{id:'upload',datasetId:'dataset',status:'open',chunkSize:2,files:opts.body.files.map(file=>({...file,chunkCount:Math.ceil(file.byteSize/2),missingChunks:Array.from({length:Math.ceil(file.byteSize/2)},(_,i)=>i)}))}};
 if(url.endsWith('/finalize')){datasetStatus='finalizing';return{operation:{id:'assemble',status:'queued'}};}
 if(url.startsWith('/api/v1/operations/')){datasetStatus=mode==='failed'?'draft':'finalized';return{operation:{id:'operation',status:mode==='failed'?'failed':'succeeded',errorMessage:'Copy validation failed'}};}
 if(url==='/api/v1/datasets/dataset')return{dataset:{id:'dataset',projectId:'project',status:datasetStatus}};
 if(url==='/api/v1/task-submissions'){submitCount++;if(mode==='pc'&&submitCount===1)throw new Error('Temporary submission failure');return{task:{id:'task'}};}
 throw new Error('Unexpected '+url);
};
window.fetch=async(url,options)=>{calls.push({url,chunk:true,bytes:options.body.byteLength});return new Response('{}',{status:201});};
window.fixture={calls,mount(next='pc'){mode=next;datasetStatus='draft';submitCount=0;complete=null;calls.length=0;handle?.dispose();document.querySelector('dialog')?.remove();const dialog=document.createElement('dialog');dialog.className='workspace-modal';dialog.innerHTML='<header class="modal-heading"><h2>New task</h2></header><div id="host"></div>';document.body.append(dialog);dialog.showModal();handle=mountNewTask({container:document.querySelector('#host'),dialog,project:{id:'project',displayName:'Farm'},providers:[],presets:[{id:'preset',displayName:'Good preset',enabled:true,providerType:'nodeodm',capabilityFingerprint:'fp'},{id:'wrong',displayName:'Wrong preset',enabled:true,providerType:'nodeodm',capabilityFingerprint:'other'}],api,token:()=> 'staff',onComplete:r=>complete=r});},select(gps=false,slow=false){const dt=new DataTransfer(),file=new File([gps?jpeg():'abcdef'],'photo.jpg',{type:'image/jpeg'});if(slow)file.slice=()=>({arrayBuffer:()=>new Promise(resolve=>releaseRead=()=>resolve(jpeg().buffer))});dt.items.add(file);const input=document.querySelector('[data-files]');input.files=dt.files;input.dispatchEvent(new Event('change'));},release(){releaseRead?.();},reading:()=>!!releaseRead,submit(){document.querySelector('form').requestSubmit();},done:()=>complete,close(){document.querySelector('dialog').close();}};
fixture.mount();document.body.dataset.ready='true';
</script>`;

test('New task uses real form controls with isolated upload/copy APIs, retry and cancellation',{timeout:60000},async t=>{
  const executable=[process.env.CHROME_PATH,process.env.EDGE_PATH,'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe','/usr/bin/chromium'].filter(Boolean).find(existsSync);if(!executable)return t.skip('Chromium-family browser required');
  const unlock=await acquireBrowserHarnessLock({root});let server,browser,client,temp,vite;
  try{
    temp=mkdtempSync(path.join(tmpdir(),'ltds-new-task-test-'));vite=await createViteServer({root,configFile:false,server:{middlewareMode:true,hmr:false},appType:'custom',logLevel:'error'});server=createServer((req,res)=>{const pathname=new URL(req.url,'http://fixture').pathname;if(pathname==='/'){res.setHeader('Content-Type','text/html');return res.end(html);}vite.middlewares(req,res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
    browser=spawn(executable,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--no-sandbox','--remote-debugging-port=0',`--user-data-dir=${temp}`,'about:blank'],{windowsHide:true,stdio:'ignore'});const active=path.join(temp,'DevToolsActivePort');await until(()=>existsSync(active));const port=readFileSync(active,'utf8').split(/\r?\n/)[0],tabs=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();client=await Cdp.connect(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);await client.command('Page.enable');await client.command('Page.navigate',{url:`http://127.0.0.1:${server.address().port}/`});await until(()=>client.eval("document.body?.dataset.ready==='true'"));
    await client.command('Runtime.enable');
    await t.test('fresh node refresh, compatible preset, PC upload and succeeded finalization; failed submit retry never reuploads',async()=>{
      await until(()=>client.eval("document.querySelector('[name=providerId]').value==='node'"));assert.equal(await client.eval("!!document.querySelector('[name=presetId] option[value=wrong]')"),false);await client.eval("document.querySelector('[name=presetId]').value='preset';fixture.select();fixture.submit()");await until(()=>client.eval("document.querySelector('[data-status]').textContent.includes('Temporary submission failure')"));await client.eval('fixture.submit()');await until(()=>client.eval('!!fixture.done()'));
      const calls=await client.eval('fixture.calls'),submit=calls.filter(x=>x.url==='/api/v1/task-submissions');assert.equal(calls.filter(x=>x.url.endsWith('/uploads')).length,1);assert.equal(calls.filter(x=>x.url.endsWith('/finalize')).length,1);assert.equal(calls.filter(x=>x.chunk).length,3);assert.equal(submit.length,2);assert.equal(submit[0].body.submissionId,submit[1].body.submissionId);assert.equal(submit[0].headers['Idempotency-Key'],submit[1].headers['Idempotency-Key']);assert.equal(submit[1].body.presetId,'preset');
    });
    await t.test('server folder selection copies recursively and waits for succeeded before submit',async()=>{
      // Native dialog close is queued; let the previous dialog's event settle
      // before mounting another controller on this deliberately reused fixture.
      await delay(80);
      await client.eval("fixture.mount('server');document.querySelector('[data-source=server]').click()");await until(()=>client.eval("!!document.querySelector('[data-pick]')"));await client.eval("document.querySelector('[data-pick]').click();fixture.submit()");await until(()=>client.eval('!!fixture.done()'));const calls=await client.eval('fixture.calls');assert.deepEqual(calls.find(x=>x.url.endsWith('/copy')).body.paths,['raw/flight']);assert.ok(calls.findIndex(x=>x.url.startsWith('/api/v1/operations/'))<calls.findIndex(x=>x.url==='/api/v1/task-submissions'));assert.equal(calls.filter(x=>x.chunk).length,0);
    });
    await t.test('closing after accepted copy stops observation and never submits a processing job',async()=>{
      await delay(80);
      await client.eval("fixture.mount('server');document.querySelector('[data-source=server]').click()");await until(()=>client.eval("!!document.querySelector('[data-pick]')"));await client.eval("document.querySelector('[data-pick]').click();fixture.submit()");await until(()=>client.eval("fixture.calls.some(x=>x.url.endsWith('/copy'))"));await client.eval('fixture.close()');await delay(1700);assert.equal(await client.eval("fixture.calls.some(x=>x.url==='/api/v1/task-submissions')"),false);
    });
    await t.test('failed source operation stays failed without task submission or automatic duplicate copy',async()=>{
      await client.eval("fixture.mount('failed');document.querySelector('[data-source=server]').click()");await until(()=>client.eval("!!document.querySelector('[data-pick]')"));await client.eval("document.querySelector('[data-pick]').click();fixture.submit()");await until(()=>client.eval("document.querySelector('[data-status]').textContent.includes('Copy validation failed')"));await client.eval('fixture.submit()');await delay(100);assert.equal(await client.eval("fixture.calls.filter(x=>x.url==='/api/v1/dataset-imports/copy').length"),1);assert.equal(await client.eval("fixture.calls.some(x=>x.url==='/api/v1/task-submissions')"),false);
    });
    await t.test('GPS preview uses real Leaflet, fits desktop/mobile and retires stale local scans on reselect/source change/close',async()=>{
      await client.eval("fixture.mount('server');fixture.select(true);document.querySelector('[data-preview-photos]').click()");await until(()=>client.eval("/1 photos? located/.test(document.querySelector('[data-photo-map]').textContent)"));assert.equal(await client.eval("!!document.querySelector('[data-photo-map] .leaflet-container canvas')"),true);
      for(const [width,height,name] of [[1200,1050,'desktop'],[390,844,'mobile']]){await client.command('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await delay(100);assert.equal(await client.eval('document.documentElement.scrollWidth<=innerWidth'),true);assert.equal(await client.eval("document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth+1"),true);if(process.env.LTDS_NEW_TASK_SCREENSHOTS==='1'){const shot=await client.command('Page.captureScreenshot',{format:'png'}),dir=path.join(root,'data','qa');mkdirSync(dir,{recursive:true});writeFileSync(path.join(dir,`new-task-gps-${name}.png`),Buffer.from(shot.data,'base64'));}}
      await client.eval("fixture.select(true,true);document.querySelector('[data-preview-photos]').click()");await until(()=>client.eval('fixture.reading()'));await client.eval("fixture.select(false);fixture.release()");await delay(80);assert.equal(await client.eval("document.querySelector('[data-photo-map]').hidden"),true);assert.equal(await client.eval("document.querySelector('[data-preview-photos]').disabled"),false);assert.equal(await client.eval("document.querySelector('[data-photo-map]').children.length"),0);
      await client.eval("document.querySelector('[data-preview-photos]').click()");await until(()=>client.eval("document.querySelector('[data-photo-map]').textContent.includes('0 photos located')"));await client.eval("document.querySelector('[data-source=server]').click()");assert.equal(await client.eval("document.querySelector('[data-photo-map]').hidden"),true);await until(()=>client.eval("!!document.querySelector('[data-pick]')"));await client.eval("document.querySelector('[data-pick]').click();document.querySelector('[data-preview-photos]').click()");await until(()=>client.eval("/1 photos? located/.test(document.querySelector('[data-photo-map]').textContent)"));await client.eval('fixture.close()');await delay(60);assert.equal(await client.eval("document.querySelector('[data-photo-map]').children.length"),0);
    });
    await t.test('More project actions escape the selected card clip and remain hittable',async()=>{
      await client.command('Emulation.setDeviceMetricsOverride',{width:1200,height:800,deviceScaleFactor:1,mobile:false});await client.eval("document.querySelector('dialog').open=false;const card=document.createElement('div');card.className='project-row selected';card.style.cssText='position:absolute;top:20px;left:20px;width:500px;height:70px;padding:10px';card.innerHTML='<details class=project-more-actions open style=width:44px;margin-left:auto><summary>…</summary><div class=project-more-menu><button>Import</button><button>Rename</button><button>Delete project</button></div></details>';document.body.append(card)");assert.equal(await client.eval("getComputedStyle(document.querySelector('.project-row')).overflow"),'visible');assert.equal(await client.eval("(()=>{const b=document.querySelector('.project-more-menu button:last-child'),r=b.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===b;})()"),true);
    });
    await delay(80);assert.deepEqual(client.errors,[],'no late renderer errors after preview removal');
  }finally{client?.close();if(browser){const exit=new Promise(r=>browser.once('exit',r));browser.kill();await Promise.race([exit,delay(2500)]);}if(server){server.closeAllConnections?.();await new Promise(r=>server.close(r));}await vite?.close();unlock();if(temp){assert.ok(path.resolve(temp).startsWith(path.resolve(tmpdir(),'ltds-new-task-test-')));try{rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100});}catch(error){if(process.platform!=='win32'||!['EBUSY','EPERM','EACCES','ENOTEMPTY'].includes(error.code))throw error;}}}
});
