'use strict';

const { applyStorageMutation } = require('./storageLifecycle');

function trashDataset(processing,storage,id,actor){const existing=processing.activeTrashForEntity('dataset',id);if(existing)return existing;const dataset=processing.getDataset(id);if(!dataset||dataset.status==='trashed')return null;if(dataset.storageMode==='external_reference')return processing.trashDataset(id,{trashRelative:'',actor});const mutation=processing.beginTrashMutation(id,actor);if(!mutation)return null;applyStorageMutation(processing,storage,mutation);return processing.getTrash(mutation.trashId);}
function trashOutput(processing,storage,id,actor){const existing=processing.activeTrashForEntity('output',id);if(existing)return existing;let output=processing.getModelOutput(id);if(!output||output.status==='trashed')return null;if(['ready','published','failed'].includes(output.status))output=processing.archiveModelOutput(id,actor);if(!output||output.status!=='archived')return null;if(output.storageMode!=='managed')return processing.trashMetadataOutput(id,actor);const mutation=processing.beginOutputTrashMutation(id,actor);if(!mutation)return null;applyStorageMutation(processing,storage,mutation);return processing.getTrash(mutation.trashId);}
function addMember(processing,container,item){if(!item||!processing.addContainerTrashMember(container.id,item.id))throw Object.assign(new Error('container member could not be moved to trash'),{code:'lifecycle_conflict'});}
function trashTaskTree(processing,storage,taskId,actor,container=null){const taskTrash=processing.trashTask(taskId,actor);if(!taskTrash)throw Object.assign(new Error('task has active processing work'),{code:'task_not_trashable'});const root=container||taskTrash;if(container)addMember(processing,container,taskTrash);const owned=processing.taskOwnedEntities(taskId);for(const outputId of owned.outputs)addMember(processing,root,trashOutput(processing,storage,outputId,actor));for(const datasetId of owned.datasets)addMember(processing,root,trashDataset(processing,storage,datasetId,actor));processing.refreshContainerTrashBytes(root.id);return root;}
function trashProjectTree(processing,storage,projectId,actor){const root=processing.trashProject(projectId,actor);if(!root)throw Object.assign(new Error('project has active processing work'),{code:'project_not_trashable'});const owned=processing.projectOwnedEntities(projectId);for(const taskId of owned.tasks)trashTaskTree(processing,storage,taskId,actor,root);for(const outputId of owned.outputs){const item=trashOutput(processing,storage,outputId,actor);if(item)addMember(processing,root,item);}for(const datasetId of owned.datasets){const item=trashDataset(processing,storage,datasetId,actor);if(item)addMember(processing,root,item);}return processing.refreshContainerTrashBytes(root.id);}
function restoreItem(processing,storage,item,actor){if(!item||item.permanentlyDeletedAt)return true;if(['project','task'].includes(item.entityType))return Boolean(processing.restoreMetadataEntity(item.id,actor));if(item.entityType==='dataset'){const dataset=processing.getDataset(item.entityId);if(dataset?.storageMode==='external_reference')return Boolean(processing.restoreTrash(item.id,actor));const mutation=processing.beginRestoreMutation(item.id,actor);if(!mutation)return false;applyStorageMutation(processing,storage,mutation);return true;}if(item.entityType==='output'){const output=processing.getModelOutput(item.entityId);if(output?.storageMode!=='managed')return Boolean(processing.restoreMetadataOutput(item.id,actor));const mutation=processing.beginRestoreMutation(item.id,actor);if(!mutation)return false;applyStorageMutation(processing,storage,mutation);return true;}return false;}
function restoreContainerTrash(processing,storage,containerId,actor){const root=processing.getTrash(containerId);if(!root||root.permanentlyDeletedAt||!['project','task'].includes(root.entityType))return null;const members=processing.listContainerTrashMembers(root.id),data=members.filter(item=>['dataset','output'].includes(item.entityType)),tasks=members.filter(item=>item.entityType==='task');for(const item of data)if(!restoreItem(processing,storage,item,actor))return null;if(root.entityType==='project'&&!processing.restoreMetadataEntity(root.id,actor,{finalizeTrash:false}))return null;for(const item of tasks)if(!restoreItem(processing,storage,item,actor))return null;if(root.entityType==='task'&&!restoreItem(processing,storage,root,actor))return null;if(root.entityType==='project'&&!processing.finishMetadataRestore(root.id,actor))return null;return root.entityType==='project'?processing.getProject(root.entityId):processing.getTask(root.entityId);}
function purgeItem(processing,storage,item,actor){if(!item||item.permanentlyDeletedAt)return true;if(['project','task'].includes(item.entityType))return Boolean(processing.purgeMetadataEntity(item.id,actor));if(item.entityType==='dataset'){const dataset=processing.getDataset(item.entityId);if(dataset?.storageMode==='external_reference')return Boolean(processing.markTrashPurged(item.id,actor));}else if(item.entityType==='output'){const output=processing.getModelOutput(item.entityId);if(output?.storageMode!=='managed')return Boolean(processing.purgeMetadataOutput(item.id,actor));}const mutation=processing.beginPurgeMutation(item.id,actor);if(!mutation)return false;applyStorageMutation(processing,storage,mutation);return true;}
function purgeContainerTrash(processing,storage,containerId,actor){const root=processing.getTrash(containerId);if(!root||!['project','task'].includes(root.entityType))return null;if(root.permanentlyDeletedAt)return root;const order={output:0,dataset:1,task:2,project:3},members=processing.listContainerTrashMembers(root.id).sort((a,b)=>(order[a.entityType]??4)-(order[b.entityType]??4));for(const item of members)if(!purgeItem(processing,storage,item,actor))return null;return purgeItem(processing,storage,root,actor)?processing.getTrash(root.id):null;}

module.exports={trashTaskTree,trashProjectTree,restoreContainerTrash,purgeContainerTrash};
