'use strict';
const crypto=require('node:crypto');
const fail=code=>{throw Object.assign(new Error(code),{code,status:429});};
class EphemeralMeasurementRepository{
  constructor(database){this.database=database;}
  transaction(fn){this.database.exec('BEGIN IMMEDIATE');try{const result=fn();this.database.exec('COMMIT');return result;}catch(e){this.database.exec('ROLLBACK');throw e;}}
  prune(at=Date.now()){return this.database.prepare('DELETE FROM ephemeral_measurement_jobs WHERE expires_at<=?').run(new Date(at).toISOString()).changes;}
  present(row){if(!row)return null;const request=JSON.parse(row.request_json),reference=request.reference||{};return{id:row.id,measurementId:row.measurement_id,revision:1,method:request.method,geometryHash:row.geometry_hash,parameters:{revision:1,method:request.method,sourceAssetId:request.source.id,reference:{type:reference.type,...(Number.isFinite(reference.offsetM)?{offsetM:reference.offsetM}:{}),...(Number.isFinite(reference.elevationM)?{elevationM:reference.elevationM}:{})},sourceVerticalUnit:request.sourceVerticalUnit||null,...(request.method==='surface-transect'?{parentCalculationId:request.parentCalculationId,parentRevision:request.parentRevision,line:request.line,baseHash:request.baseHash}:{})},status:row.status,result:row.result_json?JSON.parse(row.result_json):null,errorCode:row.error_code,createdAt:row.created_at,updatedAt:row.updated_at,expiresAt:row.expires_at};}
  get(scopeKey,pageHash,id){return this.present(this.database.prepare('SELECT * FROM ephemeral_measurement_jobs WHERE id=? AND scope_key=? AND page_hash=? AND expires_at>?').get(id,scopeKey,pageHash,new Date().toISOString()));}
  list(scopeKey,pageHash,measurementId=null){return this.database.prepare(`SELECT * FROM ephemeral_measurement_jobs WHERE scope_key=? AND page_hash=? AND expires_at>?${measurementId?' AND measurement_id=?':''} ORDER BY created_at DESC,id DESC LIMIT 20`).all(scopeKey,pageHash,new Date().toISOString(),...(measurementId?[measurementId]:[])).map(row=>this.present(row));}
  parent(scopeKey,pageHash,id){if(typeof id!=='string')return null;const job=this.get(scopeKey,pageHash,id);if(!job)return null;const row=this.database.prepare('SELECT request_json FROM ephemeral_measurement_jobs WHERE id=? AND scope_key=? AND page_hash=?').get(id,scopeKey,pageHash);return{job,request:JSON.parse(row.request_json)};}
  enqueue(access,pageHash,measurement,request){return this.transaction(()=>{this.prune();const total=this.database.prepare("SELECT (SELECT COUNT(*) FROM measurement_calculation_jobs WHERE status IN ('queued','running'))+(SELECT COUNT(*) FROM ephemeral_measurement_jobs WHERE status IN ('queued','running')) AS n").get().n;if(total>=20)fail('measurement_queue_full');
    if(this.database.prepare('SELECT COUNT(*) AS n FROM ephemeral_measurement_jobs WHERE scope_key=?').get(access.scopeKey).n>=40)fail('measurement_rate_limited');
    if(this.database.prepare("SELECT 1 FROM ephemeral_measurement_jobs WHERE scope_key=? AND page_hash=? AND measurement_id=? AND status IN ('queued','running')").get(access.scopeKey,pageHash,measurement.id))fail('measurement_calculation_already_active');
    const id=crypto.randomUUID(),at=new Date().toISOString(),geometryHash=crypto.createHash('sha256').update(JSON.stringify([measurement.collection,measurement.vertices,[measurement.coordinateReference.crs,measurement.coordinateReference.verticalUnit]])).digest('hex');
    this.database.prepare("INSERT INTO ephemeral_measurement_jobs(id,scope_key,page_hash,measurement_id,geometry_hash,request_json,status,created_at,updated_at,expires_at) VALUES(?,?,?,?,?,?,'queued',?,?,?)").run(id,access.scopeKey,pageHash,measurement.id,geometryHash,JSON.stringify({...request,ephemeralAuthority:access.authority}),at,at,new Date(access.expiresAt).toISOString());return this.get(access.scopeKey,pageHash,id);});}
  cancel(scopeKey,pageHash,id){return this.database.prepare("UPDATE ephemeral_measurement_jobs SET request_json=json_remove(request_json,'$.ephemeralAuthority'),status='cancelled',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND scope_key=? AND page_hash=? AND status IN ('queued','running')").run(new Date().toISOString(),id,scopeKey,pageHash).changes;}
  claim(owner){return this.transaction(()=>{this.prune();const at=new Date().toISOString();this.database.prepare("UPDATE ephemeral_measurement_jobs SET request_json=json_remove(request_json,'$.ephemeralAuthority'),status='failed',error_code='worker_interrupted',lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=? WHERE status='running' AND lease_expires_at<=?").run(at,at);
    if(this.database.prepare("SELECT 1 FROM measurement_calculation_jobs WHERE status='running' UNION ALL SELECT 1 FROM ephemeral_measurement_jobs WHERE status='running' LIMIT 1").get())return null;
    for(const table of ['dataset_operations','processing_jobs','derivative_jobs'])if(this.database.prepare(`SELECT 1 FROM ${table} WHERE status='leased' LIMIT 1`).get())return null;
    const row=this.database.prepare("SELECT * FROM ephemeral_measurement_jobs WHERE status='queued' ORDER BY created_at,id LIMIT 1").get();if(!row)return null;
    const token=crypto.randomUUID();this.database.prepare("UPDATE ephemeral_measurement_jobs SET status='running',lease_owner=?,lease_token=?,lease_expires_at=?,updated_at=? WHERE id=?").run(owner,token,new Date(Date.now()+90_000).toISOString(),at,row.id);return{id:row.id,measurementId:row.measurement_id,scopeKey:row.scope_key,pageHash:row.page_hash,token,request:JSON.parse(row.request_json)};});}
  live(job,owner){const at=new Date().toISOString();return Boolean(this.database.prepare("SELECT 1 FROM ephemeral_measurement_jobs WHERE id=? AND status='running' AND lease_owner=? AND lease_token=? AND lease_expires_at>? AND expires_at>?").get(job.id,owner,job.token,at,at));}
  heartbeat(job,owner){if(!this.live(job,owner))return false;this.database.prepare('UPDATE ephemeral_measurement_jobs SET lease_expires_at=? WHERE id=?').run(new Date(Date.now()+90_000).toISOString(),job.id);return true;}
  finish(job,owner,result,errorCode=null){if(!this.live(job,owner))return false;return this.database.prepare("UPDATE ephemeral_measurement_jobs SET request_json=json_remove(request_json,'$.ephemeralAuthority'),status=?,result_json=?,error_code=?,lease_owner=NULL,lease_token=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND lease_token=?").run(errorCode?'failed':'complete',result?JSON.stringify(result):null,errorCode,new Date().toISOString(),job.id,job.token).changes;}
}
module.exports={EphemeralMeasurementRepository};
