'use strict';
const fs=require('node:fs'),path=require('node:path');
const {safeRelativePath}=require('./processingSecurity');
const DIRECTORY_ENTRY_LIMIT=10000,fail=(code)=>{throw Object.assign(new Error(code),{code});};
const compare=(a,b)=>a.kind.localeCompare(b.kind)||(a.name<b.name?-1:a.name>b.name?1:0);
function canonical(value,{allowRoot=false}={}){if(allowRoot&&value==='')return'';const result=safeRelativePath(value);if(!result||result!==value||value.includes('\\'))fail('invalid_import_path');return result;}
function lexicalPath(storage,relativePath,{allowRoot=false}={}){const configured=storage.roots.dataset_import;if(!configured)fail('import_mount_unavailable');let root;try{root=fs.realpathSync.native(configured);}catch{fail('import_mount_unavailable');}const rel=canonical(relativePath,{allowRoot});let current=root;for(const component of rel?rel.split('/'):[]){current=path.join(current,component);let stat;try{stat=fs.lstatSync(current);}catch{fail('import_path_unavailable');}if(stat.isSymbolicLink())fail('invalid_import_path');}return{relativePath:rel,absolutePath:current};}
function cursor(value,relativePath,mtimeMs){if(!value)return null;try{const parsed=JSON.parse(Buffer.from(String(value),'base64url').toString('utf8'));if(parsed?.v!==1||parsed.path!==relativePath||parsed.mtimeMs!==mtimeMs||!['folder','zip'].includes(parsed.kind)||typeof parsed.name!=='string')fail('invalid_cursor');return{kind:parsed.kind,name:parsed.name};}catch(error){if(error.code)throw error;fail('invalid_cursor');}}
function browseImportRoot(storage,{relativePath='',cursor:value=null,limit=50}={}){const located=lexicalPath(storage,relativePath,{allowRoot:true});let stat;try{stat=fs.lstatSync(located.absolutePath);}catch{fail('import_path_unavailable');}if(!stat.isDirectory())fail('invalid_import_path');const dirents=fs.readdirSync(located.absolutePath,{withFileTypes:true});if(dirents.length>DIRECTORY_ENTRY_LIMIT)fail('import_directory_too_large');const entries=[];for(const entry of dirents){if(entry.name.startsWith('.')||/[\u0000-\u001f]/.test(entry.name))continue;const childStat=fs.lstatSync(path.join(located.absolutePath,entry.name));if(childStat.isSymbolicLink())continue;const kind=childStat.isDirectory()?'folder':childStat.isFile()&&path.extname(entry.name).toLowerCase()==='.zip'?'zip':null;if(!kind)continue;entries.push({name:entry.name,relativePath:located.relativePath?`${located.relativePath}/${entry.name}`:entry.name,kind,...(kind==='zip'?{byteSize:childStat.size}:{})});}entries.sort(compare);const mtimeMs=Math.trunc(stat.mtimeMs),after=cursor(value,located.relativePath,mtimeMs),start=after?entries.findIndex((item)=>compare(item,after)>0):0,offset=start<0?entries.length:start,page=entries.slice(offset,offset+limit),more=offset+limit<entries.length,nextCursor=more?Buffer.from(JSON.stringify({v:1,path:located.relativePath,mtimeMs,kind:page.at(-1).kind,name:page.at(-1).name})).toString('base64url'):null;return{path:located.relativePath,parentPath:located.relativePath.includes('/')?located.relativePath.slice(0,located.relativePath.lastIndexOf('/')):located.relativePath?'':null,entries:page,nextCursor};}
function validateImportSelection(storage,relativePath,{expectedKind=null}={}){const located=lexicalPath(storage,canonical(relativePath)),stat=fs.lstatSync(located.absolutePath);const kind=stat.isDirectory()?'folder':stat.isFile()&&path.extname(located.absolutePath).toLowerCase()==='.zip'?'zip':null;if(!kind||(expectedKind&&kind!==expectedKind))fail('invalid_import_source');return{relativePath:located.relativePath,kind};}
module.exports={DIRECTORY_ENTRY_LIMIT,browseImportRoot,validateImportSelection};
