'use strict';

const crypto = require('node:crypto');
const express = require('express');
const { config } = require('./config');
const auth = require('./auth');
const { verifyServiceRequest, sha256Hex } = require('./serviceAuth');
const { idempotent } = require('./serviceIdempotency');
const { NodeOdmProvider } = require('./nodeOdmProvider');
const { admitProviderEndpoint } = require('./providerAdmission');
const { publicDerivativeKind, safeRelativePath, sanitizeLogMessage } = require('./processingSecurity');
const { applyStorageMutation } = require('./storageLifecycle');
const { mountGcpRoutes } = require('./gcpApi');

const PERMISSIONS = new Set(['viewer.projects.read','viewer.projects.write','viewer.datasets.read','viewer.datasets.write','viewer.datasets.import','viewer.processing.read','viewer.processing.write','viewer.processing.publish','viewer.providers.read','viewer.providers.write','viewer.storage.purge','viewer.gcp.read','viewer.gcp.write']);
function validUnits(value) { return value === 'imperial' || value === 'metric'; }
function error(res,status,code,message=code,details) { return res.status(status).json({error:message,code,...(details?{details}:{})}); }
function pageQuery(req) { const raw=String(req.query.limit||'50');if(!/^\d{1,3}$/.test(raw))return null;const limit=Number(raw);if(limit<1||limit>100)return null;const cursor=req.query.cursor?String(req.query.cursor):null;if(cursor&&!/^[A-Za-z0-9_-]{8,2048}$/.test(cursor))return null;return{limit,cursor}; }
function uploadView(processing,upload) { return {id:upload.id,datasetId:upload.datasetId,status:upload.status,chunkSize:upload.chunkSize,expiresAt:upload.expiresAt,files:upload.files.map((file)=>{const chunkCount=Math.ceil(file.byteSize/upload.chunkSize)||1,completedChunks=processing.listChunks(upload.id,file.id).map((c)=>c.chunk_index),done=new Set(completedChunks);return{id:file.id,relativePath:file.relativePath,byteSize:file.byteSize,sha256:file.sha256,chunkCount,completedChunks,missingChunks:Array.from({length:chunkCount},(_,i)=>i).filter((i)=>!done.has(i))};})}; }
function publicStorageSpace(value) { return {availableBytes:Number(value.available),totalBytes:Number(value.total),reserveBytes:Number(value.reserve),requiredBytes:Number(value.required),sufficient:Boolean(value.ok)}; }
function publicImportPreview(preview) { return {...preview,destinationSpace:publicStorageSpace(preview.destinationSpace)}; }
function onlyKeys(value,allowed){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every((key)=>allowed.includes(key));}
function optionDomain(spec){if(Array.isArray(spec.domain))return spec.domain;if(spec.domain&&typeof spec.domain==='object')return spec.domain;if(typeof spec.domain==='string'){try{return JSON.parse(spec.domain);}catch{return null;}}return null;}
function validateProviderOptions(options,byName){if(!options||Array.isArray(options)||typeof options!=='object'||Object.keys(options).length>200||Buffer.byteLength(JSON.stringify(options))>64*1024)return'invalid_provider_options';for(const[name,value]of Object.entries(options)){const spec=byName.get(name);if(!spec)return'invalid_provider_option';if(spec.type==='bool'&&typeof value!=='boolean')return'invalid_provider_option';if(spec.type==='int'&&!Number.isInteger(value))return'invalid_provider_option';if(spec.type==='float'&&(typeof value!=='number'||!Number.isFinite(value)))return'invalid_provider_option';if(!['bool','int','float'].includes(spec.type)&&(typeof value!=='string'||value.length>4000))return'invalid_provider_option';const domain=optionDomain(spec);if(Array.isArray(domain)&&!domain.includes(value))return'invalid_provider_option';if(domain&&!Array.isArray(domain)&&typeof value==='number'&&((Number.isFinite(domain.min)&&value<domain.min)||(Number.isFinite(domain.max)&&value>domain.max)))return'invalid_provider_option';}return null;}

function createProcessingApi({ repository, processing, storage, providerCredentials, providerFetch }) {
  const router=express.Router();
  const serviceIdempotency=idempotent(repository);
  router.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');const origin=req.get('origin');if(origin&&origin===config.opsBaseUrl){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Expose-Headers','Location, Retry-After');res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type,Idempotency-Key,X-Upload-Token,X-Chunk-SHA256');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,PUT,DELETE,OPTIONS');}if(req.method==='OPTIONS')return origin===config.opsBaseUrl?res.sendStatus(204):res.sendStatus(403);next();});

  function service(req) { const checked=verifyServiceRequest({headers:req.headers,method:req.method,path:req.originalUrl,rawBody:req.rawBody||Buffer.alloc(0),repository});if(!checked.ok)return null;req.servicePrincipal={keyId:checked.keyId};return req.servicePrincipal; }
  function admin(req) { const token=String(req.get('authorization')||'').match(/^Bearer\s+([A-Za-z0-9_-]{32,128})$/i)?.[1];if(!token)return null;const session=processing.getAdminSessionByHash(auth.hashToken(token));if(!processing.adminSessionLive(session))return null;req.adminPrincipal=session;return session; }
  function authorize(permission,{hmacOnly=false}={}) { return (req,res,next)=>{const principal=hmacOnly?service(req):admin(req);if(!principal)return error(res,401,'authentication_required','authentication required');if(!hmacOnly&&!req.adminPrincipal.permissions.includes(permission))return error(res,403,'permission_denied','permission denied');req.actorId=hmacOnly?req.servicePrincipal.keyId:req.adminPrincipal.subject;next();}; }
  function mutate(req,res,next) { const key=req.get('Idempotency-Key');if(!key)return error(res,428,'idempotency_key_required','Idempotency-Key is required');if(!/^[A-Za-z0-9._:-]{8,128}$/.test(key))return error(res,400,'invalid_idempotency_key');if(req.servicePrincipal)return serviceIdempotency(req,res,next);const rawBody=req.rawBody||Buffer.alloc(0),requestHash=req.path.startsWith('/api/v1/processing/providers')?providerCredentials.idempotencyFingerprint(req.method,req.originalUrl,rawBody):sha256Hex(Buffer.concat([Buffer.from(`${req.method}\n${req.originalUrl}\n`),rawBody]));const reservation=processing.reserveAdminIdempotency({sessionId:req.adminPrincipal.id,key,method:req.method,path:req.originalUrl,requestHash});if(!reservation.created){const r=reservation.record;if(r.method!==req.method||r.path!==req.originalUrl||r.request_hash!==requestHash)return error(res,409,'idempotency_conflict');if(r.response_status!==null){res.setHeader('Idempotency-Replayed','true');const body=JSON.parse(r.response_json||'null');if(r.response_status===202&&body?.operation?.id){res.setHeader('Location',`/api/v1/operations/${body.operation.id}`);res.setHeader('Retry-After','2');}return r.response_status===204?res.status(204).end():res.status(r.response_status).json(body);}return error(res,409,'idempotency_in_progress');}let finalized=false;const finish=(body)=>{if(!finalized&&res.statusCode<500){finalized=true;processing.completeAdminIdempotency(req.adminPrincipal.id,key,res.statusCode,body);}};const originalJson=res.json.bind(res),originalEnd=res.end.bind(res);res.json=(body)=>{finish(body);return originalJson(body);};res.end=(...args)=>{finish(null);return originalEnd(...args);};next(); }
  const providerView=(provider)=>providerCredentials?providerCredentials.view(provider):provider;
  const providerAdmission=(endpoint)=>admitProviderEndpoint(endpoint,{exactOrigins:config.processingProviderOrigins,allowedCidrs:config.processingProviderAllowedCidrs});
  const providerCredentialFailure=(res,e)=>error(res,e.code==='provider_in_use'?409:e.code==='invalid_provider_credential'?400:503,e.code||'provider_credential_unavailable');

  router.post('/api/v1/admin-grants',authorize('',{hmacOnly:true}),mutate,(req,res)=>{const b=req.body||{};if(typeof b.subject!=='string'||!b.subject||b.subject.length>200)return error(res,400,'invalid_subject');if(!Array.isArray(b.permissions)||b.permissions.some((p)=>!PERMISSIONS.has(p)))return error(res,400,'invalid_permissions');if(!validUnits(b.displayUnits))return error(res,400,'invalid_units');const authExpiry=Date.parse(b.authorizationExpiresAt||'');if(!Number.isFinite(authExpiry)||authExpiry<=Date.now())return error(res,400,'invalid_authorization_expiry');const authorizationExpiresAt=new Date(authExpiry).toISOString(),expiresAt=new Date(Math.min(authExpiry,Date.now()+config.sessionGrantTtlSeconds*1000)).toISOString();const grant=processing.createAdminGrant({subject:b.subject,permissions:[...new Set(b.permissions)],displayUnits:b.displayUnits,expiresAt,authorizationExpiresAt});res.status(201).json({grant:grant.token,grantExpiresAt:expiresAt,redeemUrl:`${config.publicBaseUrl||''}/api/v1/admin-sessions/redeem`,sessionTtlSeconds:config.adminSessionTtlSeconds});});

  router.post('/api/v1/admin-sessions/redeem',(req,res)=>{if(auth.rateLimited(`admin-redeem-ip:${req.ip}`,20,5*60_000))return error(res,429,'rate_limited','too many attempts');const token=req.body?.grant;if(typeof token!=='string'||!/^[A-Za-z0-9_-]{32,128}$/.test(token))return error(res,400,'invalid_grant');const grant=processing.redeemAdminGrant(token);if(!grant)return error(res,410,'grant_unavailable','grant expired or already redeemed');const expiresAt=new Date(Math.min(Date.parse(grant.authorizationExpiresAt),Date.now()+config.adminSessionTtlSeconds*1000)).toISOString();if(Date.parse(expiresAt)<=Date.now())return error(res,410,'authorization_expired');const existing=admin(req);let accessToken,session;if(existing&&existing.subject===grant.subject){accessToken=String(req.get('authorization')).replace(/^Bearer\s+/i,'');session=processing.renewAdminSession(existing.id,{permissions:grant.permissions,displayUnits:grant.displayUnits,expiresAt});}else{accessToken=crypto.randomBytes(32).toString('base64url');session=processing.createAdminSession({tokenHash:auth.hashToken(accessToken),subject:grant.subject,permissions:grant.permissions,displayUnits:grant.displayUnits,expiresAt});}res.json({accessToken,session:{id:session.id,subject:session.subject,permissions:session.permissions,displayUnits:session.displayUnits,expiresAt:session.expiresAt},units:{default:config.defaultUnits,resolved:session.displayUnits}});});

  router.get('/api/v1/projects',authorize('viewer.projects.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');const result=processing.listProjectsPage(page);res.json({projects:result.items,nextCursor:result.nextCursor});});
  router.post('/api/v1/projects',authorize('viewer.projects.write'),mutate,(req,res)=>{const b=req.body||{};if(!b.displayName)return error(res,400,'display_name_required');if(b.defaultUnits&&!validUnits(b.defaultUnits))return error(res,400,'invalid_units');res.status(201).json({project:processing.createProject({...b,createdBy:req.actorId,defaultUnits:b.defaultUnits||config.defaultUnits})});});
  router.get('/api/v1/projects/:id',authorize('viewer.projects.read'),(req,res)=>{const p=processing.getProject(req.params.id);return p?res.json({project:p}):error(res,404,'project_not_found');});
  router.patch('/api/v1/projects/:id',authorize('viewer.projects.write'),mutate,(req,res)=>{if(!onlyKeys(req.body,['displayName','description','tags','metadata','defaultUnits']))return error(res,400,'invalid_patch_fields');if(req.body?.defaultUnits&&!validUnits(req.body.defaultUnits))return error(res,400,'invalid_units');try{const p=processing.updateProject(req.params.id,req.body||{});return p?res.json({project:p}):error(res,404,'project_not_found');}catch(e){return error(res,e.code?.includes('conflict')?409:400,e.code||'invalid_project');}});
  router.post('/api/v1/projects/:id/archive',authorize('viewer.projects.write'),mutate,(req,res)=>{const p=processing.archiveProject(req.params.id);return p?res.json({project:p}):error(res,409,'project_not_archivable');});
  router.get('/api/v1/projects/:id/storage',authorize('viewer.datasets.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');const result=processing.projectStorage(req.params.id,page);return result?res.json(result):error(res,404,'project_not_found');});

  router.get('/api/v1/datasets',authorize('viewer.datasets.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');const result=processing.listDatasetsPage({...page,projectId:req.query.projectId||null});res.json({datasets:result.items,nextCursor:result.nextCursor});});
  router.post('/api/v1/datasets',authorize('viewer.datasets.write'),mutate,(req,res)=>{const b=req.body||{},project=processing.getProject(b.projectId);if(!project)return error(res,400,'invalid_project');if(!b.displayName)return error(res,400,'display_name_required');const id=crypto.randomUUID();const dataset=processing.createDataset({...b,id,createdBy:req.actorId,storageMode:'managed',rootKey:'datasets',relativePath:id,status:'draft',sourceType:'upload'});res.status(201).json({dataset});});
  router.get('/api/v1/datasets/:id',authorize('viewer.datasets.read'),(req,res)=>{const d=processing.getDataset(req.params.id,true);return d?res.json({dataset:d}):error(res,404,'dataset_not_found');});
  router.patch('/api/v1/datasets/:id',authorize('viewer.datasets.write'),mutate,(req,res)=>{if(!onlyKeys(req.body,['displayName','description','tags','metadata','projectId']))return error(res,400,'invalid_patch_fields');try{const d=processing.updateDatasetMetadata(req.params.id,req.body||{});return d?res.json({dataset:d}):error(res,404,'dataset_not_found');}catch(e){return error(res,['dataset_reassociation_blocked','dataset_name_conflict'].includes(e.code)?409:400,e.code||'invalid_dataset');}});
  router.post('/api/v1/datasets/:id/archive',authorize('viewer.datasets.write'),mutate,(req,res)=>{const d=processing.archiveDataset(req.params.id);return d?res.json({dataset:d}):error(res,409,'dataset_not_archivable');});
  router.delete('/api/v1/datasets/:id',authorize('viewer.storage.purge'),mutate,(req,res)=>{const d=processing.getDataset(req.params.id);if(!d)return error(res,404,'dataset_not_found');if(processing.datasetReferences(d.id)>0||processing.activeDatasetOperations(d.id)>0)return error(res,409,'dataset_in_use');for(const uploadId of processing.cancelDatasetUploads(d.id))storage.cleanupUpload(uploadId);let item;if(d.storageMode==='external_reference'){item=processing.trashDataset(d.id,{trashRelative:'',actor:req.actorId});if(!item)return error(res,409,'dataset_not_trashable');}else{const mutation=processing.beginTrashMutation(d.id,req.actorId);if(!mutation)return error(res,409,'dataset_in_use');applyStorageMutation(processing,storage,mutation);item=processing.getTrash(mutation.trashId);}repository.audit({actorType:'admin',actorId:req.actorId,action:'dataset.trashed',entityType:'dataset',entityId:d.id});res.json({trash:item});});
  router.get('/api/v1/storage',authorize('viewer.datasets.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');res.json({storage:Object.fromEntries(['datasets','models','cache','trash'].map((key)=>[key,storage.space(key)])),trash:processing.listTrashPage(page)});});
  router.get('/api/v1/storage/mutations',authorize('viewer.storage.purge'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');try{const result=processing.listStorageMutationsPage({...page,status:req.query.status||null});res.json({mutations:result.items,nextCursor:result.nextCursor});}catch(e){return error(res,400,e.code||'invalid_status');}});
  router.post('/api/v1/storage/mutations/:id/retry',authorize('viewer.storage.purge'),mutate,(req,res)=>{if(!onlyKeys(req.body,[]))return error(res,400,'invalid_request');const mutation=processing.retryStorageMutation(req.params.id);if(!mutation)return error(res,409,'lifecycle_not_retryable');try{const completed=applyStorageMutation(processing,storage,mutation);repository.audit({actorType:'admin',actorId:req.actorId,action:'storage.lifecycle_retried',entityType:mutation.entityType,entityId:mutation.entityId,details:{mutationId:mutation.id,type:mutation.type}});return res.json({mutation:completed});}catch(e){return error(res,409,e.code||'lifecycle_failed');}});
  router.post('/api/v1/storage/trash/:id/restore',authorize('viewer.storage.purge'),mutate,(req,res)=>{const item=processing.getTrash(req.params.id);if(!item)return error(res,404,'trash_not_found');if(item.entityType==='dataset'){const dataset=processing.getDataset(item.entityId);if(!dataset)return error(res,404,'trash_not_found');let restored;if(dataset.storageMode==='external_reference')restored=processing.restoreTrash(item.id);else{const mutation=processing.beginRestoreMutation(item.id,req.actorId);if(!mutation)return error(res,409,'lifecycle_conflict');applyStorageMutation(processing,storage,mutation);restored=processing.getDataset(dataset.id);}repository.audit({actorType:'admin',actorId:req.actorId,action:'dataset.restored',entityType:'dataset',entityId:dataset.id});return res.json({dataset:restored});}if(item.entityType!=='output')return error(res,404,'trash_not_found');const mutation=processing.beginRestoreMutation(item.id,req.actorId);if(!mutation)return error(res,409,'lifecycle_conflict');applyStorageMutation(processing,storage,mutation);const output=processing.getModelOutput(item.entityId);repository.audit({actorType:'admin',actorId:req.actorId,action:'output.restored',entityType:'output',entityId:item.entityId});return res.json({output});});
  router.delete('/api/v1/storage/trash/:id',authorize('viewer.storage.purge'),mutate,(req,res)=>{const item=processing.getTrash(req.params.id);if(!item||item.permanentlyDeletedAt)return error(res,404,'trash_not_found');if(req.body?.typedId!==item.entityId)return error(res,400,'typed_confirmation_required');const dataset=item.entityType==='dataset'?processing.getDataset(item.entityId):null;if(dataset?.storageMode==='external_reference')processing.markTrashPurged(item.id);else{const mutation=processing.beginPurgeMutation(item.id,req.actorId);if(!mutation)return error(res,409,'lifecycle_conflict');applyStorageMutation(processing,storage,mutation);}repository.audit({actorType:'admin',actorId:req.actorId,action:`${item.entityType}.purged`,entityType:item.entityType,entityId:item.entityId});res.status(204).end();});
  router.post('/api/v1/datasets/:id/uploads',authorize('viewer.datasets.write'),mutate,(req,res)=>{const d=processing.getDataset(req.params.id);if(!d||d.status!=='draft'||d.storageMode!=='managed')return error(res,409,'dataset_not_uploadable');const files=req.body?.files;if(!Array.isArray(files)||!files.length||files.length>config.uploadMaxFiles)return error(res,400,'invalid_manifest');let total=0;const seen=new Set(),ids=new Set(),basenames=new Set();for(const f of files){const rel=safeRelativePath(f.relativePath),base=rel&&rel.split('/').at(-1).toLowerCase();if(typeof f.id!=='string'||!/^[A-Za-z0-9._-]{1,80}$/.test(f.id)||ids.has(f.id)||!rel||rel!==f.relativePath||!Number.isSafeInteger(f.byteSize)||f.byteSize<0||!/^[a-f0-9]{64}$/.test(f.sha256)||seen.has(f.relativePath)||basenames.has(base))return error(res,400,'invalid_manifest');ids.add(f.id);seen.add(f.relativePath);basenames.add(base);total+=f.byteSize;if(!Number.isSafeInteger(total))return error(res,400,'manifest_too_large');}if(Buffer.byteLength(JSON.stringify(files))>config.uploadMaxManifestBytes)return error(res,413,'manifest_too_large');if(storage.sameFilesystem('datasets','cache'))storage.requireSpace('datasets',total*2);else{storage.requireSpace('datasets',total);storage.requireSpace('cache',total);}const expiresAt=new Date(Date.now()+24*3600_000).toISOString(),created=processing.resumeUpload(d.id,req.actorId,files,expiresAt)||processing.createUpload({datasetId:d.id,files,subject:req.actorId,chunkSize:config.uploadChunkBytes,expiresAt});res.status(201).json({upload:uploadView(processing,created.upload),uploadToken:created.token});});

  router.get('/api/v1/admin/uploads/:id',authorize('viewer.datasets.write'),(req,res)=>{const upload=processing.getUpload(req.params.id);if(!upload||Date.parse(upload.expiresAt)<=Date.now())return error(res,410,'upload_unavailable');if(upload.subject!==req.actorId)return error(res,403,'upload_subject_mismatch');if(!processing.verifyUploadToken(upload,req.get('X-Upload-Token')))return error(res,403,'invalid_upload_token');res.json({upload:uploadView(processing,upload)});});

  router.put('/api/v1/admin/uploads/:uploadId/files/:fileId/chunks/:index',authorize('viewer.datasets.write'),express.raw({type:'application/octet-stream',limit:config.uploadChunkBytes}),async(req,res,next)=>{try{const upload=processing.getUpload(req.params.uploadId);if(!upload||upload.status!=='open'||Date.parse(upload.expiresAt)<=Date.now())return error(res,410,'upload_unavailable');if(upload.subject!==req.actorId)return error(res,403,'upload_subject_mismatch');if(!processing.verifyUploadToken(upload,req.get('X-Upload-Token')))return error(res,403,'invalid_upload_token');const spec=upload.files.find((f)=>f.id===req.params.fileId),index=Number(req.params.index),count=spec?Math.ceil(spec.byteSize/upload.chunkSize)||1:0,expected=spec?(index===count-1?spec.byteSize-upload.chunkSize*(count-1):upload.chunkSize):0;if(!spec||!Number.isSafeInteger(index)||index<0||index>=count||!Buffer.isBuffer(req.body)||req.body.length!==expected)return error(res,400,'invalid_chunk');const sha=req.get('X-Chunk-SHA256');if(!/^[a-f0-9]{64}$/.test(sha||''))return error(res,400,'invalid_chunk_checksum');const written=storage.writeChunk(upload.id,spec.id,index,req.body,sha);const chunk=processing.recordChunk({uploadId:upload.id,fileId:spec.id,chunkIndex:index,relativePath:spec.relativePath,...written});res.status(written.replayed||chunk.replayed?200:201).json({chunk});}catch(e){next(e);}});
  router.post('/api/v1/admin/uploads/:id/finalize',authorize('viewer.datasets.write'),mutate,(req,res)=>{const upload=processing.getUpload(req.params.id);if(!upload||!['open','finalizing','complete'].includes(upload.status)||Date.parse(upload.expiresAt)<=Date.now())return error(res,409,'upload_not_open');if(upload.subject!==req.actorId)return error(res,403,'upload_subject_mismatch');if(!processing.verifyUploadToken(upload,req.body?.uploadToken))return error(res,403,'invalid_upload_token');if(upload.status==='open'){for(const file of upload.files){const chunks=processing.listChunks(upload.id,file.id),expected=Math.ceil(file.byteSize/upload.chunkSize)||1;if(chunks.length!==expected||chunks.some((c,i)=>c.chunk_index!==i))return error(res,409,'upload_incomplete');}}const operation=processing.createUploadFinalizeOperation(upload.id,req.actorId);return operation?res.status(202).set('Location',`/api/v1/operations/${operation.id}`).set('Retry-After','2').json({operation}):error(res,409,'upload_finalizing');});

  router.post('/api/v1/dataset-imports/preview',authorize('viewer.datasets.import'),mutate,(req,res)=>{const rootKey=req.body?.rootKey,relativePath=safeRelativePath(req.body?.relativePath);if(!['dataset_import','terra_import','webodm'].includes(rootKey))return error(res,400,'invalid_import_root');if(!relativePath)return error(res,400,'invalid_import');const operation=processing.createImportPreviewOperation({request:{rootKey,relativePath},subject:req.actorId,sessionId:req.adminPrincipal?.id});return res.status(202).set('Location',`/api/v1/operations/${operation.id}`).set('Retry-After','2').json({operation});});
  router.post('/api/v1/dataset-imports/adopt',authorize('viewer.datasets.import'),mutate,(req,res)=>{const sessionId=req.adminPrincipal?.id||null,preview=processing.getImportPreview(req.body?.previewToken,sessionId);if(!preview)return error(res,410,'preview_unavailable');if(preview.createdBy!==req.actorId)return error(res,403,'preview_subject_mismatch');if(!processing.getProject(req.body?.projectId))return error(res,400,'invalid_project');if(!['adopted','external_reference'].includes(req.body?.storageMode)||(preview.request.rootKey==='webodm'&&req.body.storageMode!=='external_reference'))return error(res,400,'invalid_storage_mode');const operation=processing.createImportAdoptOperation({previewToken:req.body.previewToken,sessionId,subject:req.actorId,projectId:req.body.projectId,displayName:req.body.displayName||pathName(preview.request.relativePath),storageMode:req.body.storageMode});return operation?res.status(202).set('Location',`/api/v1/operations/${operation.id}`).set('Retry-After','2').json({operation}):error(res,409,'preview_claimed');});

  router.get('/api/v1/operations/:id',authorize('viewer.datasets.read'),(req,res)=>{const operation=processing.getDatasetOperation(req.params.id,req.actorId);return operation?res.set('Cache-Control','no-store').json({operation}):error(res,404,'operation_not_found');});
  router.post('/api/v1/operations/:id/cancel',authorize('viewer.datasets.import'),mutate,(req,res)=>{if(!onlyKeys(req.body,[]))return error(res,400,'invalid_request');const operation=processing.cancelImportPreviewOperation(req.params.id,req.actorId);return operation?res.set('Cache-Control','no-store').json({operation}):error(res,409,'operation_not_cancellable');});

  router.get('/api/v1/processing/providers',authorize('viewer.providers.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');const result=processing.listProvidersPage(page);res.json({providers:result.items.map(providerView),nextCursor:result.nextCursor});});
  router.post('/api/v1/processing/providers',authorize('viewer.providers.write'),mutate,(req,res)=>{const b=req.body||{};if(!onlyKeys(b,['type','displayName','endpoint','enabled','admissionLimit','credential']))return error(res,400,'invalid_request');if(!['nodeodm','clusterodm'].includes(b.type))return error(res,400,'invalid_provider_type');const admitted=providerAdmission(b.endpoint);if(!admitted.ok)return error(res,400,admitted.code);if(typeof b.displayName!=='string'||!b.displayName.trim())return error(res,400,'display_name_required');if(b.admissionLimit!==undefined&&(!Number.isSafeInteger(b.admissionLimit)||b.admissionLimit<1||b.admissionLimit>100))return error(res,400,'invalid_admission_limit');if(b.credential!==undefined&&(!onlyKeys(b.credential,['token'])||!Object.hasOwn(b.credential,'token')))return error(res,400,'invalid_provider_credential');const id=crypto.randomUUID();let sealed=null;try{if(b.credential)sealed=providerCredentials.seal(id,b.credential.token);}catch(e){return providerCredentialFailure(res,e);}const provider=processing.upsertProvider({id,type:b.type,displayName:b.displayName,endpoint:admitted.origin,enabled:false,authEnvKey:null,admissionLimit:b.admissionLimit||(b.type==='clusterodm'?4:1),credentialCiphertext:sealed?.ciphertext,credentialKeyId:sealed?.keyId,credentialUpdatedAt:sealed?new Date().toISOString():null});repository.audit({actorType:'admin',actorId:req.actorId,action:'provider.created',entityType:'processing_provider',entityId:id,details:{type:b.type,credentialConfigured:Boolean(sealed)}});res.status(201).json({provider:providerView(provider)});});
  router.patch('/api/v1/processing/providers/:id',authorize('viewer.providers.write'),mutate,(req,res)=>{const current=processing.getProvider(req.params.id);if(!current)return error(res,404,'provider_not_found');if(!onlyKeys(req.body,['displayName','endpoint','enabled','admissionLimit']))return error(res,400,'invalid_patch_fields');if(req.body.enabled!==undefined&&typeof req.body.enabled!=='boolean')return error(res,400,'invalid_provider_enabled');const b={...current,...req.body},admitted=providerAdmission(b.endpoint);if(!admitted.ok)return error(res,400,admitted.code);b.endpoint=admitted.origin;if(typeof b.displayName!=='string'||!b.displayName.trim())return error(res,400,'display_name_required');if(!Number.isSafeInteger(b.admissionLimit)||b.admissionLimit<1||b.admissionLimit>100)return error(res,400,'invalid_admission_limit');const endpointChanged=b.endpoint!==current.endpoint;if(endpointChanged&&current.activeAttempts>0)return error(res,409,'provider_in_use');if(endpointChanged)b.enabled=false;if(b.enabled===true){if(!providerCredentials?.configured(current.id))return error(res,409,'provider_credential_required');try{providerCredentials.resolve(current.id);}catch(e){return providerCredentialFailure(res,e);}if(!processing.providerProbeCurrent(current.id))return error(res,409,'provider_probe_required');}try{const provider=processing.updateProviderMetadata(current.id,b);repository.audit({actorType:'admin',actorId:req.actorId,action:'provider.updated',entityType:'processing_provider',entityId:current.id,details:{endpointChanged,enabled:provider.enabled}});return res.json({provider:providerView(provider)});}catch(e){if(['provider_in_use','provider_credential_required','provider_probe_required'].includes(e.code))return error(res,409,e.code);throw e;}});
  router.put('/api/v1/processing/providers/:id/credential',authorize('viewer.providers.write'),mutate,(req,res)=>{const current=processing.getProvider(req.params.id);if(!current)return error(res,404,'provider_not_found');if(!onlyKeys(req.body,['token'])||!Object.hasOwn(req.body,'token'))return error(res,400,'invalid_provider_credential');try{const sealed=providerCredentials.seal(current.id,req.body.token),provider=processing.setProviderCredential(current.id,sealed);repository.audit({actorType:'admin',actorId:req.actorId,action:current.credential.configured?'provider.credential_rotated':'provider.credential_configured',entityType:'processing_provider',entityId:current.id});return res.json({provider:providerView(provider)});}catch(e){return providerCredentialFailure(res,e);}});
  router.delete('/api/v1/processing/providers/:id/credential',authorize('viewer.providers.write'),mutate,(req,res)=>{const current=processing.getProvider(req.params.id);if(!current)return error(res,404,'provider_not_found');try{const provider=processing.clearProviderCredential(current.id);repository.audit({actorType:'admin',actorId:req.actorId,action:'provider.credential_cleared',entityType:'processing_provider',entityId:current.id});return res.json({provider:providerView(provider)});}catch(e){return providerCredentialFailure(res,e);}});
  router.get('/api/v1/processing/providers/:id/capabilities',authorize('viewer.providers.read'),(req,res)=>{const p=processing.getProvider(req.params.id);return p?res.json({capabilities:p.capabilities,fingerprint:p.capabilityFingerprint,lastHealth:p.lastHealth,lastHealthAt:p.lastHealthAt}):error(res,404,'provider_not_found');});
  router.post('/api/v1/processing/providers/:id/capabilities/probe',authorize('viewer.providers.write'),mutate,async(req,res,next)=>{try{const p=processing.getProvider(req.params.id);if(!p)return error(res,404,'provider_not_found');const credential=providerCredentials.resolveWithRevision(p.id),result=await new NodeOdmProvider({endpoint:p.endpoint,token:credential.token,providerType:p.type,...(providerFetch?{fetchImpl:providerFetch}:{})}).capabilities(),updated=processing.updateProviderCapabilities(p.id,{...result,health:'healthy',expectedCredentialRevision:credential.revision,expectedEndpoint:p.endpoint});if(!updated)return error(res,409,'provider_probe_stale');res.json(result);}catch(e){if(e.code==='provider_credential_unavailable')return providerCredentialFailure(res,e);next(e);}});
  router.get('/api/v1/processing/presets',authorize('viewer.processing.read'),(_q,res)=>res.json({presets:processing.listPresets()}));
  router.get('/api/v1/processing/ready',authorize('viewer.processing.read'),(_req,res)=>{const worker=processing.workerStatus(),lifecycle=processing.storageMutationSummary(),blocked=lifecycle.some((row)=>row.status==='failed'&&row.count>0),ok=worker.live&&!blocked;res.status(ok?200:503).json({ok,worker,lifecycle});});
  router.get('/api/v1/processing/outputs',authorize('viewer.processing.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');try{const result=processing.listModelOutputsPage({...page,projectId:req.query.projectId||null,taskId:req.query.taskId||null,status:req.query.status||null});res.json({outputs:result.items,nextCursor:result.nextCursor,totalCount:result.totalCount,totalBytes:result.totalBytes});}catch(e){return error(res,400,e.code||'invalid_status');}});
  router.post('/api/v1/processing/outputs/:id/archive',authorize('viewer.processing.publish'),mutate,(req,res)=>{if(!onlyKeys(req.body,[]))return error(res,400,'invalid_request');const output=processing.archiveModelOutput(req.params.id);if(!output)return error(res,409,'output_not_archivable');repository.audit({actorType:'admin',actorId:req.actorId,action:'output.archived',entityType:'output',entityId:output.id});res.json({output});});
  router.delete('/api/v1/processing/outputs/:id',authorize('viewer.processing.publish'),mutate,(req,res)=>{const current=processing.getModelOutput(req.params.id);if(!current)return error(res,404,'output_not_found');const mutation=processing.beginOutputTrashMutation(current.id,req.actorId);if(!mutation)return error(res,409,'output_not_trashable');applyStorageMutation(processing,storage,mutation);const output=processing.getModelOutput(current.id),trash=processing.getTrash(mutation.trashId);repository.audit({actorType:'admin',actorId:req.actorId,action:'output.trashed',entityType:'output',entityId:current.id});res.json({output,trash});});
  router.get('/api/v1/tasks',authorize('viewer.processing.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');const result=processing.listTasksPage({...page,projectId:req.query.projectId||null});res.json({tasks:result.items,nextCursor:result.nextCursor});});
  router.post('/api/v1/tasks',authorize('viewer.processing.write'),mutate,(req,res)=>{const b=req.body||{},p=processing.getProject(b.projectId),d=processing.getDataset(b.datasetId);if(!p||p.status!=='active'||!d||d.status!=='finalized'||d.projectId!==p.id)return error(res,400,'invalid_project_or_dataset');res.status(201).json({task:processing.createTask({...b,createdBy:req.actorId})});});
  router.get('/api/v1/tasks/:id',authorize('viewer.processing.read'),(req,res)=>{const t=processing.getTask(req.params.id);return t?res.json({task:{...t,latestAttempt:processing.latestAttempt(t.id)}}):error(res,404,'task_not_found');});
  router.get('/api/v1/tasks/:id/storage',authorize('viewer.processing.read'),(req,res)=>{const page=pageQuery(req);if(!page)return error(res,400,'invalid_page');const result=processing.taskStorage(req.params.id,page);return result?res.json(result):error(res,404,'task_not_found');});
  router.patch('/api/v1/tasks/:id',authorize('viewer.processing.write'),mutate,(req,res)=>{if(!onlyKeys(req.body,['displayName','description','metadata']))return error(res,400,'invalid_patch_fields');const task=processing.updateTaskMetadata(req.params.id,req.body);return task?res.json({task}):error(res,404,'task_not_found');});
  router.post('/api/v1/tasks/:id/archive',authorize('viewer.processing.write'),mutate,(req,res)=>{const task=processing.archiveTask(req.params.id);return task?res.json({task}):error(res,409,'task_not_archivable');});
  router.use('/api/v1/tasks/:id/attempts',(req,res,next)=>req.method==='POST'&&!processing.workerStatus().live?error(res,503,'processing_worker_unavailable'):next());
  router.post('/api/v1/tasks/:id/attempts',authorize('viewer.processing.write'),mutate,(req,res)=>{try{const p=processing.getProvider(req.body?.providerId);if(!p||!p.enabled)return error(res,409,'provider_not_enabled');if(!Array.isArray(p.capabilities?.options)||!p.capabilityFingerprint)return error(res,409,'provider_capabilities_required');const preset=req.body?.presetId?processing.getPreset(req.body.presetId):null;if(req.body?.presetId&&!preset)return error(res,400,'invalid_preset');if(preset&&((preset.providerType&&preset.providerType!==p.type)||(preset.capabilityFingerprint&&preset.capabilityFingerprint!==p.capabilityFingerprint)))return error(res,409,'stale_preset_capabilities');const userOptions=req.body?.options||{},required=['pc-ept','gltf','3d-tiles'];if(required.some((name)=>Object.hasOwn(userOptions,name)&&userOptions[name]!==true))return error(res,400,'required_output_cannot_be_disabled');const options={...(preset?.options||{}),...userOptions},byName=new Map(p.capabilities.options.map((o)=>[o.name,o]));if(required.some((name)=>!byName.has(name)))return error(res,409,'provider_missing_viewer_outputs');for(const name of required)options[name]=true;const invalid=validateProviderOptions(options,byName);if(invalid)return error(res,400,invalid);const task=processing.getTask(req.params.id),dataset=task&&processing.getDataset(task.datasetId);if(!task||!dataset||dataset.projectId!==task.projectId)return error(res,409,'task_dataset_project_mismatch');const attempt=processing.createAttempt({taskId:req.params.id,providerId:p.id,presetId:preset?.id,options,capabilityFingerprint:p.capabilityFingerprint,createdBy:req.actorId});res.status(202).json({attempt});}catch(e){return error(res,409,'attempt_not_created');}});
  router.get('/api/v1/attempts/:id',authorize('viewer.processing.read'),(req,res)=>{const a=processing.getAttempt(req.params.id);return a?res.json({attempt:a,logs:processing.listLogs(a.id,req.query.logLimit)}):error(res,404,'attempt_not_found');});
  router.post('/api/v1/attempts/:id/cancel',authorize('viewer.processing.write'),mutate,async(req,res)=>{const a=processing.getAttempt(req.params.id);if(!a)return error(res,404,'attempt_not_found');const cancelled=processing.cancelAttempt(a.id);if(a.providerTaskId&&['queued_upstream','running'].includes(a.status)){try{const p=processing.getProvider(a.providerId);if(p)await new NodeOdmProvider({endpoint:p.endpoint,token:providerCredentials.resolve(p.id),providerType:p.type,...(providerFetch?{fetchImpl:providerFetch}:{})}).cancel(a.providerTaskId);}catch(e){processing.appendLog(a.id,'warning',`Upstream cancellation could not be confirmed: ${sanitizeLogMessage(e.message)}`);}}res.json({attempt:cancelled});});
  router.post('/api/v1/attempts/:id/retry',authorize('viewer.processing.write'),mutate,(req,res)=>{const a=processing.retryAttempt(req.params.id,req.actorId);return a?res.status(202).json({attempt:a}):error(res,409,'attempt_not_retryable');});
  router.post('/api/v1/attempts/:id/publish',authorize('viewer.processing.publish'),mutate,(req,res)=>{const a=processing.getAttempt(req.params.id);if(!a||a.status!=='ready_for_review'||!a.resultModelId||!a.resultModelVersionId)return error(res,409,'attempt_not_reviewable');const selected=req.body?.selectedAssetKinds;if(!Array.isArray(selected)||!selected.length||selected.some((k)=>!publicDerivativeKind(k)))return error(res,400,'invalid_published_assets');const candidate=repository.getModelVersion(a.resultModelId,a.resultModelVersionId),available=new Set(candidate?.activeVersion?.assets.map((x)=>x.kind)||[]);if(selected.some((k)=>!available.has(k)))return error(res,400,'published_asset_unavailable');const model=repository.publishModelVersion(a.resultModelId,a.resultModelVersionId,selected);if(!model)return error(res,409,'asset_integrity_not_ready');const task=processing.publishAttempt(a.id,model.id);res.json({task,model});});
  mountGcpRoutes(router,{repository,processing,storage,authorize,mutate,error});
  return router;
}

function pathName(value){const parts=String(value||'Imported dataset').split('/');return parts[parts.length-1]||'Imported dataset';}
module.exports={PERMISSIONS,createProcessingApi,validUnits,publicStorageSpace,publicImportPreview};
