'use strict';

const crypto = require('node:crypto');
const path = require('node:path');
const { sanitizeLogMessage } = require('./processingSecurity');
const { odmGcpList } = require('./gcpOdm');

const BUILT_IN_PRESETS = [
  ['standard', 'Standard', { 'feature-quality': 'high', 'pc-quality': 'medium' }],
  ['high-quality', 'High Quality', { 'feature-quality': 'ultra', 'pc-quality': 'high' }],
  ['quick-preview', 'Quick Preview', { 'fast-orthophoto': true, 'pc-quality': 'low' }],
  ['orthophoto', 'Orthophoto Focused', { 'orthophoto-resolution': 2, 'skip-3dmodel': true }],
  ['model-3d', '3D Model Focused', { 'mesh-octree-depth': 12, 'pc-quality': 'high' }],
  ['custom', 'Custom', {}],
];

function now() { return new Date().toISOString(); }
function json(value, fallback = {}) { try { return JSON.parse(value); } catch { return fallback; } }
function bounded(value, max = 240) { return String(value || '').trim().slice(0, max); }
function decodeCursor(cursor) {
  if (!cursor) return null;
  try {
    const value = JSON.parse(Buffer.from(String(cursor), 'base64url').toString('utf8'));
    return typeof value?.createdAt === 'string' && typeof value?.id === 'string' ? value : null;
  } catch { return null; }
}
function encodeCursor(row) {
  return Buffer.from(JSON.stringify({ createdAt: row.created_at, id: row.id })).toString('base64url');
}
function pageLimit(value) { return Math.max(1, Math.min(Number(value) || 50, 100)); }
function normalizedTags(value, fallback = []) {
  if (value === undefined) return fallback;
  if (!Array.isArray(value) || value.length > 50) throw Object.assign(new Error('tags must be an array of at most 50 strings'), { code:'invalid_tags' });
  const tags=[]; const seen=new Set();
  for (const raw of value) { if(typeof raw!=='string')throw Object.assign(new Error('tags must be strings'),{code:'invalid_tags'});const tag=raw.trim();if(!tag||tag.length>64)throw Object.assign(new Error('tags must contain 1 to 64 characters'),{code:'invalid_tags'});const key=tag.toLocaleLowerCase('en-US');if(!seen.has(key)){seen.add(key);tags.push(tag);} }
  return tags;
}
function finiteOrNull(value) { const number=Number(value);return value!==null&&value!==''&&Number.isFinite(number)?number:null; }
function positiveIntegerOrNull(value) { const number=Number(value);return Number.isSafeInteger(number)&&number>0?number:null; }
function inferredMimeType(file) {
  if(typeof file.contentType==='string'&&file.contentType.trim())return file.contentType.trim().toLowerCase();
  const extension=path.extname(String(file.relativePath||'')).toLowerCase();
  return ({'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.tif':'image/tiff','.tiff':'image/tiff','.dng':'image/x-adobe-dng','.heic':'image/heic','.csv':'text/csv','.geojson':'application/geo+json','.json':'application/json','.txt':'text/plain'})[extension]||null;
}
function indexedFileMetadata(file) {
  const metadata=file.metadata&&typeof file.metadata==='object'?file.metadata:{},gps=metadata.gps&&typeof metadata.gps==='object'?metadata.gps:{};
  return {mimeType:inferredMimeType(file),capturedAt:typeof metadata.capturedAt==='string'?metadata.capturedAt:null,
    latitude:finiteOrNull(gps.latitude),longitude:finiteOrNull(gps.longitude),altitudeM:finiteOrNull(gps.altitudeM),
    width:positiveIntegerOrNull(metadata.width),height:positiveIntegerOrNull(metadata.height)};
}

class ProcessingRepository {
  constructor(database, { logMaxBytes = 10 * 1024 * 1024 } = {}) {
    this.database = database;
    this.logMaxBytes = logMaxBytes;
    this.seedPresets();
  }

  transaction(fn) {
    this.database.exec('BEGIN IMMEDIATE');
    try { const result = fn(); this.database.exec('COMMIT'); return result; }
    catch (error) { this.database.exec('ROLLBACK'); throw error; }
  }

  seedPresets() {
    const insert = this.database.prepare(`INSERT OR IGNORE INTO processing_presets
      (id,display_name,options_json,built_in,enabled,created_at,updated_at) VALUES (?,?,?,?,?,?,?)`);
    const timestamp = now();
    for (const [id, name, options] of BUILT_IN_PRESETS)
      insert.run(id, name, JSON.stringify(options), 1, 1, timestamp, timestamp);
  }

  project(row) {
    if (!row) return null;
    return { id: row.id, displayName: row.display_name, description: row.description, tags: json(row.tags_json,[]), metadata: json(row.metadata_json),
      defaultUnits: row.default_units, status: row.status, createdBy: row.created_by, createdAt: row.created_at,
      updatedAt: row.updated_at, archivedAt: row.archived_at };
  }
  createProject(input) {
    const id = input.id || crypto.randomUUID(); const timestamp = now(),displayName=bounded(input.displayName),tags=normalizedTags(input.tags);
    if(!displayName)throw Object.assign(new Error('display name is required'),{code:'display_name_required'});
    if(this.database.prepare("SELECT 1 FROM projects WHERE status='active' AND display_name=? COLLATE NOCASE").get(displayName))throw Object.assign(new Error('an active project already uses this name'),{code:'project_name_conflict'});
    this.database.prepare(`INSERT INTO projects(id,display_name,description,metadata_json,default_units,status,created_by,created_at,updated_at)
      VALUES (?,?,?,?,?,'active',?,?,?)`).run(id, displayName, bounded(input.description, 4000) || null,
      JSON.stringify(input.metadata || {}), input.defaultUnits || 'imperial', input.createdBy || null, timestamp, timestamp);
    this.database.prepare('UPDATE projects SET tags_json=? WHERE id=?').run(JSON.stringify(tags),id);
    return this.getProject(id);
  }
  getProject(id) { return this.project(this.database.prepare('SELECT * FROM projects WHERE id=?').get(id)); }
  listProjectsPage({limit=50,cursor=null}={}) { const n=pageLimit(limit),c=decodeCursor(cursor);const rows=c?this.database.prepare('SELECT * FROM projects WHERE created_at<? OR (created_at=? AND id<?) ORDER BY created_at DESC,id DESC LIMIT ?').all(c.createdAt,c.createdAt,c.id,n+1):this.database.prepare('SELECT * FROM projects ORDER BY created_at DESC,id DESC LIMIT ?').all(n+1);const more=rows.length>n,items=rows.slice(0,n);return{items:items.map((r)=>this.project(r)),nextCursor:more?encodeCursor(items.at(-1)):null}; }
  listProjects() { return this.listProjectsPage({limit:100}).items; }
  updateProject(id, input) {
    const current = this.getProject(id); if (!current) return null;
    const displayName=bounded(input.displayName ?? current.displayName);if(!displayName)throw Object.assign(new Error('display name is required'),{code:'display_name_required'});
    if(this.database.prepare("SELECT 1 FROM projects WHERE id<>? AND status='active' AND display_name=? COLLATE NOCASE").get(id,displayName))throw Object.assign(new Error('an active project already uses this name'),{code:'project_name_conflict'});
    this.database.prepare(`UPDATE projects SET display_name=?,description=?,tags_json=?,metadata_json=?,default_units=?,updated_at=? WHERE id=?`).run(
      displayName, bounded(input.description ?? current.description, 4000) || null, JSON.stringify(normalizedTags(input.tags,current.tags)),
      JSON.stringify(input.metadata ?? current.metadata), input.defaultUnits || current.defaultUnits, now(), id);
    return this.getProject(id);
  }
  archiveProject(id) {
    const timestamp = now(), active=this.database.prepare("SELECT COUNT(*) AS count FROM processing_tasks WHERE project_id=? AND status IN ('queued','processing')").get(id)?.count||0;
    if(active)return null;
    const changed=this.database.prepare("UPDATE projects SET status='archived',archived_at=?,updated_at=? WHERE id=? AND status='active'").run(timestamp, timestamp, id);
    if(!changed.changes)return null;
    return this.getProject(id);
  }

  dataset(row, includeFiles = false) {
    if (!row) return null;
    const result = { id: row.id, projectId: row.project_id, displayName: row.display_name, description: row.description,
      sourceType: row.source_type, storageMode: row.storage_mode, rootKey: row.root_key, relativePath: row.relative_path,
      status: row.status, manifestSha256: row.manifest_sha256, fileCount: row.file_count, byteSize: row.byte_size,
      tags: json(row.tags_json,[]), metadata: json(row.metadata_json), createdBy: row.created_by, createdAt: row.created_at, updatedAt: row.updated_at,
      finalizedAt: row.finalized_at, archivedAt: row.archived_at, trashedAt: row.trashed_at };
    if (includeFiles) result.files = this.database.prepare('SELECT * FROM dataset_files WHERE dataset_id=? ORDER BY relative_path').all(row.id).map((f) => ({
      id: f.id, relativePath: f.relative_path, byteSize: f.byte_size, sha256: f.sha256, contentType: f.content_type,
      mimeType:f.mime_type,capturedAt:f.captured_at,latitude:f.latitude,longitude:f.longitude,altitudeM:f.altitude_m,
      width:f.width,height:f.height,metadata: json(f.metadata_json), createdAt: f.created_at,
    }));
    return result;
  }
  createDataset(input) {
    const id = input.id || crypto.randomUUID(); const timestamp = now(),displayName=bounded(input.displayName),tags=normalizedTags(input.tags);
    if(!displayName)throw Object.assign(new Error('display name is required'),{code:'display_name_required'});
    if(input.projectId&&this.database.prepare("SELECT 1 FROM datasets WHERE project_id=? AND status<>'trashed' AND display_name=? COLLATE NOCASE").get(input.projectId,displayName))throw Object.assign(new Error('the project already has a dataset with this name'),{code:'dataset_name_conflict'});
    this.database.prepare(`INSERT INTO datasets(id,project_id,display_name,description,source_type,storage_mode,root_key,relative_path,status,metadata_json,created_by,created_at,updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id, input.projectId || null, displayName, bounded(input.description, 4000) || null,
      bounded(input.sourceType || 'upload', 40), input.storageMode || 'managed', bounded(input.rootKey, 40),
      bounded(input.relativePath || id, 1000), input.status || 'draft', JSON.stringify(input.metadata || {}), input.createdBy || null, timestamp, timestamp);
    this.database.prepare('UPDATE datasets SET tags_json=? WHERE id=?').run(JSON.stringify(tags),id);
    return this.getDataset(id);
  }
  getDataset(id, includeFiles = false) { return this.dataset(this.database.prepare('SELECT * FROM datasets WHERE id=?').get(id), includeFiles); }
  listDatasets(projectId) {
    return this.listDatasetsPage({projectId,limit:100}).items;
  }
  listDatasetsPage({projectId=null,limit=50,cursor=null}={}) { const n=pageLimit(limit),c=decodeCursor(cursor);let rows;if(projectId&&c)rows=this.database.prepare('SELECT * FROM datasets WHERE project_id=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,c.createdAt,c.createdAt,c.id,n+1);else if(projectId)rows=this.database.prepare('SELECT * FROM datasets WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,n+1);else if(c)rows=this.database.prepare('SELECT * FROM datasets WHERE created_at<? OR (created_at=? AND id<?) ORDER BY created_at DESC,id DESC LIMIT ?').all(c.createdAt,c.createdAt,c.id,n+1);else rows=this.database.prepare('SELECT * FROM datasets ORDER BY created_at DESC,id DESC LIMIT ?').all(n+1);const more=rows.length>n,items=rows.slice(0,n);return{items:items.map((r)=>this.dataset(r)),nextCursor:more?encodeCursor(items.at(-1)):null}; }
  updateDatasetMetadata(id, input) {
    const current = this.getDataset(id); if (!current || current.status === 'trashed') return null;
    const displayName=bounded(input.displayName ?? current.displayName),projectId=input.projectId??current.projectId;
    if(!displayName)throw Object.assign(new Error('display name is required'),{code:'display_name_required'});
    if(projectId!==current.projectId){const target=this.getProject(projectId);if(!target||target.status!=='active'||['finalizing','trashed'].includes(current.status)||this.activeDatasetOperations(id)>0||this.datasetReferences(id)>0)throw Object.assign(new Error('dataset cannot be reassociated while in use or to an inactive project'),{code:'dataset_reassociation_blocked'});}
    if(this.database.prepare("SELECT 1 FROM datasets WHERE id<>? AND project_id=? AND status<>'trashed' AND display_name=? COLLATE NOCASE").get(id,projectId,displayName))throw Object.assign(new Error('the target project already has a dataset with this name'),{code:'dataset_name_conflict'});
    this.database.prepare('UPDATE datasets SET display_name=?,description=?,tags_json=?,metadata_json=?,project_id=?,updated_at=? WHERE id=?').run(
      displayName, bounded(input.description ?? current.description, 4000) || null,JSON.stringify(normalizedTags(input.tags,current.tags)),
      JSON.stringify(input.metadata ?? current.metadata), projectId, now(), id);
    return this.getDataset(id);
  }
  finalizeDataset(id, files, manifestSha256) {
    return this.transaction(() => {
      const current = this.getDataset(id); if (!current || !['draft', 'finalizing'].includes(current.status)) throw new Error('dataset is not finalizable');
      this.database.prepare('DELETE FROM dataset_files WHERE dataset_id=?').run(id);
      const insert = this.database.prepare(`INSERT INTO dataset_files(id,dataset_id,relative_path,byte_size,sha256,content_type,metadata_json,created_at,
        mime_type,captured_at,latitude,longitude,altitude_m,width,height) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
      const timestamp = now(); let bytes = 0;
      for (const file of files) { const indexed=indexedFileMetadata(file);bytes += file.byteSize; insert.run(file.id || crypto.randomUUID(), id, file.relativePath, file.byteSize, file.sha256, file.contentType || null, JSON.stringify(file.metadata || {}), timestamp,
        indexed.mimeType,indexed.capturedAt,indexed.latitude,indexed.longitude,indexed.altitudeM,indexed.width,indexed.height); }
      this.database.prepare(`UPDATE datasets SET status='finalized',manifest_sha256=?,file_count=?,byte_size=?,finalized_at=?,updated_at=? WHERE id=?`).run(
        manifestSha256, files.length, bytes, timestamp, timestamp, id);
      return this.getDataset(id, true);
    });
  }
  activeDatasetOperations(id){const operations=Number(this.database.prepare("SELECT COUNT(*) AS count FROM dataset_operations WHERE dataset_id=? AND status IN ('queued','leased')").get(id)?.count||0),mutations=Number(this.database.prepare("SELECT COUNT(*) AS count FROM storage_mutations WHERE entity_type='dataset' AND entity_id=? AND status IN ('intent','fs_applied','failed')").get(id)?.count||0);return operations+mutations;}
  archiveDataset(id) { if(this.activeDatasetOperations(id))return null;const t=now(),changed=this.database.prepare("UPDATE datasets SET status='archived',archived_at=?,updated_at=? WHERE id=? AND status='finalized'").run(t,t,id);return changed.changes?this.getDataset(id):null; }
  datasetReferences(id){return this.database.prepare("SELECT COUNT(*) AS count FROM processing_tasks WHERE dataset_id=? AND status<>'archived'").get(id).count;}
  trashDataset(id,{trashRelative,actor}){return this.transaction(()=>{const dataset=this.getDataset(id);if(!dataset||dataset.storageMode!=='external_reference'||!['draft','finalized','archived'].includes(dataset.status)||this.datasetReferences(id)>0||this.activeDatasetOperations(id)>0)return null;const t=now(),trashId=crypto.randomUUID(),changed=this.database.prepare("UPDATE datasets SET status='trashed',trashed_at=?,updated_at=? WHERE id=? AND status=?").run(t,t,id,dataset.status);if(changed.changes!==1)return null;this.database.prepare('INSERT INTO storage_trash(id,entity_type,entity_id,root_key,relative_path,byte_size,purge_after,created_by,created_at) VALUES (?,\'dataset\',?,?,?,?,?,?,?)').run(trashId,id,dataset.rootKey,trashRelative||'',dataset.byteSize,new Date(Date.now()+14*86400_000).toISOString(),actor,t);return this.getTrash(trashId);});}
  getTrash(id){const r=this.database.prepare('SELECT * FROM storage_trash WHERE id=?').get(id);return r&&{id:r.id,entityType:r.entity_type,entityId:r.entity_id,rootKey:r.root_key,relativePath:r.relative_path,byteSize:r.byte_size,purgeAfter:r.purge_after,createdBy:r.created_by,createdAt:r.created_at,permanentlyDeletedAt:r.permanently_deleted_at};}
  listTrash(){return this.database.prepare('SELECT * FROM storage_trash WHERE permanently_deleted_at IS NULL ORDER BY created_at DESC').all().map((r)=>this.getTrash(r.id));}
  listTrashPage({limit=50,cursor=null}={}){const n=pageLimit(limit),c=decodeCursor(cursor),rows=c?this.database.prepare('SELECT * FROM storage_trash WHERE permanently_deleted_at IS NULL AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT ?').all(c.createdAt,c.createdAt,c.id,n+1):this.database.prepare('SELECT * FROM storage_trash WHERE permanently_deleted_at IS NULL ORDER BY created_at DESC,id DESC LIMIT ?').all(n+1),more=rows.length>n,items=rows.slice(0,n),totals=this.database.prepare('SELECT COUNT(*) AS totalCount,COALESCE(SUM(byte_size),0) AS totalBytes FROM storage_trash WHERE permanently_deleted_at IS NULL').get();return{items:items.map((r)=>this.getTrash(r.id)),nextCursor:more?encodeCursor(items.at(-1)):null,totalCount:totals.totalCount,totalBytes:totals.totalBytes};}
  restoreTrash(id){const item=this.getTrash(id),dataset=item&&this.getDataset(item.entityId);if(!item||item.permanentlyDeletedAt||dataset?.storageMode!=='external_reference')return null;const t=now();return this.transaction(()=>{const changed=this.database.prepare("UPDATE datasets SET status='archived',trashed_at=NULL,updated_at=? WHERE id=? AND status='trashed'").run(t,item.entityId);if(changed.changes!==1)return null;this.database.prepare('UPDATE storage_trash SET permanently_deleted_at=? WHERE id=? AND permanently_deleted_at IS NULL').run(t,id);return this.getDataset(item.entityId);});}
  markTrashPurged(id){const item=this.getTrash(id),dataset=item&&this.getDataset(item.entityId);if(!item||item.permanentlyDeletedAt||dataset?.storageMode!=='external_reference')return null;const t=now(),changed=this.database.prepare('UPDATE storage_trash SET permanently_deleted_at=? WHERE id=? AND permanently_deleted_at IS NULL').run(t,id);return changed.changes===1?this.getTrash(id):null;}
  expiredTrash(at=Date.now()){return this.database.prepare('SELECT * FROM storage_trash WHERE permanently_deleted_at IS NULL AND purge_after<=?').all(new Date(at).toISOString()).map((r)=>this.getTrash(r.id));}

  storageMutation(row){return row?{id:row.id,type:row.mutation_type,entityType:row.entity_type,entityId:row.entity_id,trashId:row.trash_id,sourceRootKey:row.source_root_key,sourceRelativePath:row.source_relative_path,destinationRootKey:row.destination_root_key,destinationRelativePath:row.destination_relative_path,allowAbsentSource:Boolean(row.allow_absent_source),status:row.status,actor:row.actor,errorCode:row.error_code,errorMessage:row.error_message,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at}:null;}
  getStorageMutation(id){return this.storageMutation(this.database.prepare('SELECT * FROM storage_mutations WHERE id=?').get(id));}
  pendingStorageMutations(limit=20){return this.database.prepare("SELECT * FROM storage_mutations WHERE status IN ('intent','fs_applied') ORDER BY created_at,id LIMIT ?").all(Math.max(1,Math.min(Number(limit)||20,100))).map((row)=>this.storageMutation(row));}
  listStorageMutationsPage({status=null,limit=50,cursor=null}={}){const n=pageLimit(limit),c=decodeCursor(cursor),allowed=['intent','fs_applied','complete','failed'];if(status&&!allowed.includes(status))throw Object.assign(new Error('invalid lifecycle status'),{code:'invalid_status'});let rows;if(status&&c)rows=this.database.prepare('SELECT * FROM storage_mutations WHERE status=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT ?').all(status,c.createdAt,c.createdAt,c.id,n+1);else if(status)rows=this.database.prepare('SELECT * FROM storage_mutations WHERE status=? ORDER BY created_at DESC,id DESC LIMIT ?').all(status,n+1);else if(c)rows=this.database.prepare('SELECT * FROM storage_mutations WHERE created_at<? OR (created_at=? AND id<?) ORDER BY created_at DESC,id DESC LIMIT ?').all(c.createdAt,c.createdAt,c.id,n+1);else rows=this.database.prepare('SELECT * FROM storage_mutations ORDER BY created_at DESC,id DESC LIMIT ?').all(n+1);const more=rows.length>n,items=rows.slice(0,n);return{items:items.map((row)=>this.storageMutation(row)),nextCursor:more?encodeCursor(items.at(-1)):null};}
  storageMutationSummary(){return this.database.prepare("SELECT status,COUNT(*) AS count FROM storage_mutations GROUP BY status").all();}
  beginTrashMutation(datasetId,actor){return this.transaction(()=>{const existing=this.database.prepare("SELECT * FROM storage_mutations WHERE entity_type='dataset' AND entity_id=? AND status IN ('intent','fs_applied') ORDER BY created_at LIMIT 1").get(datasetId);if(existing)return existing.mutation_type==='trash'?this.storageMutation(existing):null;const dataset=this.getDataset(datasetId);if(!dataset||dataset.storageMode==='external_reference'||dataset.rootKey!=='datasets'||dataset.status==='trashed'||this.datasetReferences(datasetId)>0||this.activeDatasetOperations(datasetId)>0)return null;const id=crypto.randomUUID(),trashId=crypto.randomUUID(),t=now(),trashRelative=`dataset/${datasetId}-${trashId}`,allowAbsent=dataset.status==='draft'&&dataset.fileCount===0;this.database.prepare("INSERT INTO storage_mutations(id,mutation_type,entity_type,entity_id,trash_id,source_root_key,source_relative_path,destination_root_key,destination_relative_path,allow_absent_source,status,actor,created_at,updated_at) VALUES (?,'trash','dataset',?,?,?,?,'trash',?,?,'intent',?,?,?)").run(id,datasetId,trashId,dataset.rootKey,dataset.relativePath,trashRelative,allowAbsent?1:0,actor||null,t,t);return this.getStorageMutation(id);});}
  beginOutputTrashMutation(outputId,actor){return this.transaction(()=>{const existing=this.database.prepare("SELECT * FROM storage_mutations WHERE entity_type='output' AND entity_id=? AND status IN ('intent','fs_applied') ORDER BY created_at LIMIT 1").get(outputId);if(existing)return existing.mutation_type==='trash'?this.storageMutation(existing):null;const output=this.getModelOutput(outputId);if(!output||output.status!=='archived'||this.outputInUse(output))return null;const row=this.database.prepare('SELECT * FROM model_outputs WHERE id=?').get(outputId);if(row.root_key!=='models')return null;const id=crypto.randomUUID(),trashId=crypto.randomUUID(),t=now(),trashRelative=`model-output/${outputId}-${trashId}`;this.database.prepare("INSERT INTO storage_mutations(id,mutation_type,entity_type,entity_id,trash_id,source_root_key,source_relative_path,destination_root_key,destination_relative_path,status,actor,created_at,updated_at) VALUES (?,'trash','output',?,?,? ,?,'trash',?,'intent',?,?,?)").run(id,outputId,trashId,row.root_key,row.relative_path,trashRelative,actor||null,t,t);return this.getStorageMutation(id);});}
  beginRestoreMutation(trashId,actor){return this.transaction(()=>{const item=this.getTrash(trashId);if(!item||item.permanentlyDeletedAt)return null;const existing=this.database.prepare("SELECT * FROM storage_mutations WHERE entity_type=? AND entity_id=? AND status IN ('intent','fs_applied') ORDER BY created_at LIMIT 1").get(item.entityType,item.entityId);if(existing)return existing.mutation_type==='restore'&&existing.trash_id===trashId?this.storageMutation(existing):null;let rootKey,relativePath,allowAbsent=0;if(item.entityType==='dataset'){const dataset=this.getDataset(item.entityId);if(!dataset||dataset.storageMode==='external_reference'||dataset.rootKey!=='datasets'||dataset.status!=='trashed'||this.activeDatasetOperations(dataset.id)>0)return null;rootKey=dataset.rootKey;relativePath=dataset.relativePath;allowAbsent=item.relativePath===''?1:0;}else if(item.entityType==='output'){const row=this.database.prepare('SELECT * FROM model_outputs WHERE id=?').get(item.entityId);if(!row||row.status!=='trashed'||row.root_key!=='models')return null;rootKey=row.root_key;relativePath=row.relative_path;}else return null;const id=crypto.randomUUID(),t=now();this.database.prepare("INSERT INTO storage_mutations(id,mutation_type,entity_type,entity_id,trash_id,source_root_key,source_relative_path,destination_root_key,destination_relative_path,allow_absent_source,status,actor,created_at,updated_at) VALUES (?,'restore',?,?,?,'trash',?,?,?,?,'intent',?,?,?)").run(id,item.entityType,item.entityId,item.id,item.relativePath,rootKey,relativePath,allowAbsent,actor||null,t,t);return this.getStorageMutation(id);});}
  beginPurgeMutation(trashId,actor){return this.transaction(()=>{const item=this.getTrash(trashId);if(!item||item.permanentlyDeletedAt)return null;const existing=this.database.prepare("SELECT * FROM storage_mutations WHERE entity_type=? AND entity_id=? AND status IN ('intent','fs_applied') ORDER BY created_at LIMIT 1").get(item.entityType,item.entityId);if(existing)return existing.mutation_type==='purge'&&existing.trash_id===trashId?this.storageMutation(existing):null;if(item.entityType==='dataset'){const dataset=this.getDataset(item.entityId);if(!dataset||dataset.storageMode==='external_reference'||dataset.rootKey!=='datasets'||dataset.status!=='trashed'||this.activeDatasetOperations(dataset.id)>0)return null;}else if(item.entityType==='output'){const output=this.getModelOutput(item.entityId);if(!output||output.status!=='trashed')return null;}else return null;const id=crypto.randomUUID(),t=now();this.database.prepare("INSERT INTO storage_mutations(id,mutation_type,entity_type,entity_id,trash_id,source_root_key,source_relative_path,status,actor,created_at,updated_at) VALUES (?,'purge',?,?,?,'trash',?,'intent',?,?,?)").run(id,item.entityType,item.entityId,item.id,item.relativePath,actor||null,t,t);return this.getStorageMutation(id);});}
  retryStorageMutation(id){return this.transaction(()=>{const mutation=this.getStorageMutation(id);if(!mutation||mutation.status!=='failed')return null;const active=this.database.prepare("SELECT id FROM storage_mutations WHERE entity_type=? AND entity_id=? AND status IN ('intent','fs_applied') LIMIT 1").get(mutation.entityType,mutation.entityId);if(active)return null;const t=now(),changed=this.database.prepare("UPDATE storage_mutations SET status='intent',error_code=NULL,error_message=NULL,completed_at=NULL,updated_at=? WHERE id=? AND status='failed'").run(t,id);return changed.changes===1?this.getStorageMutation(id):null;});}
  markStorageMutationFsApplied(id,{destinationRelativePath}={}){const t=now();const changed=destinationRelativePath===undefined?this.database.prepare("UPDATE storage_mutations SET status='fs_applied',updated_at=? WHERE id=? AND status IN ('intent','fs_applied')").run(t,id):this.database.prepare("UPDATE storage_mutations SET status='fs_applied',destination_relative_path=?,updated_at=? WHERE id=? AND status IN ('intent','fs_applied')").run(destinationRelativePath,t,id);return changed.changes===1?this.getStorageMutation(id):null;}
  failStorageMutation(id,code,message){const t=now(),safe=sanitizeLogMessage(message).slice(0,1000);this.database.prepare("UPDATE storage_mutations SET status='failed',error_code=?,error_message=?,completed_at=?,updated_at=? WHERE id=? AND status IN ('intent','fs_applied')").run(bounded(code,80),safe,t,t,id);return this.getStorageMutation(id);}
  completeStorageMutation(id){return this.transaction(()=>{const mutation=this.getStorageMutation(id);if(!mutation)return null;if(mutation.status==='complete')return mutation;if(mutation.status!=='fs_applied')return null;const t=now();if(mutation.type==='trash'){if(mutation.entityType==='dataset'){const dataset=this.getDataset(mutation.entityId);if(!dataset)return null;this.database.prepare("UPDATE datasets SET status='trashed',trashed_at=?,updated_at=? WHERE id=?").run(t,t,dataset.id);this.database.prepare("INSERT OR IGNORE INTO storage_trash(id,entity_type,entity_id,root_key,relative_path,byte_size,purge_after,created_by,created_at) VALUES (?,'dataset',?,?,?,?,?,?,?)").run(mutation.trashId,dataset.id,dataset.rootKey,mutation.destinationRelativePath||'',dataset.byteSize,new Date(Date.now()+14*86400_000).toISOString(),mutation.actor,t);}else{const output=this.getModelOutput(mutation.entityId);if(!output)return null;this.database.prepare("UPDATE model_outputs SET status='trashed',trashed_at=?,updated_at=? WHERE id=? AND status='archived'").run(t,t,output.id);this.database.prepare("INSERT OR IGNORE INTO storage_trash(id,entity_type,entity_id,root_key,relative_path,byte_size,purge_after,created_by,created_at) VALUES (?,'output',?,?,?,?,?,?,?)").run(mutation.trashId,output.id,'models',mutation.destinationRelativePath,output.byteSize,new Date(Date.now()+14*86400_000).toISOString(),mutation.actor,t);}}else if(mutation.type==='restore'){if(mutation.entityType==='dataset')this.database.prepare("UPDATE datasets SET status='archived',trashed_at=NULL,updated_at=? WHERE id=? AND status='trashed'").run(t,mutation.entityId);else this.database.prepare("UPDATE model_outputs SET status='archived',trashed_at=NULL,updated_at=? WHERE id=? AND status='trashed'").run(t,mutation.entityId);this.database.prepare('UPDATE storage_trash SET permanently_deleted_at=COALESCE(permanently_deleted_at,?) WHERE id=?').run(t,mutation.trashId);}else if(mutation.type==='purge'){if(mutation.entityType==='output'){this.database.prepare('DELETE FROM model_assets WHERE version_id=?').run(mutation.entityId);this.database.prepare("UPDATE model_outputs SET byte_size=0,asset_count=0,updated_at=? WHERE id=?").run(t,mutation.entityId);}this.database.prepare('UPDATE storage_trash SET permanently_deleted_at=COALESCE(permanently_deleted_at,?) WHERE id=?').run(t,mutation.trashId);}this.database.prepare("UPDATE storage_mutations SET status='complete',completed_at=?,updated_at=? WHERE id=? AND status='fs_applied'").run(t,t,id);return this.getStorageMutation(id);});}

  createUpload(input) {
    const id = crypto.randomUUID(); const token = crypto.randomBytes(32).toString('base64url'); const timestamp = now();
    this.database.prepare(`INSERT INTO upload_sessions(id,dataset_id,token_hash,subject,expected_manifest_json,chunk_size,status,expires_at,created_at,updated_at)
      VALUES (?,?,?,?,?,?,'open',?,?,?)`).run(id, input.datasetId, crypto.createHash('sha256').update(token).digest('hex'), input.subject, JSON.stringify(input.files), input.chunkSize,
      input.expiresAt, timestamp, timestamp);
    return { upload: this.getUpload(id), token };
  }
  resumeUpload(datasetId, subject, files, expiresAt) { const expected=JSON.stringify(files),row=this.database.prepare("SELECT * FROM upload_sessions WHERE dataset_id=? AND subject=? AND expected_manifest_json=? AND status='open' AND expires_at>? ORDER BY created_at DESC LIMIT 1").get(datasetId,subject,expected,now());if(!row)return null;const token=crypto.randomBytes(32).toString('base64url'),t=now();this.database.prepare('UPDATE upload_sessions SET token_hash=?,expires_at=?,updated_at=? WHERE id=?').run(crypto.createHash('sha256').update(token).digest('hex'),expiresAt,t,row.id);return{upload:this.getUpload(row.id),token}; }
  getUpload(id) { const r = this.database.prepare('SELECT * FROM upload_sessions WHERE id=?').get(id); return r && { id:r.id,datasetId:r.dataset_id,tokenHash:r.token_hash,subject:r.subject,files:json(r.expected_manifest_json,[]),chunkSize:r.chunk_size,status:r.status,expiresAt:r.expires_at,createdAt:r.created_at,updatedAt:r.updated_at }; }
  verifyUploadToken(upload, token) { return Boolean(upload && token && crypto.timingSafeEqual(Buffer.from(upload.tokenHash), Buffer.from(crypto.createHash('sha256').update(token).digest('hex')))); }
  recordChunk(input) {
    const existing = this.database.prepare('SELECT * FROM upload_chunks WHERE upload_id=? AND file_id=? AND chunk_index=?').get(input.uploadId,input.fileId,input.chunkIndex);
    if (existing) {
      if (existing.sha256 !== input.sha256 || existing.byte_size !== input.byteSize) throw Object.assign(new Error('chunk replay does not match'), { code:'chunk_conflict' });
      return { ...input, replayed:true };
    }
    this.database.prepare(`INSERT INTO upload_chunks(upload_id,file_id,chunk_index,byte_size,sha256,relative_path,created_at) VALUES (?,?,?,?,?,?,?)`).run(
      input.uploadId,input.fileId,input.chunkIndex,input.byteSize,input.sha256,input.relativePath,now());
    return { ...input, replayed:false };
  }
  listChunks(uploadId, fileId) { return this.database.prepare('SELECT * FROM upload_chunks WHERE upload_id=? AND file_id=? ORDER BY chunk_index').all(uploadId,fileId); }
  claimUploadFinalization(id) { const t=now();return this.database.prepare("UPDATE upload_sessions SET status='finalizing',updated_at=? WHERE id=? AND status='open'").run(t,id).changes===1; }
  reopenUpload(id) { this.database.prepare("UPDATE upload_sessions SET status='open',updated_at=? WHERE id=? AND status='finalizing'").run(now(),id); }
  completeUpload(id) { const t=now(); this.database.prepare("UPDATE upload_sessions SET status='complete',updated_at=? WHERE id=?").run(t,id); return this.getUpload(id); }
  expiredUploads(at=Date.now()){return this.database.prepare("SELECT id FROM upload_sessions WHERE status IN ('open','expired','cancelled') AND expires_at<=?").all(new Date(at).toISOString()).map((r)=>r.id);}
  expireUpload(id){this.database.prepare("UPDATE upload_sessions SET status='expired',updated_at=? WHERE id=? AND status IN ('open','finalizing')").run(now(),id);}
  cancelDatasetUploads(datasetId){const ids=this.database.prepare("SELECT id FROM upload_sessions WHERE dataset_id=? AND status IN ('open','finalizing')").all(datasetId).map((r)=>r.id),t=now();this.database.prepare("UPDATE upload_sessions SET status='cancelled',updated_at=? WHERE dataset_id=? AND status IN ('open','finalizing')").run(t,datasetId);return ids;}
  touchUploadFinalization(id){return this.database.prepare("UPDATE upload_sessions SET updated_at=? WHERE id=? AND status='finalizing'").run(now(),id).changes===1;}
  recoverStaleUploadFinalizations(at=Date.now(),maxAgeMs=3600000){return this.database.prepare("UPDATE upload_sessions SET status='open',updated_at=? WHERE status='finalizing' AND updated_at<? AND NOT EXISTS (SELECT 1 FROM dataset_operations o WHERE o.upload_id=upload_sessions.id AND o.status IN ('queued','leased'))").run(new Date(at).toISOString(),new Date(at-maxAgeMs).toISOString()).changes;}

  provider(row) { return row && { id:row.id,type:row.provider_type,displayName:row.display_name,endpoint:row.endpoint,enabled:Boolean(row.enabled),admissionLimit:row.admission_limit,activeAttempts:this.database.prepare("SELECT COUNT(*) AS count FROM processing_attempts WHERE provider_id=? AND status IN ('admitted','initializing','uploading','committed','queued_upstream','running')").get(row.id).count,capabilities:json(row.capabilities_json),capabilityFingerprint:row.capability_fingerprint,lastHealth:row.last_health,lastHealthAt:row.last_health_at,createdAt:row.created_at,updatedAt:row.updated_at }; }
  upsertProvider(input) {
    const id=input.id||crypto.randomUUID(), t=now();
    this.database.prepare(`INSERT INTO processing_providers(id,provider_type,display_name,endpoint,auth_env_key,enabled,admission_limit,created_at,updated_at)
      VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET provider_type=excluded.provider_type,display_name=excluded.display_name,endpoint=excluded.endpoint,auth_env_key=excluded.auth_env_key,enabled=excluded.enabled,admission_limit=excluded.admission_limit,updated_at=excluded.updated_at`).run(
      id,input.type,bounded(input.displayName),String(input.endpoint).replace(/\/+$/,''),input.authEnvKey||null,input.enabled?1:0,input.admissionLimit||1,t,t);
    return this.getProvider(id);
  }
  getProvider(id) { return this.provider(this.database.prepare('SELECT * FROM processing_providers WHERE id=?').get(id)); }
  listProvidersPage({limit=50,cursor=null}={}) { const n=pageLimit(limit),c=decodeCursor(cursor);const rows=c?this.database.prepare('SELECT * FROM processing_providers WHERE created_at<? OR (created_at=? AND id<?) ORDER BY created_at DESC,id DESC LIMIT ?').all(c.createdAt,c.createdAt,c.id,n+1):this.database.prepare('SELECT * FROM processing_providers ORDER BY created_at DESC,id DESC LIMIT ?').all(n+1);const more=rows.length>n,items=rows.slice(0,n);return{items:items.map((r)=>this.provider(r)),nextCursor:more?encodeCursor(items.at(-1)):null}; }
  listProviders() { return this.listProvidersPage({limit:100}).items; }
  updateProviderCapabilities(id,{capabilities,fingerprint,health}) { const t=now(); this.database.prepare('UPDATE processing_providers SET capabilities_json=?,capability_fingerprint=?,last_health=?,last_health_at=?,updated_at=? WHERE id=?').run(JSON.stringify(capabilities||{}),fingerprint||null,health,t,t,id); return this.getProvider(id); }
  listPresets() { return this.database.prepare('SELECT * FROM processing_presets WHERE enabled=1 ORDER BY built_in DESC,display_name').all().map((r)=>({id:r.id,displayName:r.display_name,options:json(r.options_json),providerType:r.provider_type,capabilityFingerprint:r.capability_fingerprint,builtIn:Boolean(r.built_in)})); }
  getPreset(id){return this.listPresets().find((p)=>p.id===id)||null;}

  task(row) { return row && { id:row.id,projectId:row.project_id,datasetId:row.dataset_id,displayName:row.display_name,description:row.description,status:row.status,activeAttemptId:row.active_attempt_id,publishedModelId:row.published_model_id,metadata:json(row.metadata_json),createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,archivedAt:row.archived_at }; }
  createTask(input) { const project=this.getProject(input.projectId),dataset=this.getDataset(input.datasetId);if(!project||project.status!=='active'||!dataset||dataset.status!=='finalized'||dataset.projectId!==project.id)throw Object.assign(new Error('task project and finalized dataset must match'),{code:'invalid_project_or_dataset'});const id=input.id||crypto.randomUUID(),t=now();this.database.prepare(`INSERT INTO processing_tasks(id,project_id,dataset_id,display_name,description,status,metadata_json,created_by,created_at,updated_at) VALUES (?,?,?,?,?,'draft',?,?,?,?)`).run(id,input.projectId,input.datasetId,bounded(input.displayName),bounded(input.description,4000)||null,JSON.stringify(input.metadata||{}),input.createdBy||null,t,t);return this.getTask(id); }
  getTask(id) { return this.task(this.database.prepare('SELECT * FROM processing_tasks WHERE id=?').get(id)); }
  listTasksPage({projectId=null,limit=50,cursor=null}={}) { const n=pageLimit(limit),c=decodeCursor(cursor);let rows;if(projectId&&c)rows=this.database.prepare('SELECT * FROM processing_tasks WHERE project_id=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,c.createdAt,c.createdAt,c.id,n+1);else if(projectId)rows=this.database.prepare('SELECT * FROM processing_tasks WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,n+1);else if(c)rows=this.database.prepare('SELECT * FROM processing_tasks WHERE created_at<? OR (created_at=? AND id<?) ORDER BY created_at DESC,id DESC LIMIT ?').all(c.createdAt,c.createdAt,c.id,n+1);else rows=this.database.prepare('SELECT * FROM processing_tasks ORDER BY created_at DESC,id DESC LIMIT ?').all(n+1);const more=rows.length>n,items=rows.slice(0,n),latest=new Map();if(items.length){const attempts=this.database.prepare(`SELECT * FROM processing_attempts WHERE task_id IN (${items.map(()=>'?').join(',')}) ORDER BY task_id,attempt_number DESC`).all(...items.map((r)=>r.id));for(const row of attempts)if(!latest.has(row.task_id))latest.set(row.task_id,this.attempt(row));}return{items:items.map((r)=>({...this.task(r),latestAttempt:latest.get(r.id)||null})),nextCursor:more?encodeCursor(items.at(-1)):null}; }
  listTasks(projectId) { return this.listTasksPage({projectId,limit:100}).items; }
  attempt(row) { return row && { id:row.id,taskId:row.task_id,attemptNumber:row.attempt_number,providerId:row.provider_id,providerTaskId:row.provider_task_id,presetId:row.preset_id,options:json(row.options_json),capabilityFingerprint:row.capability_fingerprint,status:row.status,progress:row.progress,providerOutputCursor:row.provider_output_cursor,errorCode:row.error_code,errorMessage:row.error_message,resultModelId:row.result_model_id,resultModelVersionId:row.result_model_version_id,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,startedAt:row.started_at,upstreamCompletedAt:row.upstream_completed_at,ingestedAt:row.ingested_at,completedAt:row.completed_at }; }
  createAttempt(input) {
    return this.transaction(()=>{ const task=this.getTask(input.taskId); if(!task||task.status==='archived') throw new Error('task is not processable'); const dataset=this.getDataset(task.datasetId),project=this.getProject(task.projectId);if(!dataset||dataset.status!=='finalized'||dataset.projectId!==task.projectId||!project||project.status!=='active')throw new Error('dataset and project must be active and finalized');const active=task.activeAttemptId&&this.getAttempt(task.activeAttemptId);if(active&&!['failed','cancelled','published'].includes(active.status))throw Object.assign(new Error('task already has an active attempt'),{code:'attempt_in_progress'});
      const n=this.database.prepare('SELECT COALESCE(MAX(attempt_number),0)+1 AS n FROM processing_attempts WHERE task_id=?').get(task.id).n;
      const id=crypto.randomUUID(),t=now(); this.database.prepare(`INSERT INTO processing_attempts(id,task_id,attempt_number,provider_id,provider_task_id,preset_id,options_json,capability_fingerprint,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'pending',?,?,?)`).run(id,task.id,n,input.providerId,input.providerTaskId||crypto.randomUUID(),input.presetId||null,JSON.stringify(input.options||{}),input.capabilityFingerprint||null,input.createdBy||null,t,t);
      const markCount=Number(this.database.prepare('SELECT COUNT(*) count FROM gcp_image_correspondences WHERE task_id=?').get(task.id).count);
      if(markCount>100000)throw Object.assign(new Error('task has too many GCP image correspondences'),{code:'too_many_gcp_correspondences'});
      const marks=this.database.prepare(`SELECT points.longitude,points.latitude,points.elevation_m elevationM,
        marks.pixel_x pixelX,marks.pixel_y pixelY,files.relative_path relativePath
        FROM gcp_image_correspondences marks
        JOIN gcp_points points ON points.id=marks.gcp_point_id
        JOIN dataset_files files ON files.id=marks.dataset_file_id
        WHERE marks.task_id=? ORDER BY points.external_id,files.relative_path,marks.id`).all(task.id);
      const gcpList=odmGcpList(marks);
      if(gcpList&&Buffer.byteLength(gcpList)>16*1024*1024)throw Object.assign(new Error('generated ODM GCP input is too large'),{code:'gcp_snapshot_too_large'});
      if(gcpList)this.database.prepare(`INSERT INTO processing_attempt_gcp_snapshots(attempt_id,sha256,content_text,correspondence_count,created_at)
        VALUES (?,?,?,?,?)`).run(id,crypto.createHash('sha256').update(gcpList).digest('hex'),gcpList,marks.length,t);
      this.database.prepare(`INSERT INTO processing_jobs(id,attempt_id,job_type,status,available_at,created_at,updated_at) VALUES (?,?,'submit','pending',?,?,?)`).run(crypto.randomUUID(),id,t,t,t);
      this.database.prepare("UPDATE processing_tasks SET active_attempt_id=?,status='queued',updated_at=? WHERE id=?").run(id,t,task.id); return this.getAttempt(id); });
  }
  getAttempt(id) { return this.attempt(this.database.prepare('SELECT * FROM processing_attempts WHERE id=?').get(id)); }
  getAttemptGcpSnapshot(id){const row=this.database.prepare('SELECT * FROM processing_attempt_gcp_snapshots WHERE attempt_id=?').get(id);return row?{attemptId:row.attempt_id,sha256:row.sha256,content:row.content_text,correspondenceCount:Number(row.correspondence_count),createdAt:row.created_at}:null;}
  getAttemptSubmission(id){const row=this.database.prepare('SELECT submission_phase,uploaded_file_count FROM processing_attempts WHERE id=?').get(id);return row?{submissionPhase:row.submission_phase||'new',uploadedFileCount:Number(row.uploaded_file_count||0)}:null;}
  latestAttempt(taskId){const row=this.database.prepare('SELECT * FROM processing_attempts WHERE task_id=? ORDER BY attempt_number DESC LIMIT 1').get(taskId);return this.attempt(row);}
  updateTaskMetadata(id,input){const current=this.getTask(id);if(!current||current.status==='archived')return null;this.database.prepare('UPDATE processing_tasks SET display_name=?,description=?,metadata_json=?,updated_at=? WHERE id=?').run(bounded(input.displayName??current.displayName),bounded(input.description??current.description,4000)||null,JSON.stringify(input.metadata??current.metadata),now(),id);return this.getTask(id);}
  archiveTask(id){const task=this.getTask(id);if(!task)return null;const active=task.activeAttemptId&&this.getAttempt(task.activeAttemptId);if(active&&!['failed','cancelled','published'].includes(active.status))return null;const t=now(),changed=this.database.prepare("UPDATE processing_tasks SET status='archived',archived_at=?,updated_at=? WHERE id=? AND status<>'archived'").run(t,t,id);return changed.changes?this.getTask(id):null;}
  publishAttempt(id,modelId){const t=now();return this.transaction(()=>{const attempt=this.getAttempt(id);if(!attempt)return null;this.database.prepare("UPDATE processing_attempts SET status='published',completed_at=COALESCE(completed_at,?),updated_at=? WHERE id=?").run(t,t,id);this.database.prepare("UPDATE processing_tasks SET status='published',published_model_id=?,updated_at=? WHERE id=? AND active_attempt_id=?").run(modelId,t,attempt.taskId,id);this.database.prepare("UPDATE model_outputs SET status='published',updated_at=? WHERE id=? AND status='ready'").run(t,attempt.resultModelVersionId);return this.getTask(attempt.taskId);});}
  claimJob(owner, leaseSeconds=60) {
    return this.transaction(()=>{ const t=now(),expired=t; const row=this.database.prepare(`SELECT j.* FROM processing_jobs j JOIN processing_attempts a ON a.id=j.attempt_id LEFT JOIN processing_providers p ON p.id=a.provider_id
        WHERE j.available_at<=? AND (j.status='pending' OR (j.status='leased' AND j.lease_expires_at<=?))
        AND (j.job_type<>'submit' OR (p.enabled=1 AND (SELECT COUNT(*) FROM processing_attempts active WHERE active.provider_id=p.id AND active.id<>a.id AND active.status IN ('admitted','initializing','uploading','committed','queued_upstream','running')) < p.admission_limit))
        ORDER BY j.created_at LIMIT 1`).get(t,expired); if(!row)return null; const until=new Date(Date.now()+leaseSeconds*1000).toISOString();
      const updated=this.database.prepare("UPDATE processing_jobs SET status='leased',lease_owner=?,lease_expires_at=?,heartbeat_at=?,attempt_count=attempt_count+1,updated_at=? WHERE id=? AND (status='pending' OR lease_expires_at<=?)").run(owner,until,t,t,row.id,expired); if(updated.changes!==1)return null;
      this.database.prepare("UPDATE processing_attempts SET status='admitted',started_at=COALESCE(started_at,?),updated_at=? WHERE id=? AND status='pending'").run(t,t,row.attempt_id); return this.database.prepare('SELECT * FROM processing_jobs WHERE id=?').get(row.id); });
  }
  transitionAttempt(id,status,fields={}) { return this.transaction(()=>{const current=this.getAttempt(id);if(!current)return null;if(['cancelled','published'].includes(current.status)&&current.status!==status)return current;const t=now(),progress=Math.max(0,Math.min(1,Number(fields.progress??current.progress))),safeError=fields.errorMessage?sanitizeLogMessage(fields.errorMessage).slice(0,1000):null,changed=this.database.prepare(`UPDATE processing_attempts SET status=?,progress=?,provider_task_id=COALESCE(?,provider_task_id),error_code=?,error_message=?,upstream_completed_at=COALESCE(?,upstream_completed_at),ingested_at=COALESCE(?,ingested_at),completed_at=COALESCE(?,completed_at),updated_at=? WHERE id=? AND status=?`).run(status,progress,fields.providerTaskId||null,fields.errorCode||null,safeError,fields.upstreamCompletedAt||null,fields.ingestedAt||null,fields.completedAt||null,t,id,current.status);if(changed.changes!==1)return this.getAttempt(id);const taskStatus={pending:'queued',admitted:'processing',initializing:'processing',uploading:'processing',committed:'processing',queued_upstream:'processing',running:'processing',ingesting:'processing',derivatives:'processing',ready_for_review:'ready_for_review',published:'published',failed:'failed',cancelled:'cancelled'}[status];if(taskStatus)this.database.prepare('UPDATE processing_tasks SET status=?,updated_at=? WHERE id=? AND active_attempt_id=?').run(taskStatus,t,current.taskId,id);return this.getAttempt(id);}); }
  transitionAttemptForJob(jobId,owner,status,fields={}){return this.transaction(()=>{const job=this.database.prepare("SELECT * FROM processing_jobs WHERE id=? AND status='leased' AND lease_owner=? AND lease_expires_at>?").get(jobId,owner,now());if(!job)return null;const row=this.database.prepare('SELECT * FROM processing_attempts WHERE id=?').get(job.attempt_id);if(!row||['cancelled','published'].includes(row.status))return null;const current=this.attempt(row),t=now(),progress=Math.max(0,Math.min(1,Number(fields.progress??current.progress))),safeError=fields.errorMessage?sanitizeLogMessage(fields.errorMessage).slice(0,1000):null,changed=this.database.prepare(`UPDATE processing_attempts SET status=?,progress=?,provider_task_id=COALESCE(?,provider_task_id),error_code=?,error_message=?,upstream_completed_at=COALESCE(?,upstream_completed_at),ingested_at=COALESCE(?,ingested_at),completed_at=COALESCE(?,completed_at),updated_at=? WHERE id=? AND status=?`).run(status,progress,fields.providerTaskId||null,fields.errorCode||null,safeError,fields.upstreamCompletedAt||null,fields.ingestedAt||null,fields.completedAt||null,t,current.id,current.status);if(changed.changes!==1)return null;const taskStatus={admitted:'processing',initializing:'processing',uploading:'processing',committed:'processing',queued_upstream:'processing',running:'processing',ingesting:'processing',derivatives:'processing',ready_for_review:'ready_for_review',failed:'failed',cancelled:'cancelled'}[status];if(taskStatus)this.database.prepare('UPDATE processing_tasks SET status=?,updated_at=? WHERE id=? AND active_attempt_id=?').run(taskStatus,t,current.taskId,current.id);return this.getAttempt(current.id);});}
  heartbeatJob(id,owner,leaseSeconds=60){const t=now(),until=new Date(Date.now()+leaseSeconds*1000).toISOString();return this.database.prepare("UPDATE processing_jobs SET heartbeat_at=?,lease_expires_at=?,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(t,until,t,id,owner).changes===1;}
  setSubmissionStateForJob(jobId,owner,phase,uploadedFileCount){const t=now();const valid=new Set(['new','initializing','initialized','uploading','uploading_auxiliary','uploaded','committing','committed']);if(!valid.has(phase))throw new Error('invalid submission phase');return this.database.prepare(`UPDATE processing_attempts SET submission_phase=?,uploaded_file_count=?,updated_at=? WHERE id=(SELECT attempt_id FROM processing_jobs WHERE id=? AND status='leased' AND lease_owner=? AND lease_expires_at>?) AND status NOT IN ('cancelled','failed','published')`).run(phase,Math.max(0,Number(uploadedFileCount)||0),t,jobId,owner,t).changes===1;}
  completeJob(id,owner) { return this.database.prepare("UPDATE processing_jobs SET status='complete',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(now(),id,owner).changes===1; }
  enqueueJob(attemptId,jobType,availableAt=now()){const id=crypto.randomUUID(),t=now();this.database.prepare("INSERT INTO processing_jobs(id,attempt_id,job_type,status,available_at,created_at,updated_at) VALUES (?,?,?,'pending',?,?,?)").run(id,attemptId,jobType,availableAt,t,t);return id;}
  completeAndEnqueueJob(id,owner,attemptId,jobType,availableAt=now()){return this.transaction(()=>{const t=now(),done=this.database.prepare("UPDATE processing_jobs SET status='complete',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(t,id,owner);if(done.changes!==1)return false;this.database.prepare("INSERT INTO processing_jobs(id,attempt_id,job_type,status,available_at,created_at,updated_at) VALUES (?,?,?,'pending',?,?,?)").run(crypto.randomUUID(),attemptId,jobType,availableAt,t,t);return true;});}
  setAttemptResult(id,modelId,versionId){this.database.prepare('UPDATE processing_attempts SET result_model_id=?,result_model_version_id=?,updated_at=? WHERE id=?').run(modelId,versionId,now(),id);return this.getAttempt(id);}
  setAttemptResultForJob(jobId,owner,modelId,versionId){const t=now();return this.transaction(()=>{const job=this.database.prepare("SELECT attempt_id FROM processing_jobs WHERE id=? AND status='leased' AND lease_owner=? AND lease_expires_at>?").get(jobId,owner,t);if(!job)return null;const changed=this.database.prepare("UPDATE processing_attempts SET result_model_id=?,result_model_version_id=?,updated_at=? WHERE id=? AND status NOT IN ('cancelled','failed','published')").run(modelId,versionId,t,job.attempt_id);return changed.changes===1?this.getAttempt(job.attempt_id):null;});}
  setOutputCursor(id,cursor){this.database.prepare('UPDATE processing_attempts SET provider_output_cursor=?,updated_at=? WHERE id=?').run(Math.max(0,Number(cursor)||0),now(),id);}
  registerModelOutput({versionId,modelId,taskId,attemptId,projectId,relativePath,byteSize,assetCount}){const t=now();this.database.prepare(`INSERT INTO model_outputs(id,model_id,task_id,attempt_id,project_id,root_key,relative_path,status,byte_size,asset_count,created_at,updated_at) VALUES (?,?,?,?,?,'models',?,'ready',?,?,?,?) ON CONFLICT(id) DO UPDATE SET byte_size=excluded.byte_size,asset_count=excluded.asset_count,updated_at=excluded.updated_at`).run(versionId,modelId,taskId,attemptId,projectId,relativePath,Math.max(0,Number(byteSize)||0),Math.max(0,Number(assetCount)||0),t,t);return this.getModelOutput(versionId);}
  modelOutput(row){if(!row)return null;const model=this.database.prepare('SELECT display_name FROM models WHERE id=?').get(row.model_id);return{id:row.id,modelId:row.model_id,taskId:row.task_id,attemptId:row.attempt_id,projectId:row.project_id,displayName:model?.display_name||'',status:row.status,byteSize:Number(row.byte_size||0),assetCount:Number(row.asset_count||0),createdAt:row.created_at,updatedAt:row.updated_at,archivedAt:row.archived_at,trashedAt:row.trashed_at};}
  getModelOutput(id){return this.modelOutput(this.database.prepare('SELECT * FROM model_outputs WHERE id=?').get(id));}
  listModelOutputsPage({projectId=null,taskId=null,status=null,limit=50,cursor=null}={}){const n=pageLimit(limit),c=decodeCursor(cursor),where=[],args=[];if(projectId){where.push('project_id=?');args.push(projectId);}if(taskId){where.push('task_id=?');args.push(taskId);}if(status){if(!['ready','published','archived','trashed'].includes(status))throw Object.assign(new Error('invalid output status'),{code:'invalid_status'});where.push('status=?');args.push(status);}if(c){where.push('(created_at<? OR (created_at=? AND id<?))');args.push(c.createdAt,c.createdAt,c.id);}const sql=`SELECT * FROM model_outputs${where.length?' WHERE '+where.join(' AND '):''} ORDER BY created_at DESC,id DESC LIMIT ?`,rows=this.database.prepare(sql).all(...args,n+1),more=rows.length>n,items=rows.slice(0,n),totalsWhere=where.filter((_,i)=>!c||i<where.length-1),totalsArgs=c?args.slice(0,-3):args,totals=this.database.prepare(`SELECT COUNT(*) AS totalCount,COALESCE(SUM(byte_size),0) AS totalBytes FROM model_outputs${totalsWhere.length?' WHERE '+totalsWhere.join(' AND '):''}`).get(...totalsArgs);return{items:items.map((r)=>this.modelOutput(r)),nextCursor:more?encodeCursor(items.at(-1)):null,totalCount:Number(totals.totalCount),totalBytes:Number(totals.totalBytes)};}
  projectStorage(projectId,{limit=50,cursor=null}={}){if(!this.getProject(projectId))return null;const n=pageLimit(limit),c=decodeCursor(cursor),rows=c?this.database.prepare('SELECT * FROM processing_tasks WHERE project_id=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,c.createdAt,c.createdAt,c.id,n+1):this.database.prepare('SELECT * FROM processing_tasks WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,n+1),items=rows.slice(0,n),datasetBytes=Number(this.database.prepare("SELECT COALESCE(SUM(byte_size),0) AS n FROM datasets WHERE project_id=? AND status<>'trashed'").get(projectId).n),outputBytes=Number(this.database.prepare("SELECT COALESCE(SUM(byte_size),0) AS n FROM model_outputs WHERE project_id=? AND status<>'trashed'").get(projectId).n);return{project:{projectId,datasetBytes,outputBytes,totalBytes:datasetBytes+outputBytes},tasks:items.map((task)=>{const d=Number(this.database.prepare('SELECT byte_size AS n FROM datasets WHERE id=?').get(task.dataset_id)?.n||0),o=Number(this.database.prepare("SELECT COALESCE(SUM(byte_size),0) AS n FROM model_outputs WHERE task_id=? AND status<>'trashed'").get(task.id).n);return{taskId:task.id,projectId,datasetBytes:d,outputBytes:o,totalBytes:d+o};}),nextCursor:rows.length>n?encodeCursor(items.at(-1)):null};}
  taskStorage(taskId,{limit=50,cursor=null}={}){const task=this.getTask(taskId);if(!task)return null;const outputs=this.listModelOutputsPage({taskId,limit,cursor}),datasetBytes=Number(this.database.prepare('SELECT byte_size AS n FROM datasets WHERE id=?').get(task.datasetId)?.n||0),outputBytes=Number(this.database.prepare("SELECT COALESCE(SUM(byte_size),0) AS n FROM model_outputs WHERE task_id=? AND status<>'trashed'").get(taskId).n);return{task:{taskId,projectId:task.projectId,datasetBytes,outputBytes,totalBytes:datasetBytes+outputBytes},outputs:outputs.items,nextCursor:outputs.nextCursor};}
  outputInUse(output){const t=now();return Boolean(this.database.prepare('SELECT 1 FROM processing_attempts WHERE id=? AND status IN (\'pending\',\'admitted\',\'initializing\',\'uploading\',\'committed\',\'queued_upstream\',\'running\',\'ingesting\',\'derivatives\')').get(output.attemptId)||this.database.prepare('SELECT 1 FROM public_shares WHERE model_id=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?) LIMIT 1').get(output.modelId,t)||this.database.prepare('SELECT 1 FROM viewer_sessions WHERE model_id=? AND revoked_at IS NULL AND expires_at>? LIMIT 1').get(output.modelId,t));}
  archiveModelOutput(id){return this.transaction(()=>{const output=this.getModelOutput(id);if(!output||!['ready','published'].includes(output.status)||this.outputInUse(output))return null;const t=now(),changed=this.database.prepare("UPDATE model_outputs SET status='archived',archived_at=?,updated_at=? WHERE id=? AND status IN ('ready','published')").run(t,t,id);if(changed.changes!==1)return null;this.database.prepare('UPDATE model_assets SET published=0 WHERE version_id=?').run(id);this.database.prepare("UPDATE models SET active_version_id=NULL,status='unregistered',unregistered_at=?,updated_at=? WHERE id=? AND (active_version_id IS NULL OR active_version_id=?)").run(t,t,output.modelId,id);this.database.prepare("UPDATE processing_tasks SET status='archived',published_model_id=NULL,archived_at=COALESCE(archived_at,?),updated_at=? WHERE id=?").run(t,t,output.taskId);return this.getModelOutput(id);});}
  enqueueDerivative(attemptId,type,request={}){const existing=this.database.prepare('SELECT id,request_json FROM derivative_jobs WHERE attempt_id=? AND derivative_type=?').get(attemptId,type),serialized=JSON.stringify(request);if(existing){if(existing.request_json!==serialized)throw new Error('derivative job already exists with a different request');return existing.id;}const id=crypto.randomUUID(),t=now();try{this.database.prepare("INSERT INTO derivative_jobs(id,attempt_id,derivative_type,status,request_json,created_at,updated_at) VALUES (?,?,?,'pending',?,?,?)").run(id,attemptId,type,serialized,t,t);return id;}catch(error){if(!String(error.message).includes('UNIQUE constraint failed'))throw error;const raced=this.database.prepare('SELECT id,request_json FROM derivative_jobs WHERE attempt_id=? AND derivative_type=?').get(attemptId,type);if(!raced||raced.request_json!==serialized)throw error;return raced.id;}}
  claimDerivative(owner,leaseSeconds=300){return this.transaction(()=>{const t=now(),row=this.database.prepare("SELECT * FROM derivative_jobs WHERE status='pending' OR (status='leased' AND lease_expires_at<=?) ORDER BY created_at LIMIT 1").get(t);if(!row)return null;const until=new Date(Date.now()+leaseSeconds*1000).toISOString(),changed=this.database.prepare("UPDATE derivative_jobs SET status='leased',lease_owner=?,lease_expires_at=?,updated_at=? WHERE id=? AND (status='pending' OR lease_expires_at<=?)").run(owner,until,t,row.id,t);return changed.changes===1?this.database.prepare('SELECT * FROM derivative_jobs WHERE id=?').get(row.id):null;});}
  heartbeatDerivative(id,owner,leaseSeconds=300){const t=now(),until=new Date(Date.now()+leaseSeconds*1000).toISOString();return this.database.prepare("UPDATE derivative_jobs SET heartbeat_at=?,lease_expires_at=?,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(t,until,t,id,owner).changes===1;}
  completeDerivative(id,owner,result){const t=now();return this.database.prepare("UPDATE derivative_jobs SET status='complete',result_json=?,lease_owner=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(JSON.stringify(result||{}),t,t,id,owner).changes===1;}
  failDerivative(id,owner,message){return this.database.prepare("UPDATE derivative_jobs SET status='failed',result_json=?,lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(JSON.stringify({error:sanitizeLogMessage(message).slice(0,1000)}),now(),id,owner).changes===1;}
  derivativeSummary(attemptId){return this.database.prepare("SELECT status,COUNT(*) AS count FROM derivative_jobs WHERE attempt_id=? GROUP BY status").all(attemptId);}
  addModelAsset({versionId,kind,rootKey,relativePath,format,contentType,byteSize,attemptId,sha256=null,manifestSha256=null,manifestFiles=[]}){return this.transaction(()=>{const existing=this.database.prepare('SELECT id FROM model_assets WHERE version_id=? AND kind=?').get(versionId,kind),id=existing?.id||crypto.randomUUID(),t=now();this.database.prepare(`INSERT INTO model_assets(id,version_id,kind,root_key,relative_path,format,content_type,byte_size,storage_mode,published,source_attempt_id,sha256,manifest_sha256,created_at) VALUES (?,?,?,?,?,?,?,?,'managed',0,?,?,?,?,?) ON CONFLICT(version_id,kind) DO UPDATE SET relative_path=excluded.relative_path,format=excluded.format,content_type=excluded.content_type,byte_size=excluded.byte_size,storage_mode='managed',published=0,source_attempt_id=excluded.source_attempt_id,sha256=excluded.sha256,manifest_sha256=excluded.manifest_sha256`).run(id,versionId,kind,rootKey,relativePath,format||null,contentType||null,byteSize??null,attemptId,sha256,manifestSha256,t);this.database.prepare('DELETE FROM model_asset_files WHERE asset_id=?').run(id);const insert=this.database.prepare('INSERT INTO model_asset_files(asset_id,relative_path,byte_size,sha256) VALUES (?,?,?,?)');for(const file of manifestFiles)insert.run(id,file.relativePath,file.byteSize,file.sha256);return id;});}
  failJob(id,owner,code,message,retryAt=null) { return this.database.prepare(`UPDATE processing_jobs SET status=?,available_at=COALESCE(?,available_at),lease_owner=NULL,lease_expires_at=NULL,error_code=?,error_message=?,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?`).run(retryAt?'pending':'failed',retryAt,bounded(code,80),bounded(message,1000),now(),id,owner).changes===1; }
  cancelAttempt(id) { const a=this.transitionAttempt(id,'cancelled',{completedAt:now()}),t=now();this.database.prepare("UPDATE processing_jobs SET status='cancelled',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE attempt_id=? AND status IN ('pending','leased')").run(t,id);this.database.prepare("UPDATE derivative_jobs SET status='cancelled',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE attempt_id=? AND status IN ('pending','leased')").run(t,id);return a; }
  retryAttempt(id,actor) { const previous=this.getAttempt(id); if(!previous||!['failed','cancelled'].includes(previous.status)) return null; return this.createAttempt({taskId:previous.taskId,providerId:previous.providerId,presetId:previous.presetId,options:previous.options,capabilityFingerprint:previous.capabilityFingerprint,createdBy:actor}); }
  appendLog(attemptId,level,message) { const clean=sanitizeLogMessage(message), bytes=Buffer.byteLength(clean); const used=this.database.prepare('SELECT COALESCE(SUM(byte_size),0) AS n FROM processing_logs WHERE attempt_id=?').get(attemptId).n; if(used>=this.logMaxBytes)return false; const clipped=Buffer.from(clean).subarray(0,Math.max(0,this.logMaxBytes-used)).toString('utf8'); if(!clipped)return false; this.database.prepare('INSERT INTO processing_logs(attempt_id,level,message,byte_size,created_at) VALUES (?,?,?,?,?)').run(attemptId,bounded(level,20)||'info',clipped,Buffer.byteLength(clipped),now()); return true; }
  listLogs(attemptId,limit=500) { return this.database.prepare('SELECT level,message,created_at FROM processing_logs WHERE attempt_id=? ORDER BY id DESC LIMIT ?').all(attemptId,Math.max(1,Math.min(Number(limit)||500,2000))).reverse(); }
  pruneLogs(retentionDays=30,at=Date.now()){return this.database.prepare('DELETE FROM processing_logs WHERE created_at<?').run(new Date(at-retentionDays*86400_000).toISOString()).changes;}
  recordWorkerHeartbeat(owner,details={}){const value=JSON.stringify({owner,at:now(),...details});this.database.prepare(`INSERT INTO app_state(key,value,updated_at) VALUES ('processing_worker_heartbeat',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).run(value,now());}
  workerStatus(at=Date.now(),maxAgeMs=30000){const row=this.database.prepare("SELECT value FROM app_state WHERE key='processing_worker_heartbeat'").get();if(!row)return{live:false};const value=json(row.value,{});return{...value,live:Number.isFinite(Date.parse(value.at))&&Date.parse(value.at)>at-maxAgeMs};}
  workerWorkCounts(){return{datasetOperations:Number(this.database.prepare("SELECT COUNT(*) AS n FROM dataset_operations WHERE status='leased'").get().n),processing:Number(this.database.prepare("SELECT COUNT(*) AS n FROM processing_jobs WHERE status='leased'").get().n),derivatives:Number(this.database.prepare("SELECT COUNT(*) AS n FROM derivative_jobs WHERE status='leased'").get().n),events:Number(this.database.prepare("SELECT COUNT(*) AS n FROM event_outbox WHERE status='leased'").get().n)};}

  createAdminGrant({subject,permissions,displayUnits,expiresAt,authorizationExpiresAt}) { const id=crypto.randomUUID(),token=crypto.randomBytes(32).toString('base64url'),t=now(); this.database.prepare('INSERT INTO admin_grants(id,token_hash,subject,permissions_json,display_units,expires_at,authorization_expires_at,created_at) VALUES (?,?,?,?,?,?,?,?)').run(id,crypto.createHash('sha256').update(token).digest('hex'),bounded(subject,200),JSON.stringify(permissions||[]),displayUnits||'imperial',expiresAt,authorizationExpiresAt,t); return {token,subject,permissions,displayUnits:displayUnits||'imperial',expiresAt,authorizationExpiresAt,createdAt:t}; }
  redeemAdminGrant(token,at=Date.now()) { const hash=crypto.createHash('sha256').update(token||'').digest('hex');return this.transaction(()=>{ const row=this.database.prepare('SELECT * FROM admin_grants WHERE token_hash=?').get(hash);if(!row||row.redeemed_at||Date.parse(row.expires_at)<=at||Date.parse(row.authorization_expires_at)<=at)return null;const t=new Date(at).toISOString();const changed=this.database.prepare('UPDATE admin_grants SET redeemed_at=? WHERE id=? AND redeemed_at IS NULL').run(t,row.id);return changed.changes===1?{id:row.id,subject:row.subject,permissions:json(row.permissions_json,[]),displayUnits:row.display_units,expiresAt:row.expires_at,authorizationExpiresAt:row.authorization_expires_at}:null; }); }
  adminSession(row) { return row&&{id:row.id,tokenHash:row.token_hash,subject:row.subject,permissions:json(row.permissions_json,[]),displayUnits:row.display_units,expiresAt:row.expires_at,revokedAt:row.revoked_at,createdAt:row.created_at,updatedAt:row.updated_at}; }
  createAdminSession({tokenHash,subject,permissions,displayUnits,expiresAt}) { const id=crypto.randomUUID(),t=now();this.database.prepare('INSERT INTO admin_sessions(id,token_hash,subject,permissions_json,display_units,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run(id,tokenHash,subject,JSON.stringify(permissions),displayUnits||'imperial',expiresAt,t,t);return this.getAdminSessionByHash(tokenHash); }
  getAdminSessionByHash(hash) { return this.adminSession(this.database.prepare('SELECT * FROM admin_sessions WHERE token_hash=?').get(hash)); }
  adminSessionLive(session,at=Date.now()) { return Boolean(session&&!session.revokedAt&&Date.parse(session.expiresAt)>at); }
  renewAdminSession(id,{permissions,displayUnits,expiresAt}) { const t=now();const changed=this.database.prepare('UPDATE admin_sessions SET permissions_json=?,display_units=?,expires_at=?,updated_at=? WHERE id=? AND revoked_at IS NULL').run(JSON.stringify(permissions),displayUnits||'imperial',expiresAt,t,id);return changed.changes===1?this.adminSession(this.database.prepare('SELECT * FROM admin_sessions WHERE id=?').get(id)):null; }
  revokeAdminSession(id) { const t=now();return this.database.prepare('UPDATE admin_sessions SET revoked_at=COALESCE(revoked_at,?),updated_at=? WHERE id=?').run(t,t,id).changes===1; }
  reserveAdminIdempotency({sessionId,key,method,path:route,requestHash}) { const t=now();let existing=this.database.prepare('SELECT * FROM admin_idempotency WHERE session_id=? AND idempotency_key=?').get(sessionId,key);if(existing&&(Date.parse(existing.expires_at)<=Date.now()||(existing.response_status===null&&Date.parse(existing.created_at)<=Date.now()-15*60_000))){this.database.prepare('DELETE FROM admin_idempotency WHERE session_id=? AND idempotency_key=? AND response_status IS NULL').run(sessionId,key);existing=this.database.prepare('SELECT * FROM admin_idempotency WHERE session_id=? AND idempotency_key=?').get(sessionId,key);}if(existing)return{created:false,record:existing};try{this.database.prepare('INSERT INTO admin_idempotency(session_id,idempotency_key,method,path,request_hash,created_at,expires_at) VALUES (?,?,?,?,?,?,?)').run(sessionId,key,method,route,requestHash,t,new Date(Date.now()+24*3600_000).toISOString());return{created:true};}catch(error){if(!String(error.message).includes('UNIQUE constraint failed'))throw error;return{created:false,record:this.database.prepare('SELECT * FROM admin_idempotency WHERE session_id=? AND idempotency_key=?').get(sessionId,key)};} }
  completeAdminIdempotency(sessionId,key,status,response) { this.database.prepare('UPDATE admin_idempotency SET response_status=?,response_json=? WHERE session_id=? AND idempotency_key=?').run(status,JSON.stringify(response),sessionId,key); }

  createImportPreview({request,preview,createdBy,createdSessionId,expiresAt}) { const id=crypto.randomUUID(),token=crypto.randomBytes(32).toString('base64url'),t=now();this.database.prepare('INSERT INTO dataset_import_previews(id,token_hash,request_json,preview_json,expires_at,created_by,created_session_id,created_at) VALUES (?,?,?,?,?,?,?,?)').run(id,crypto.createHash('sha256').update(token).digest('hex'),JSON.stringify(request),JSON.stringify(preview),expiresAt,createdBy,createdSessionId||null,t);return{id,token,preview,expiresAt}; }
  getImportPreview(token,sessionId,at=Date.now()) { const hash=crypto.createHash('sha256').update(token||'').digest('hex'),row=this.database.prepare('SELECT * FROM dataset_import_previews WHERE token_hash=?').get(hash);if(!row||row.consumed_at||row.claimed_at||Date.parse(row.expires_at)<=at||(row.created_session_id&&row.created_session_id!==sessionId))return null;return{id:row.id,request:json(row.request_json),preview:json(row.preview_json),createdBy:row.created_by}; }
  claimImportPreview(token,sessionId,claimId,at=Date.now()){const hash=crypto.createHash('sha256').update(token||'').digest('hex'),t=new Date(at).toISOString();return this.transaction(()=>{const row=this.database.prepare('SELECT * FROM dataset_import_previews WHERE token_hash=?').get(hash);if(!row||row.consumed_at||row.claimed_at||Date.parse(row.expires_at)<=at||(row.created_session_id&&row.created_session_id!==sessionId))return null;const changed=this.database.prepare('UPDATE dataset_import_previews SET claimed_at=?,claim_id=? WHERE id=? AND claimed_at IS NULL AND consumed_at IS NULL').run(t,claimId,row.id);return changed.changes===1?{id:row.id,request:json(row.request_json),preview:json(row.preview_json),createdBy:row.created_by}:null;});}
  releaseImportPreview(id,claimId){this.database.prepare('UPDATE dataset_import_previews SET claimed_at=NULL,claim_id=NULL WHERE id=? AND claim_id=? AND consumed_at IS NULL').run(id,claimId);}
  consumeClaimedImportPreview(id,claimId){const t=now();return this.database.prepare('UPDATE dataset_import_previews SET consumed_at=?,claimed_at=NULL,claim_id=NULL WHERE id=? AND claim_id=? AND consumed_at IS NULL').run(t,id,claimId).changes===1;}

  datasetOperation(row){return row?{id:row.id,type:row.operation_type,subject:row.subject,datasetId:row.dataset_id,uploadId:row.upload_id,status:row.status,progress:row.progress,result:json(row.result_json,null),errorCode:row.error_code,errorMessage:row.error_message,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at}:null;}
  getDatasetOperation(id,subject=null){const row=subject?this.database.prepare('SELECT * FROM dataset_operations WHERE id=? AND subject=?').get(id,subject):this.database.prepare('SELECT * FROM dataset_operations WHERE id=?').get(id);return this.datasetOperation(row);}
  createUploadFinalizeOperation(uploadId,subject){return this.transaction(()=>{const existing=this.database.prepare("SELECT * FROM dataset_operations WHERE upload_id=? AND status IN ('queued','leased','succeeded') ORDER BY created_at DESC LIMIT 1").get(uploadId);if(existing)return this.datasetOperation(existing);const upload=this.getUpload(uploadId);if(!upload||upload.subject!==subject||upload.status!=='open')return null;const t=now(),id=crypto.randomUUID();if(this.database.prepare("UPDATE upload_sessions SET status='finalizing',updated_at=? WHERE id=? AND status='open'").run(t,uploadId).changes!==1)return null;this.database.prepare("INSERT INTO dataset_operations(id,operation_type,subject,dataset_id,upload_id,status,available_at,created_at,updated_at) VALUES (?,'upload_finalize',?,?,?,'queued',?,?,?)").run(id,subject,upload.datasetId,uploadId,t,t,t);return this.getDatasetOperation(id);});}
  createImportAdoptOperation({previewToken,sessionId,subject,projectId,displayName,storageMode}){const tokenHash=crypto.createHash('sha256').update(previewToken||'').digest('hex');return this.transaction(()=>{const preview=this.database.prepare('SELECT * FROM dataset_import_previews WHERE token_hash=?').get(tokenHash);if(!preview||preview.consumed_at||preview.claimed_at||Date.parse(preview.expires_at)<=Date.now()||preview.created_by!==subject||(preview.created_session_id&&preview.created_session_id!==sessionId))return null;const project=this.getProject(projectId);if(!project||project.status!=='active')return null;const t=now(),id=crypto.randomUUID(),datasetId=crypto.randomUUID(),request=json(preview.request_json);this.database.prepare("UPDATE dataset_import_previews SET claimed_at=?,claim_id=? WHERE id=? AND claimed_at IS NULL AND consumed_at IS NULL").run(t,id,preview.id);this.database.prepare(`INSERT INTO datasets(id,project_id,display_name,source_type,storage_mode,root_key,relative_path,status,metadata_json,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(datasetId,projectId,bounded(displayName)||'Imported dataset',request.rootKey==='webodm'?'webodm':'server_import',storageMode,storageMode==='external_reference'?request.rootKey:'datasets',storageMode==='external_reference'?request.relativePath:datasetId,'finalizing','{}',subject,t,t);const payload={rootKey:request.rootKey,relativePath:request.relativePath,storageMode,treeFingerprint:json(preview.preview_json).treeFingerprint,previewId:preview.id};this.database.prepare("INSERT INTO dataset_operations(id,operation_type,subject,session_id,dataset_id,import_preview_id,payload_json,status,available_at,created_at,updated_at) VALUES (?,'import_adopt',?,?,?,?,?,'queued',?,?,?)").run(id,subject,sessionId||null,datasetId,preview.id,JSON.stringify(payload),t,t,t);return this.getDatasetOperation(id);});}
  claimDatasetOperation(owner,leaseSeconds=600){return this.transaction(()=>{const t=now(),row=this.database.prepare("SELECT * FROM dataset_operations WHERE available_at<=? AND (status='queued' OR (status='leased' AND lease_expires_at<=?)) ORDER BY created_at LIMIT 1").get(t,t);if(!row)return null;const until=new Date(Date.now()+leaseSeconds*1000).toISOString(),changed=this.database.prepare("UPDATE dataset_operations SET status='leased',lease_owner=?,lease_expires_at=?,heartbeat_at=?,attempt_count=attempt_count+1,updated_at=? WHERE id=? AND (status='queued' OR lease_expires_at<=?)").run(owner,until,t,t,row.id,t);return changed.changes===1?this.database.prepare('SELECT * FROM dataset_operations WHERE id=?').get(row.id):null;});}
  heartbeatDatasetOperation(id,owner,progress,leaseSeconds=600){const t=now(),until=new Date(Date.now()+leaseSeconds*1000).toISOString();return this.database.prepare("UPDATE dataset_operations SET progress=?,heartbeat_at=?,lease_expires_at=?,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(Math.max(0,Math.min(0.99,Number(progress)||0)),t,until,t,id,owner).changes===1;}
  completeDatasetOperation(id,owner,result){const t=now();return this.database.prepare("UPDATE dataset_operations SET status='succeeded',progress=1,result_json=?,lease_owner=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE id=? AND status='leased' AND lease_owner=?").run(JSON.stringify(result||{}),t,t,id,owner).changes===1;}
  failDatasetOperation(id,owner,code,message){const safe=sanitizeLogMessage(message).slice(0,1000),t=now();return this.transaction(()=>{const row=this.database.prepare("SELECT * FROM dataset_operations WHERE id=? AND status='leased' AND lease_owner=?").get(id,owner);if(!row)return false;this.database.prepare("UPDATE dataset_operations SET status='failed',error_code=?,error_message=?,lease_owner=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE id=? AND lease_owner=?").run(bounded(code,80),safe,t,t,id,owner);if(row.upload_id)this.database.prepare("UPDATE upload_sessions SET status='open',updated_at=? WHERE id=? AND status='finalizing'").run(t,row.upload_id);if(row.import_preview_id)this.database.prepare('UPDATE dataset_import_previews SET claimed_at=NULL,claim_id=NULL WHERE id=? AND claim_id=? AND consumed_at IS NULL').run(row.import_preview_id,id);return true;});}
  consumeOperationImportPreview(operationId,previewId){const t=now(),changed=this.database.prepare('UPDATE dataset_import_previews SET consumed_at=?,claimed_at=NULL,claim_id=NULL WHERE id=? AND claim_id=? AND consumed_at IS NULL').run(t,previewId,operationId);if(changed.changes===1)return true;return Boolean(this.database.prepare('SELECT 1 FROM dataset_import_previews WHERE id=? AND consumed_at IS NOT NULL').get(previewId));}

  enqueueEvent(type,payload) { const id=payload.eventId||crypto.randomUUID(),t=now();const clean={...payload,eventId:id,error:payload.error?{code:bounded(payload.error.code,80),message:sanitizeLogMessage(payload.error.message).slice(0,1000)}:undefined};const serialized=JSON.stringify(clean);if(Buffer.byteLength(serialized)>64*1024)throw new Error('event payload exceeds 64 KiB');const existing=this.database.prepare('SELECT payload_json,event_type FROM event_outbox WHERE id=?').get(id);if(existing){if(existing.payload_json!==serialized||existing.event_type!==type)throw new Error('eventId already has a different payload');return id;}this.database.prepare("INSERT INTO event_outbox(id,event_type,payload_json,status,available_at,created_at,updated_at) VALUES (?,?,?,'pending',?,?,?)").run(id,type,serialized,t,t,t);return id; }
  claimEvent(leaseSeconds=60){return this.transaction(()=>{const t=now(),row=this.database.prepare("SELECT * FROM event_outbox WHERE available_at<=? AND (status='pending' OR (status='leased' AND lease_expires_at<=?)) ORDER BY created_at LIMIT 1").get(t,t);if(!row)return null;const until=new Date(Date.now()+leaseSeconds*1000).toISOString();const changed=this.database.prepare("UPDATE event_outbox SET status='leased',lease_expires_at=?,attempt_count=attempt_count+1,updated_at=? WHERE id=? AND (status='pending' OR lease_expires_at<=?)").run(until,t,row.id,t);return changed.changes===1?this.database.prepare('SELECT * FROM event_outbox WHERE id=?').get(row.id):null;});}
  deliverEvent(id){const t=now();this.database.prepare("UPDATE event_outbox SET status='delivered',delivered_at=?,lease_expires_at=NULL,updated_at=? WHERE id=?").run(t,t,id);}
  retryEvent(id,message,attemptCount){const terminal=attemptCount>=12,t=now(),next=new Date(Date.now()+Math.min(3600_000,5000*2**Math.min(attemptCount,10))).toISOString();this.database.prepare('UPDATE event_outbox SET status=?,available_at=?,lease_expires_at=NULL,last_error=?,updated_at=? WHERE id=?').run(terminal?'failed':'pending',next,bounded(sanitizeLogMessage(message),1000),t,id);}
}

module.exports = { BUILT_IN_PRESETS, ProcessingRepository };
