'use strict';
const crypto=require('node:crypto');const {config}=require('./config');const {signViewerEvent}=require('./viewerEvents');const {boundedText}=require('./nodeOdmProvider');
const PATH='/api/viewer/source-authorizations/introspect';

class SourceAuthorizationValidator{
  constructor({enabled=config.clientViewerSharesEnabled,baseUrl=config.opsAutomationBaseUrl,keyId=config.viewerEventKeyId,secret=config.viewerEventSecret,fetchImpl=fetch,positiveMs=5000,negativeMs=1000,timeoutMs=3000}={}){this.enabled=Boolean(enabled);this.baseUrl=baseUrl;this.keyId=keyId;this.secret=secret;this.fetch=fetchImpl;this.positiveMs=Math.min(5000,Math.max(250,positiveMs));this.negativeMs=Math.min(1000,Math.max(100,negativeMs));this.timeoutMs=Math.min(5000,Math.max(250,timeoutMs));this.cache=new Map();this.pending=new Map();}
  key(share){const source=share.sourceAuthorization;return crypto.createHash('sha256').update(JSON.stringify([source.id,source.version,source.subject,share.modelId,share.id])).digest('hex');}
  configured(){try{const url=new URL(this.baseUrl);return this.enabled&&url.origin===this.baseUrl&&url.protocol==='https:'&&url.username===''&&url.password===''&&url.pathname==='/'&&!url.search&&!url.hash&&this.secret.length>=32&&/^[A-Za-z0-9._-]{1,64}$/.test(this.keyId);}catch{return false;}}
  async allows(share,at=Date.now()){if(!share||share.shareClass!=='client')return true;const source=share.sourceAuthorization;if(!this.configured()||!source||source.type!=='client_grant'||typeof source.id!=='string'||!Number.isSafeInteger(source.version)||source.version<1||typeof source.subject!=='string'||!source.subject)return false;const sourceExpiry=source.expiresAt===null?null:Date.parse(source.expiresAt);if(sourceExpiry!==null&&(!Number.isFinite(sourceExpiry)||sourceExpiry<=at))return false;const key=this.key(share),cached=this.cache.get(key);if(cached&&cached.until>at)return cached.allowed;if(cached)this.cache.delete(key);const inflight=this.pending.get(key);if(inflight)return inflight;const promise=this.check(share,at).then((allowed)=>{const maxUntil=allowed?at+this.positiveMs:at+this.negativeMs,until=allowed&&sourceExpiry!==null?Math.min(maxUntil,sourceExpiry):maxUntil;this.cache.set(key,{allowed,until});while(this.cache.size>10000)this.cache.delete(this.cache.keys().next().value);return allowed;}).catch(()=>{this.cache.set(key,{allowed:false,until:at+this.negativeMs});return false;}).finally(()=>this.pending.delete(key));this.pending.set(key,promise);return promise;}
  async check(share){const source=share.sourceAuthorization,url=new URL(PATH,this.baseUrl),body=JSON.stringify({authorizationId:source.id,authorizationVersion:source.version,subject:source.subject,modelId:share.modelId,shareId:share.id}),headers=signViewerEvent({secret:this.secret,keyId:this.keyId,method:'POST',path:PATH,body}),response=await this.fetch(url,{method:'POST',redirect:'error',signal:AbortSignal.timeout(this.timeoutMs),headers:{...headers,'Content-Type':'application/json'},body});if(!response.ok)return false;if(!String(response.headers.get('content-type')||'').includes('json'))return false;let result;try{result=JSON.parse(await boundedText(response,64*1024));}catch{return false;}const keys=Object.keys(result||{}).sort().join(',');if(keys!=='active,authorizationId,authorizationVersion,expiresAt,modelId,subject'||typeof result.active!=='boolean'||result.authorizationId!==source.id||result.authorizationVersion!==source.version||result.subject!==source.subject||result.modelId!==share.modelId||result.expiresAt!==source.expiresAt)return false;return result.active&&(result.expiresAt===null||Date.parse(result.expiresAt)>Date.now());}
}

const sourceAuthorizationValidator=new SourceAuthorizationValidator();
module.exports={PATH,SourceAuthorizationValidator,sourceAuthorizationValidator};
