'use strict';
const crypto=require('node:crypto');const {spawnSync}=require('node:child_process');const {config,validate}=require('./config');const {openDatabase}=require('./database');const {ViewerRepository}=require('./repository');const {ProcessingRepository}=require('./processingRepository');const {StorageManager}=require('./storageManager');const {ProviderCredentials}=require('./providerCredentials');const {processOne}=require('./processingWorker');const {refreshOneProviderHealth}=require('./providerHealth');const {deliverOneEvent}=require('./eventDelivery');const {processOneDerivative}=require('./derivativeWorker');const {processOneImportCleanup}=require('./importCleanup');const {processOneDatasetOperation,reconcileCatalogAdoptionRecoveries,reconcileCatalogSourceCleanups}=require('./datasetOperationWorker');const {reconcileStorageMutations,purgeExpiredTrash}=require('./storageLifecycle');const {reconcileMissingPointCloudAssets}=require('./lodBackfill');const {reconcileLodDerivativeStorage}=require('./lodDerivativeStorage');const {reconcileMissingOdmGeoreference}=require('./odmGeorefReconciliation');
const {reconcileProviderlessRetries}=require('./providerlessRetryReconciliation');
const {retireSupersededOutputs,purgeSupersededOutputs}=require('./outputSupersession');
const maintenanceAbort=new AbortController();
for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>maintenanceAbort.abort());
const workerInstanceId=/^[a-f0-9-]{36}$/i.test(process.env.WORKER_INSTANCE_ID||'')?process.env.WORKER_INSTANCE_ID:crypto.randomUUID();
const problems=validate();if(problems.length){console.error('Processing worker configuration is invalid:',problems.join('; '));process.exit(1);}if(!config.processingPlatformEnabled){const idleDb=openDatabase(config.databasePath),idleProcessing=new ProcessingRepository(idleDb),owner=`worker-idle-${workerInstanceId}`,heartbeat=()=>idleProcessing.recordWorkerHeartbeat(owner,{version:1,enabled:false,idle:true,active:idleProcessing.workerWorkCounts()});heartbeat();const timer=setInterval(heartbeat,10000);console.log('Processing worker is idle because PROCESSING_PLATFORM_ENABLED=false');let closing=false;for(const signal of['SIGINT','SIGTERM'])process.once(signal,()=>{if(closing)return;closing=true;clearInterval(timer);idleDb.close();process.exit(0);});}else{
for(const [enabled,name,bin,args,flag]of[[config.localDerivativesEnabled,'Entwine',config.entwineBin,['--version'],'LOCAL_DERIVATIVES_ENABLED'],[config.meshDerivativesEnabled,'Obj2Tiles',config.obj2TilesBin,['--version'],'MESH_DERIVATIVES_ENABLED']]){if(!enabled)continue;const probe=spawnSync(bin,args,{windowsHide:true,timeout:10000,stdio:'ignore'});if(probe.error||probe.status===null||probe.status!==0){console.error(`${name} is unavailable; disable ${flag} or install the configured executable`);process.exit(1);}}
const db=openDatabase(config.databasePath),repository=new ViewerRepository(db),processing=new ProcessingRepository(db,{logMaxBytes:config.processingLogMaxBytes}),providerCredentials=new ProviderCredentials({processing,activeKeyId:config.providerCredentialsKeyId,keys:config.providerCredentialsKeys,legacyTokens:config.processingProviderTokens}),storage=new StorageManager(config);providerCredentials.migrateLegacy();storage.initialize();const owner=`worker-${workerInstanceId}`;let stopped=false;for(const signal of['SIGINT','SIGTERM'])process.once(signal,()=>{if(stopped)return;stopped=true;console.log(`Processing worker stopping after ${signal}`);});
function heartbeat(){try{processing.recordWorkerHeartbeat(owner,{version:1,nativeOdmOutputs:true,localDerivatives:config.localDerivativesEnabled,meshDerivatives:config.meshDerivativesEnabled,active:processing.workerWorkCounts()});return true;}catch{return false;/* next heartbeat retries */}}
function maintenanceCode(error){return String(error?.code||error?.name||'maintenance_error').replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,80);}
async function maintenanceStep(name,run){if(stopped)return null;try{return await run();}catch(error){console.error(`Maintenance ${name} failed: code=${maintenanceCode(error)}`);return null;}}
let maintenanceActive=false,maintenancePending=Promise.resolve();
function maintenance(){if(stopped||maintenanceActive)return maintenancePending;maintenancePending=runMaintenance();return maintenancePending;}
async function runMaintenance(){maintenanceActive=true;try{
  const providerless=await maintenanceStep('providerless-retry-reconciliation',()=>reconcileProviderlessRetries(processing,{limit:100}));if(providerless&&(providerless.invalidated||providerless.restored))console.log(`Providerless retry reconciliation: invalidated=${providerless.invalidated} restored=${providerless.restored}`);
  await maintenanceStep('upload-finalization-recovery',()=>processing.recoverStaleUploadFinalizations());
  await maintenanceStep('storage-mutation-reconciliation',()=>reconcileStorageMutations(processing,storage,20));
  await maintenanceStep('catalog-source-cleanup',()=>reconcileCatalogSourceCleanups(processing,storage,20));
  await maintenanceStep('catalog-adoption-recovery',()=>reconcileCatalogAdoptionRecoveries(processing,storage,20));
  const georef=await maintenanceStep('odm-georeference-reconciliation',()=>reconcileMissingOdmGeoreference(repository,storage,{limit:5}));if(georef&&(georef.scanned||georef.updated||georef.terminal))console.log(`ODM georeference reconciliation: scanned=${georef.scanned} updated=${georef.updated} terminal=${georef.terminal}`);
  const pointCloud=await maintenanceStep('point-cloud-reconciliation',()=>reconcileMissingPointCloudAssets(processing,storage,{limit:5}));if(pointCloud&&(pointCloud.scanned||pointCloud.registered))console.log(`Point-cloud reconciliation: scanned=${pointCloud.scanned} registered=${pointCloud.registered}`);
  const lodStorage=await maintenanceStep('lod-derivative-storage-reconciliation',()=>reconcileLodDerivativeStorage(processing,storage,{limit:100}));if(lodStorage&&(lodStorage.scanned||lodStorage.removed))console.log(`LOD derivative storage reconciliation: scanned=${lodStorage.scanned} removed=${lodStorage.removed}`);
  if(stopped)return;
  for(const id of processing.expiredUploads().slice(0,20))await maintenanceStep('expired-upload-cleanup',()=>{processing.expireUpload(id);storage.cleanupUpload(id);});
  const superseded=await maintenanceStep('superseded-output-retirement',()=>retireSupersededOutputs(processing,storage,{limit:1,signal:maintenanceAbort.signal}));if(superseded?.length)console.log(`Output supersession: inspected=${superseded.length} retired=${superseded.filter(item=>item.status==='retired').length} retained=${superseded.filter(item=>item.status!=='retired').length}`);
  await maintenanceStep('superseded-output-verified-purge',()=>purgeSupersededOutputs(processing,storage,{limit:1,signal:maintenanceAbort.signal}));
  await maintenanceStep('trash-retention-purge',()=>purgeExpiredTrash(processing,storage,{actor:owner,limit:20,onPurged:(item)=>repository.audit({actorType:'system',actorId:owner,action:`${item.entityType}.retention_purged`,entityType:item.entityType,entityId:item.entityId})}));
  await maintenanceStep('processing-log-prune',()=>processing.pruneLogs(config.processingLogRetentionDays));
  await maintenanceStep('operation-receipt-prune',()=>processing.pruneSubjectOperationReceipts(7));
  await maintenanceStep('abuse-window-prune',()=>repository.pruneAbuseWindows());
}finally{maintenanceActive=false;}}
const delay=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));async function lane(name,run){while(!stopped){try{if(!await run())await delay(2000);}catch(error){console.error(`${name} lane error:`,error.code||error.name||'worker_error');await delay(2000);}}}
const initialHeartbeat=heartbeat();console.log(`Processing worker started: heartbeat=${initialHeartbeat?'recorded':'pending'} local-derivatives=${config.localDerivativesEnabled?'enabled':'disabled'} mesh-derivatives=${config.meshDerivativesEnabled?'enabled':'disabled'} lanes=dataset-operation,processing,provider-health,derivative,event,import-cleanup`);maintenance();const heartbeatTimer=setInterval(heartbeat,10000),maintenanceTimer=setInterval(maintenance,3600000);heartbeatTimer.unref?.();maintenanceTimer.unref?.();
(async()=>{await Promise.all([lane('dataset-operation',()=>processOneDatasetOperation({processing,repository,storage,config},`${owner}:dataset`)),lane('processing',()=>processOne({processing,repository,storage,config,providerCredentials},`${owner}:processing`)),lane('provider-health',()=>refreshOneProviderHealth({processing,providerCredentials,config,owner:`${owner}:health`})),lane('derivative',()=>processOneDerivative({processing,storage,config},`${owner}:derivative`)),lane('event',()=>deliverOneEvent(processing,config)),lane('import-cleanup',()=>processOneImportCleanup({processing,storage},`${owner}:cleanup`))]);clearInterval(heartbeatTimer);clearInterval(maintenanceTimer);maintenanceAbort.abort();await maintenancePending;db.close();console.log('Processing worker stopped cleanly');})().catch(async(error)=>{stopped=true;maintenanceAbort.abort();clearInterval(heartbeatTimer);clearInterval(maintenanceTimer);console.error('Processing worker stopped:',error.code||error.name||'worker_error');try{await maintenancePending;}catch{}try{db.close();}catch{}process.exitCode=1;});
}
