'use strict';
const crypto=require('node:crypto');const {spawnSync}=require('node:child_process');const {config,validate}=require('./config');const {openDatabase}=require('./database');const {ViewerRepository}=require('./repository');const {ProcessingRepository}=require('./processingRepository');const {StorageManager}=require('./storageManager');const {ProviderCredentials}=require('./providerCredentials');const {processOne}=require('./processingWorker');const {deliverOneEvent}=require('./eventDelivery');const {processOneDerivative}=require('./derivativeWorker');const {processOneDatasetOperation}=require('./datasetOperationWorker');const {reconcileStorageMutations,purgeExpiredTrash}=require('./storageLifecycle');
const problems=validate();if(problems.length||!config.processingPlatformEnabled){console.error('Processing worker configuration is invalid:',problems.join('; ')||'platform disabled');process.exit(1);}if(config.localDerivativesEnabled){for(const [name,bin,args]of[['Entwine',config.entwineBin,['--version']],['Obj2Tiles',config.obj2TilesBin,['--help']]]){const probe=spawnSync(bin,args,{windowsHide:true,timeout:10000,stdio:'ignore'});if(probe.error||probe.status===null){console.error(`${name} is unavailable; disable LOCAL_DERIVATIVES_ENABLED and use native ODM outputs`);process.exit(1);}}}
const db=openDatabase(config.databasePath),repository=new ViewerRepository(db),processing=new ProcessingRepository(db,{logMaxBytes:config.processingLogMaxBytes}),providerCredentials=new ProviderCredentials({processing,activeKeyId:config.providerCredentialsKeyId,keys:config.providerCredentialsKeys,legacyTokens:config.processingProviderTokens}),storage=new StorageManager(config);providerCredentials.migrateLegacy();storage.initialize();const owner=`worker-${crypto.randomUUID()}`;let stopped=false;for(const signal of['SIGINT','SIGTERM'])process.once(signal,()=>{stopped=true;});
function heartbeat(){try{processing.recordWorkerHeartbeat(owner,{version:1,nativeOdmOutputs:true,localDerivatives:config.localDerivativesEnabled,active:processing.workerWorkCounts()});}catch{/* next heartbeat retries */}}
function maintenance(){try{processing.recoverStaleUploadFinalizations();}catch{}try{reconcileStorageMutations(processing,storage,20);}catch{}for(const id of processing.expiredUploads().slice(0,20)){try{processing.expireUpload(id);storage.cleanupUpload(id);}catch{}}try{purgeExpiredTrash(processing,storage,{actor:owner,limit:20,onPurged:(item)=>repository.audit({actorType:'system',actorId:owner,action:'dataset.retention_purged',entityType:'dataset',entityId:item.entityId})});}catch{}try{processing.pruneLogs(config.processingLogRetentionDays);}catch{}}
const delay=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));async function lane(name,run){while(!stopped){try{if(!await run())await delay(2000);}catch(error){console.error(`${name} lane error:`,error.code||error.name||'worker_error');await delay(2000);}}}
heartbeat();maintenance();const heartbeatTimer=setInterval(heartbeat,10000),maintenanceTimer=setInterval(maintenance,3600000);heartbeatTimer.unref?.();maintenanceTimer.unref?.();
(async()=>{await Promise.all([lane('dataset-operation',()=>processOneDatasetOperation({processing,storage,config},`${owner}:dataset`)),lane('processing',()=>processOne({processing,repository,storage,config,providerCredentials},`${owner}:processing`)),lane('derivative',()=>processOneDerivative({processing,storage,config},`${owner}:derivative`)),lane('event',()=>deliverOneEvent(processing,config))]);clearInterval(heartbeatTimer);clearInterval(maintenanceTimer);db.close();})().catch((error)=>{clearInterval(heartbeatTimer);clearInterval(maintenanceTimer);console.error('Processing worker stopped:',error.code||error.name||'worker_error');try{db.close();}catch{}process.exitCode=1;});
