'use strict';
const crypto=require('node:crypto');const {spawnSync}=require('node:child_process');const {config,validate}=require('./config');const {openDatabase}=require('./database');const {ViewerRepository}=require('./repository');const {ProcessingRepository}=require('./processingRepository');const {StorageManager}=require('./storageManager');const {ProviderCredentials}=require('./providerCredentials');const {processOne}=require('./processingWorker');const {refreshOneProviderHealth}=require('./providerHealth');const {deliverOneEvent}=require('./eventDelivery');const {processOneDerivative}=require('./derivativeWorker');const {processOneDatasetOperation,reconcileCatalogAdoptionRecoveries,reconcileCatalogSourceCleanups}=require('./datasetOperationWorker');const {reconcileStorageMutations,purgeExpiredTrash}=require('./storageLifecycle');const {lodReconciliationFailure,lodReconciliationSummary,reconcileLodMaintenance,reconcileMissingPointCloudAssets}=require('./lodBackfill');const {reconcileMissingOdmGeoreference}=require('./odmGeorefReconciliation');
const problems=validate();if(problems.length){console.error('Processing worker configuration is invalid:',problems.join('; '));process.exit(1);}if(!config.processingPlatformEnabled){const idleDb=openDatabase(config.databasePath),idleProcessing=new ProcessingRepository(idleDb),owner=`worker-idle-${crypto.randomUUID()}`,heartbeat=()=>idleProcessing.recordWorkerHeartbeat(owner,{version:1,enabled:false,idle:true,active:idleProcessing.workerWorkCounts()});heartbeat();const timer=setInterval(heartbeat,10000);console.log('Processing worker is idle because PROCESSING_PLATFORM_ENABLED=false');let closing=false;for(const signal of['SIGINT','SIGTERM'])process.once(signal,()=>{if(closing)return;closing=true;clearInterval(timer);idleDb.close();process.exit(0);});}else{
for(const [enabled,name,bin,args,flag]of[[config.localDerivativesEnabled,'Entwine',config.entwineBin,['--version'],'LOCAL_DERIVATIVES_ENABLED'],[config.meshDerivativesEnabled,'Obj2Tiles',config.obj2TilesBin,['--version'],'MESH_DERIVATIVES_ENABLED']]){if(!enabled)continue;const probe=spawnSync(bin,args,{windowsHide:true,timeout:10000,stdio:'ignore'});if(probe.error||probe.status===null||probe.status!==0){console.error(`${name} is unavailable; disable ${flag} or install the configured executable`);process.exit(1);}}
const db=openDatabase(config.databasePath),repository=new ViewerRepository(db),processing=new ProcessingRepository(db,{logMaxBytes:config.processingLogMaxBytes}),providerCredentials=new ProviderCredentials({processing,activeKeyId:config.providerCredentialsKeyId,keys:config.providerCredentialsKeys,legacyTokens:config.processingProviderTokens}),storage=new StorageManager(config);providerCredentials.migrateLegacy();storage.initialize();const owner=`worker-${crypto.randomUUID()}`;let stopped=false;for(const signal of['SIGINT','SIGTERM'])process.once(signal,()=>{if(stopped)return;stopped=true;console.log(`Processing worker stopping after ${signal}`);});
function heartbeat(){try{processing.recordWorkerHeartbeat(owner,{version:1,nativeOdmOutputs:true,localDerivatives:config.localDerivativesEnabled,meshDerivatives:config.meshDerivativesEnabled,active:processing.workerWorkCounts()});return true;}catch{return false;/* next heartbeat retries */}}
function maintenanceCode(error){return String(error?.code||error?.name||'maintenance_error').replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,80);}
async function maintenanceStep(name,run){try{return await run();}catch(error){console.error(`Maintenance ${name} failed: code=${maintenanceCode(error)}`);return null;}}
let maintenanceActive=false;async function maintenance(){if(maintenanceActive)return;maintenanceActive=true;try{
  await maintenanceStep('upload-finalization-recovery',()=>processing.recoverStaleUploadFinalizations());
  await maintenanceStep('storage-mutation-reconciliation',()=>reconcileStorageMutations(processing,storage,20));
  await maintenanceStep('catalog-source-cleanup',()=>reconcileCatalogSourceCleanups(processing,storage,20));
  await maintenanceStep('catalog-adoption-recovery',()=>reconcileCatalogAdoptionRecoveries(processing,storage,20));
  const georef=await maintenanceStep('odm-georeference-reconciliation',()=>reconcileMissingOdmGeoreference(repository,storage,{limit:5}));if(georef&&(georef.scanned||georef.updated||georef.terminal))console.log(`ODM georeference reconciliation: scanned=${georef.scanned} updated=${georef.updated} terminal=${georef.terminal}`);
  const pointCloud=await maintenanceStep('point-cloud-reconciliation',()=>reconcileMissingPointCloudAssets(processing,storage,{limit:5}));if(pointCloud&&(pointCloud.scanned||pointCloud.registered))console.log(`Point-cloud reconciliation: scanned=${pointCloud.scanned} registered=${pointCloud.registered}`);
  try{const result=reconcileLodMaintenance(processing,storage,{meshDerivativesEnabled:config.meshDerivativesEnabled,limit:20});if(result.recovery.scanned||result.discovery.scanned||result.recovery.requeued||result.discovery.queued||result.recovery.conflicts||result.discovery.conflict)console.log(lodReconciliationSummary(result));}catch(error){console.error(lodReconciliationFailure(error));}
  for(const id of processing.expiredUploads().slice(0,20))await maintenanceStep('expired-upload-cleanup',()=>{processing.expireUpload(id);storage.cleanupUpload(id);});
  await maintenanceStep('trash-retention-purge',()=>purgeExpiredTrash(processing,storage,{actor:owner,limit:20,onPurged:(item)=>repository.audit({actorType:'system',actorId:owner,action:`${item.entityType}.retention_purged`,entityType:item.entityType,entityId:item.entityId})}));
  await maintenanceStep('processing-log-prune',()=>processing.pruneLogs(config.processingLogRetentionDays));
  await maintenanceStep('operation-receipt-prune',()=>processing.pruneSubjectOperationReceipts(7));
  await maintenanceStep('abuse-window-prune',()=>repository.pruneAbuseWindows());
}finally{maintenanceActive=false;}}
const delay=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));async function lane(name,run){while(!stopped){try{if(!await run())await delay(2000);}catch(error){console.error(`${name} lane error:`,error.code||error.name||'worker_error');await delay(2000);}}}
const initialHeartbeat=heartbeat();console.log(`Processing worker started: heartbeat=${initialHeartbeat?'recorded':'pending'} local-derivatives=${config.localDerivativesEnabled?'enabled':'disabled'} mesh-derivatives=${config.meshDerivativesEnabled?'enabled':'disabled'} lanes=dataset-operation,processing,provider-health,derivative,event`);maintenance();const heartbeatTimer=setInterval(heartbeat,10000),maintenanceTimer=setInterval(maintenance,3600000);heartbeatTimer.unref?.();maintenanceTimer.unref?.();
(async()=>{await Promise.all([lane('dataset-operation',()=>processOneDatasetOperation({processing,repository,storage,config},`${owner}:dataset`)),lane('processing',()=>processOne({processing,repository,storage,config,providerCredentials},`${owner}:processing`)),lane('provider-health',()=>refreshOneProviderHealth({processing,providerCredentials,config,owner:`${owner}:health`})),lane('derivative',()=>processOneDerivative({processing,storage,config},`${owner}:derivative`)),lane('event',()=>deliverOneEvent(processing,config))]);clearInterval(heartbeatTimer);clearInterval(maintenanceTimer);db.close();console.log('Processing worker stopped cleanly');})().catch((error)=>{clearInterval(heartbeatTimer);clearInterval(maintenanceTimer);console.error('Processing worker stopped:',error.code||error.name||'worker_error');try{db.close();}catch{}process.exitCode=1;});
}
